= ownCloud Client Releases
:toc: right
:toclevels: 3

== Introduction

include::{partialsdir}release-intro-text.adoc[]

== Desktop Client and Mobile Apps

=== ownCloud Desktop Client

==== Latest Stable Desktop Release (version {latest-desktop-version})

The latest ownCloud Desktop Sync Client release, suitable for production use.

* xref:{latest-desktop-version}@desktop:ROOT:index.adoc[ownCloud Desktop Client Manual]
  ({docs-base-url}/pdf/desktop/{latest-desktop-version}_ownCloud_Desktop_Client_Manual.pdf[Download PDF])

==== Previous Stable Release (version {previous-desktop-version})

* xref:{previous-desktop-version}@desktop:ROOT:index.adoc[ownCloud Desktop Client Manual]
  ({docs-base-url}/pdf/desktop/{previous-desktop-version}_ownCloud_Desktop_Client_Manual.pdf[Download PDF])

=== ownCloud iOS App (iOS 11+)

==== Latest Stable iOS App Release (version {latest-ios-version})

The latest ownCloud iOS App release, suitable for production use.

* xref:{latest-ios-version}@ios-app:ROOT:index.adoc[ownCloud iOS App Manual]
  ({docs-base-url}/pdf/ios-app/{latest-ios-version}_ownCloud_iOS_App_Manual.pdf[Download PDF])

=== ownCloud Android App

==== Latest Stable Android App Release (version {latest-android-version})

The latest ownCloud Android App release, suitable for production use.

* xref:{latest-android-version}@android:ROOT:index.adoc[ownCloud Android App Manual]
  ({docs-base-url}/pdf/android/{latest-android-version}_ownCloud_Android_App_Manual.pdf[Download PDF])

== Building Branded ownCloud Clients (Enterprise only)

Instructions for building branded ownCloud iOS, Android, and Desktop Sync clients.

* {docs-base-url}/branded_clients/[Building Branded ownCloud Clients]
  ({docs-base-url}/branded_clients/Building_Branded_ownCloud_Clients.pdf[Download PDF])

All documentation licensed under the Creative Commons Attribution 3.0 Unported license.
