= ownCloud Documentation Overview
:toc: right
:toclevels: 3

== What is Infinite Scale

Infinite Scale is a *cloud-native microservices-based architecture* and the latest generation of server applications. It does not depend on external software packages like PHP or a database which eliminates all the hassle that comes along with using them. With its modern xref:{latest-ocis-version}@ocis:ROOT:architecture/architecture.adoc[architecture], Infinite Scale provides all xref:{latest-ocis-version}@ocis:ROOT:availability_scaling/availability_scaling.adoc[deployment models] for cloud infrastructure deployments and optimized scaling setups for the best output in return for the invested energy. With the single binary concept, managing the server is much more streamlined over all deployment methods.

With all the measures taken, *security is greatly increased* compared to a LAMP stack. For details read the page about xref:{latest-ocis-version}@ocis:ROOT:security/security.adoc[Security Aspects of Infinite Scale].

Amongst many other features, the most notable benefits of ownCloud Infinite Scale are:

=== Spaces

Spaces are special folders made for teamwork. 

Members of a space enjoy the service of a space manager, who takes care of enough quota and the right people added to a space. Thus a space is the ideal place where school classes, co-workers in business projects or other working groups collaborate. Spaces don't "belong" to individual people, but are assigned to someone with the role of the space manager. For example, school classes can easily be handed over to the next teacher or organizations can transfer project responsibilities if an employee leaves the organization.

Usually space managers are, for example, project leaders or teachers. 
All in all, spaces make life easier for admins by giving space managers the ability of self-service.

=== ownCloud Web

ownCloud Web is bundled with Infinite Scale, has a new design and comes with a brand new look. The goal is to make ownCloud accessible to all people from children to experts. Technically, ownCloud Web is built with VueJS as dedicated client, communicating via well-formed APIs with the Infinite Scale server, just like all the other ownCloud clients. ownCloud Web can be used as app for ownCloud Server but is limited in its capabilities. Nevertheless, switching to ownCloud Web makes a future migration to Infinite Scale easier for users as they are already used to the new UI. ownCloud Web can be customized according to your corporate identity via config values.

=== Collaborative Editing

Editing with Microsoft Online Office 365, Collabora Office and OnlyOffice 

Infinite Scale comes with a ramped-up WOPI protocol server that provides collaborative office document editing with multiple users. It supports Microsoft Online Office 365, Collabora Office and OnlyOffice out of the box and is ready to support more collaborative editors in the near future. With the focus on seamless collaboration, files are locked when opened in an online editor to show others that they are in use and likely to change.

=== Links

In Infinite Scale, we drastically simplified sharing by links. First of all: You can get a link with a single click in ownCloud Web. Second: You can share one and the same link with internal and external people at once and if you change your mind, you can restrict access for example to only internal people of your organization. This feature was known as "private link" in ownCloud 10 and is still available but via the "internal" selection of a link.

=== Cloud Native Deployments

Infinite Scale is a platform built of independent microservices that communicate over the highly efficient gRPC  protocol internally and provide HTTP APIs externally. That gives the flexibility for easy extension, integration and deployment of the entire platform.

For the sake of efficiency, Infinite Scale reduces dependencies and works without a traditional database. This saves administration efforts, hardware resources, attack vectors and energy.

One of the biggest benefits of Infinite Scale is the variety of xref:{latest-ocis-version}@ocis:ROOT:deployment/index.adoc[deployment models] that make the rollout of the platform really easy and independent of the underlying infrastructure as much as possible.

Infinite Scale can be delivered as a xref:{latest-ocis-version}@ocis:ROOT:deployment/binary/binary-setup.adoc[single binary] - which is a self-contained, complete and ready to start compilation of all microservices that are needed to simply start Infinite Scale. Other featured deployment methods are xref:{latest-ocis-version}@ocis:ROOT:deployment/container/container-setup.adoc[docker images] and xref:{latest-ocis-version}@ocis:ROOT:deployment/container/orchestration/orchestration.adoc#docker-compose[docker-compose] files. For setups with scaling requirements all Infinite Scale microservices can be deployed and scaled separately on orchestration infrastructure like xref:{latest-ocis-version}@ocis:ROOT:deployment/container/orchestration/orchestration.adoc#kubernetes-and-helm[Kubernetes].

With that, Infinite Scale provides all deployment models for modern cloud infrastructure deployments and optimized scaling setups to achieve the best output in return for the invested energy. 

=== Infinite Scale Features

[width=100%,cols="~,~,~",options="header"]
|===
| Category
| Component
| Comment
                            
.4+| Storage
| Local (POSIX)
| “ocis” driver (“decomposedfs”), the default filesystem for Infinite Scale

| NFS (POSIX)
| “ocis” driver (“decomposedfs”), the default filesystem for Infinite Scale

| S3
| “s3ng” driver; with decomposedfs for metadata (POSIX)

| ownCloud 10 SQL storage driver
| Needed for parallel deployments with ownCloud 10 and for migration purposes
                                     
.4+| Users & IDM
| Integrated, lightweight user & group management (LibreIDM)
| Out-of-the-box integrated user & group management; can be replaced with external LDAP

| OIDC (LibreConnect)
| OpenID Connect for user authentication and single sign-on based on an integrated identity provider; can be replaced with external identity providers

| User roles system
| Define user roles based on permissions to create a segregation of duties in administration as well as to distinguish user types

| LDAP integration
| Integrate an external LDAP/AD user directory

.8+| Content Collaboration
| File management (upload / download / rename / copy / move / delete / etc.)
| Ability for users to conduct basic file and folder operations as well as synchronization with clients

| Sharing / access management (permissions on data)
| Ability for users to share files and folders with users, groups and via links

| Spaces
| User-independent project and team folders with multiple owners and dedicated behavior

| Deleted files / trash bin
| Ability for users to restore deleted files

| File versioning
| Ability for users to automatically create versions upon file changes and to restore them

| Media viewer (preview)
| Ability for users to preview images, videos and music files in the browser

| File locking
| Ability for users to lock files to prevent concurrent edits
                                                                                         
| Archive download for multiple files and folders
| Ability for users to download multiple files and folders as archives

.5+| Platform
| User settings
| Framework for users to define their settings like web UI language

| Notifications
| Framework to inform users about events in the platform; email notification for the event “Share received”

| File search
| Global search by file name, filter current folder by file name

| File metadata management framework
| Store and retrieve arbitrary metadata related to files

| Event system
| Framework to enable cross-service communication based on events

| Customization
| Web branding (runtime branding based on config values)
| Customize the ownCloud Web frontend according to your corporate identity

.3+| API & Integration
| WebDAV
| API for file operations; API endpoints known from ownCloud 10

| OCS
| Open Collaboration Services, ownCloud-specific API endpoints known from ownCloud 10

| LibreGraph
| Open implementation of the MS Graph API, currently used for the management of spaces

.3+| Administration & Operations
| Technical service metrics
| Load, memory usage, etc. per Infinite Scale service

| Logging
| Technical log for operations and debugging

| Auditing
| Ability to log all operations conducted by users for compliance and traceability

.4+| Deployment
| Single binary
| The simplest way to deploy Infinite Scale for testing

| systemd
| Deploy Infinite Scale as a systemd service

| Docker
| Deploy Infinite Scale using Docker and Docker-Compose

| Helm / Kubernetes
| Deploy Infinite Scale in Kubernetes

.3+| Web Office Integrations
| Collabora Online
| Collabora Online can be integrated via the wopiserver extension; automatic file locking capabilities are available

| ONLYOFFICE
| ONLYOFFICE can be integrated via the wopiserver extension; automatic file locking capabilities are available

| Microsoft Office Online
| Microsoft Office Online can be integrated via the wopiserver extension; automatic file locking capabilities are available

| File Migration
| Cloud Importer
| With the integrated `Cloud Importer`, there is native support for importing files like from Google Cloud or Microsoft OneDrive and via public shares from Nextcloud or ownCloud and other WebDav based file sharing products. "If you can share it, you can import it".
|===

== What is ownCloud Server

ownCloud Server is an open source *LAMP-stack-based* server application that allows you to access your files from anywhere in a secure way. The files are stored on a server running ownCloud. You can access your files via the browser or sync them to your desktop or mobile device like you might know it from oneDrive, Dropbox or others. The difference with ownCloud is, that you stay in control of your data as you can install ownCloud in your own environment.

== Web Interfaces

The web interfaces integrated in ownCoud Infinite Scale and owncloud Server give users native access to their ownCloud cloud data. With no needs for user-side installations, one can just access their data securely from all over the world with just a browser. 

== Apps

=== ownCloud Desktop App

The ownCloud Desktop app is fully compatible with Infinite Scale as well as the recent ownCloud Server. It provides many features like syncing data locally.

For Infinite Scale, the desktop sync app supports the Infinite Scale spaces concept for modern collaboration. Users can select which spaces they are interested in and synchronize these to their desktops. This is supported by a UI where spaces can be selected comfortably, which results in individual and efficient sync connections for each space.

The desktop app comes with many improvements like performance or Windows VFS or improved log file generation and a large number of other topics. 

=== ownCloud Android App

Starting with the new Android app version 4.0, users get full support for Infinite Scale spaces as well as the recent ownCloud Server. Users have comfortable access to the collaboration spaces in all their accounts on their mobile devices. The list of spaces available is dynamically retrieved from the Infinite Scale server and listed along with the cover image and description. 

The Android app is an example of how efficient data management works on the mobile platform with Infinite Scale.

=== ownCloud iOS App

Starting with the new iOS app version 12, users get full support for Infinite Scale, including spaces, as well as the recent ownCloud Server. Users can comfortably access the collaboration spaces in all their accounts on their mobile devices. The list of spaces available is dynamically retrieved from the Infinite Scale server and listed along with the cover image and description. 

The iOS app is an example of how efficient data management works on the mobile platform with Infinite Scale.
