= ownCloud Documentation Overview
:toc: right
:toclevels: 3

== Useful pages

Note that this section always points to the latest server version available. In case you need a different version, select your topic and manually switch to one of the available.

* xref:{latest-server-version}@admin_manual:installation/manual_installation/index.adoc[Manual Installation]

* xref:{latest-server-version}@admin_manual:installation/docker/index.adoc[Installation with Docker]

* xref:{latest-server-version}@admin_manual:configuration/server/occ_command.adoc[OCC Commands]

* xref:{latest-server-version}@admin_manual:configuration/server/config_sample_php_parameters.adoc[Config Parameters]

* xref:{latest-server-version}@admin_manual:configuration/server/caching_configuration.adoc#small-organization-single-server-setup[File Locking and Caching Configuration]

* xref:{latest-server-version}@admin_manual:maintenance/manual_upgrade.adoc[Manual Upgrade]

== Getting ownCloud

You can download and install ownCloud on your own Linux server, try some prefab cloud or virtual machine images, or sign up for hosted ownCloud services.
See the https://owncloud.com/get-started/[Get Started] page for more information.

== Reporting Documentation Bugs & How to Contribute

If you find errors or omissions in any of the manuals, we welcome your bug reports and contributions in fixing them.
Please refer to xref:how_to_contribute.adoc[the contributing guide] for instructions.

== ownCloud Server Releases

include::{partialsdir}maintenance-release-schedule-link.adoc[]

The _Administrator_, _User_, and _Developer_ manuals for the current stable release are always at: {docs-base-url}/#current-stable-server-release.

=== Latest Stable Release (version {latest-server-version})

* xref:{latest-server-version}@admin_manual:index.adoc[Administration Manual]
  ({docs-base-url}/server/{latest-server-version}/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* xref:{latest-server-version}@developer_manual:index.adoc[Developer Manual]
  ({docs-base-url}/server/{latest-server-version}/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* xref:{latest-server-version}@user_manual:index.adoc[User Manual]
  ({docs-base-url}/server/{latest-server-version}/user_manual/ownCloud_User_Manual.pdf[Download PDF])

=== Previous Stable Release (version {previous-server-version})

* xref:{previous-server-version}@admin_manual:index.adoc[Administration Manual]
  ({docs-base-url}/server/{previous-server-version}/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* xref:{previous-server-version}@developer_manual:index.adoc[Developer Manual]
  ({docs-base-url}/server/{previous-server-version}/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* xref:{previous-server-version}@user_manual:index.adoc[User Manual]
  ({docs-base-url}/server/{previous-server-version}/user_manual/ownCloud_User_Manual.pdf[Download PDF])

=== ownCloud X Appliance

The ownCloud X Appliance is a complete virtual machine image running ownCloud X, on _Univention Server_.

* xref:master@admin_manual:appliance/index.adoc[ownCloud X Appliance Manual]

== Desktop Client and Mobile Apps

=== ownCloud Desktop Client

==== Latest Stable Desktop Release (version {latest-desktop-version})

The latest ownCloud Desktop Sync Client release, suitable for production use.

* xref:{latest-desktop-version}@desktop:ROOT:index.adoc[ownCloud Desktop Client Manual]
  ({docs-base-url}/desktop/{latest-desktop-version}/ownCloud_Desktop_Client_Manual.pdf[Download PDF])

==== Previous Stable Release (version {previous-desktop-version})

* xref:{previous-desktop-version}@desktop:ROOT:index.adoc[ownCloud Desktop Client Manual]
  ({docs-base-url}/desktop/{previous-desktop-version}/ownCloud_Desktop_Client_Manual.pdf[Download PDF])

=== ownCloud Android App

* xref:master@android:ROOT:index.adoc[ownCloud Android App Manual]
  (Download PDF)

=== ownCloud iOS App (iOS 11+)

* xref:master@ios-app:ROOT:index.adoc[ownCloud iOS App Manual]

=== Building Branded ownCloud Clients (Enterprise only)

Instructions for building branded ownCloud iOS, Android, and Desktop Sync clients.

* {docs-base-url}/branded_clients/[Building Branded ownCloud Clients]
  ({docs-base-url}/branded_clients/Building_Branded_ownCloud_Clients.pdf[Download PDF])

== Older ownCloud Server Releases

include::{partialsdir}maintenance-release-schedule-link.adoc[]

These are the older ownCloud releases.
Users of these releases are *strongly encouraged* to upgrade to the latest production release.

[discrete]
=== ownCloud 10.6

* {docs-base-url}/server/10.6/admin_manual/[Administration Manual]
  ({docs-base-url}/server/10.6/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.6/developer_manual/[Developer Manual]
  ({docs-base-url}/server/10.6/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.6/user_manual/[User Manual]
  ({docs-base-url}/server/10.6/user_manual/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 10.5

* {docs-base-url}/server/10.5/admin_manual/[Administration Manual]
  ({docs-base-url}/server/10.5/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.5/developer_manual/[Developer Manual]
  ({docs-base-url}/server/10.5/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.5/user_manual/[User Manual]
  ({docs-base-url}/server/10.5/user_manual/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 10.4

* {docs-base-url}/server/10.4/admin_manual/[Administration Manual]
  ({docs-base-url}/server/10.4/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.4/developer_manual/[Developer Manual]
  ({docs-base-url}/server/10.4/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.4/user_manual/[User Manual]
  ({docs-base-url}/server/10.4/user_manual/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 10.3

* {docs-base-url}/server/10.3/admin_manual/[Administration Manual]
  ({docs-base-url}/server/10.3/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.3/developer_manual/[Developer Manual]
  ({docs-base-url}/server/10.3/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.3/user_manual/[User Manual]
  ({docs-base-url}/server/10.3/user_manual/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 10.2

* {docs-base-url}/server/10.2/admin_manual/[Administration Manual]
  ({docs-base-url}/server/10.2/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.2/developer_manual/[Developer Manual]
  ({docs-base-url}/server/10.2/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.2/user_manual/[User Manual]
  ({docs-base-url}/server/10.2/user_manual/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 10.1

* {docs-base-url}/server/10.1/admin_manual/[Administration Manual]
  ({docs-base-url}/server/10.1/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.1/developer_manual/[Developer Manual]
  ({docs-base-url}/server/10.1/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.1/user_manual/[User Manual]
  ({docs-base-url}/server/10.1/user_manual/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 10.0

* {docs-base-url}/server/10.0/admin_manual/[Administration Manual]
  ({docs-base-url}/server/10.0/admin_manual/ownCloud_Admin_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.0/developer_manual/[Developer Manual]
  ({docs-base-url}/server/10.0/developer_manual/ownCloud_Developer_Manual.pdf[Download PDF])
* {docs-base-url}/server/10.0/user_manual/[User Manual]
  ({docs-base-url}/server/10.0/user_manual/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 9.1

* {docs-base-url}/server/9.1/admin_manual/[Administration Manual]
  ({docs-base-url}/server/9.1/ownCloud_Server_Administration_Manual.pdf[Download PDF])
* {docs-base-url}/server/9.1/developer_manual/[Developer Manual]
  ({docs-base-url}/server/9.1/ownCloudDeveloperManual.pdf[Download PDF])
* {docs-base-url}/server/9.1/user_manual/[User Manual]
  ({docs-base-url}/server/9.1/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 9.0

* {docs-base-url}/server/9.0/admin_manual/[Administration Manual]
  ({docs-base-url}/server/9.0/ownCloud_Server_Administration_Manual.pdf[Download PDF])
* {docs-base-url}/server/9.0/developer_manual/[Developer Manual]
  ({docs-base-url}/server/9.0/ownCloudDeveloperManual.pdf[Download PDF])
* {docs-base-url}/server/9.0/user_manual/[User Manual]
  ({docs-base-url}/server/9.0/ownCloud_User_Manual.pdf[Download PDF])

[discrete]
=== ownCloud 8.2

* {docs-base-url}/server/8.2/admin_manual/[Administration Manual]
  ({docs-base-url}/server/8.2/ownCloud_Server_Administration_Manual.pdf[Download PDF])
* {docs-base-url}/server/8.2/developer_manual/[Developer Manual]
  ({docs-base-url}/server/8.2/ownCloudDeveloperManual.pdf[Download PDF])
* {docs-base-url}/server/8.2/user_manual/[User Manual]
  ({docs-base-url}/server/8.2/ownCloud_User_Manual.pdf[Download PDF])

All documentation licensed under the Creative Commons Attribution 3.0 Unported license.
