= Infinite Scale Server Release Notes
:toc: macro
:toclevels: 2
:toc-title: Releases

:release-roadmap-url: https://github.com/owncloud/ocis/blob/master/docs/ocis/release_roadmap.md

:description: Dear Infinite Scale administrator, find below the changes and known issues in Infinite Scale that need your attention.

{description} Also see our {release-roadmap-url}[release roadmap] for additional information.

{empty} +

toc::[]

== Infinite Scale 4.0.4

[discrete]
=== General

This is a patch release only, please update as soon as possible.

[discrete]
=== Enhancement

* Update Reva to improve trash bin listing: https://github.com/owncloud/ocis/pull/7858[#7858]

== Infinite Scale 4.0.3

[discrete]
=== General

This is a patch release only, please update as soon as possible.

[discrete]
=== Issues Fixed

* Bump Reva to 2.16.1. https://github.com/owncloud/ocis/pull/7350[#7350]

* We fixed a problem where the states of received shares were reset to PENDING in the +
`ocis migrate rebuild-jsoncs3-indexes` command. https://github.com/owncloud/ocis/issues/7319[#7319]

* We fixed an issue that allowed two schools to be created with the same school number.  https://github.com/owncloud/ocis/pull/7351[#7351]

* Disable username validation for Keycloak example. https://github.com/owncloud/ocis/pull/7230[#7230] +
Set `GRAPH_USERNAME_MATCH` to `none` to accept any username that is also valid for Keycloak.

* Actually pass `PROXY_OIDC_SKIP_USER_INFO` option to OIDC client middleware.  https://github.com/owncloud/ocis/pull/7220[#7220]

[discrete]
=== Enhancement

* Add `OCIS_LDAP_BIND_PASSWORD` as replacement for `LDAP_BIND_PASSWORD`.  https://github.com/owncloud/ocis/issues/7176[#7176] +
The enviroment variable `OCIS_LDAP_BIND_PASSWORD` was added to be more consistent with all other global LDAP variables. `LDAP_BIND_PASSWORD` is deprecated now and scheduled for removal with the 5.0.0 release. We also deprecated `LDAP_USER_SCHEMA_ID_IS_OCTETSTRING` for removal with 5.0.0. The replacement for it is `OCIS_LDAP_USER_SCHEMA_ID_IS_OCTETSTRING`.

=== Solved Known Issues

* We reintroduced the `USERS_LDAP_USER_SCHEMA_ID` variable which was accidently removed from the users service with the 4.0.0 release. https://github.com/owncloud/ocis/issues/7312[#7312]

== Infinite Scale 4.0.2

[discrete]
=== General

This is a patch release only, please update as soon as possible.

[discrete]
=== Issues Fixed

* Fixed a problem where the states of received shares were reset to PENDING in the `ocis migrate rebuild-jsoncs3-indexes` command. https://github.com/owncloud/ocis/pull/7336[#7336]

* Fixed an issue that allowed two schools to be created with the same school number. https://github.com/owncloud/ocis/pull/7351[#7351]

* Actually pass `PROXY_OIDC_SKIP_USER_INFO` option to oidc client middleware. https://github.com/owncloud/ocis/pull/7220[#7220]

* Reintroducing the `USERS_LDAP_USER_SCHEMA_ID` variable which was accidently removed from the users service
with the 4.0.0 release. https://github.com/owncloud/ocis/pull/7321[#7321]

* Always pass adjusted default nats options. https://github.com/cs3org/reva/pull/4214[cs3org/reva#4214]

* In the yaml example for Keycloak, set `GRAPH_USERNAME_MATCH` to `none`, to accept any username that is
also valid for keycloak. https://github.com/owncloud/ocis/pull/7230[#7230]

== Infinite Scale 4.0.1

[discrete]
=== General

This is a patch release only, please update as soon as possible.

=== Solved Known Issues

The critical issue identified in Infinite Scale 4.0.0 where users where able to search other users' spaces under certain circumstances has been resolved, see https://github.com/owncloud/ocis/issues/7092[#7092]. 

== Infinite Scale 4.0.0

[discrete]
=== General

This release primarily focuses on performance and stability improvements along with usability enhancements for a more streamlined user experience.

Please find the full list of changes here:

* Infinite Scale: https://github.com/owncloud/ocis/releases/tag/v4.0.0[Changes in 4.0.0]
* Web: https://github.com/owncloud/web/releases/tag/v7.1.0[Changelog for ownCloud Web 7.1.0]

[discrete]
=== Paste to Upload

With the "Paste to upload" feature, you can instantly upload a single file by simply pasting it from your clipboard via kbd:[CTRL+V] / kbd:[CMD+V] in the Web UI. This eliminates the need for traditional file selection and upload methods, providing you an intuitive and swift upload process. Note: For security reasons "Paste to upload" works only for a single file, not for multiple files or a folder. 
https://github.com/owncloud/web/pull/9140[#9140]

[discrete]
=== Fulltext Search: Highlight Matches

Instead of just showing you the files that contain your search terms, it also highlights exactly where those terms are within each document. This will expedite your search for relevant content, saving you from the hassle of manually scanning through lengthy documents. Users can now activate the fulltext search by selecting the btn:[Search only in content] filter chip located on the search results page. This takes away the need for inputting search syntax. https://github.com/owncloud/web/pull/9294[#9294]

[discrete]
=== Search: Location Filter

The location filter feature allows you to refine search by specifying the file location. Now, instead of searching throughout your entire storage system, you can specify to search only within your current folder. This allows for a faster, more accurate search result, saving you precious time and effort. https://github.com/owncloud/web/pull/9304[#9304]

[discrete]
=== Search: Tag Filter

With the tag filter on the search results page, you can now refine your search results by specific tags. If you've assigned tags to your files and folders for better organization, you can utilize these tags as filters in your searches. This means you can narrow down your search results to only show items that carry a specific tag.

For example, if you're looking for a particular project file and you remember tagging it as "Project X", you can input "Project X" in the tag filter, and the search results will only display files and folders with that tag. This new feature is particularly useful when dealing with a large number of files, making your search more efficient and manageable. https://github.com/owncloud/web/pull/9044[#9044], https://github.com/owncloud/web/pull/9096[#9096]

[discrete]
=== Cloud Importer (experimental)

We are excited to announce our new extension: Cloud Importer, designed to import files from other services. With this functionality, you can now seamlessly import files and folders from other services like OneDrive, Google Drive, ownCloud 10 or Nextcloud directly into Infinite Scale.

Effortlessly transfer your work documents, shared files, or entire project folders from these popular cloud storage platforms to your account. Whether you're moving a single document or a large batch of files, the Cloud Importer ensures a smooth, fast, and reliable transfer. Note that the Cloud Importer only imports files, not shares or tags. Think of it as uploading a file, but from a cloud service instead of from your local drive.

The Cloud Importer is disabled by default. To enable this extension, please refer to the xref:{latest-ocis-version}@ocis:ROOT:deployment/container/orchestration/orchestration.adoc#docker-compose-examples[WOPI Docker Compose Deployment] Example. https://github.com/owncloud/ocis/pull/6702[#6702]

This feature is experimental, i.e. its in a preview state, may break and individual production usage must be agreed with ownCloud Support.

[discrete]
=== Simplified Sharing Links

The simplified sharing links make sharing files with both internal and external parties easier than ever, while maintaining the highest levels of security and access control.

With simplified sharing links, you can generate a single, user-friendly link for any file or folder you want to share. This one link is all you need, whether you're sharing with team members within your organization or with external partners and clients.

The advanced design of simplified sharing links respects the permissions of all recipients, regardless of whether they're internal or external. This means that users will only gain the access levels (e.g. view, download, edit) that you authorize. It ensures secure, controlled sharing without compromising on ease of use.

An added benefit for internal users is the visibility of the file location. If permission is granted, internal users can see where the shared file is stored within the organization's file system. This enables them to navigate directly to the file location, eliminating the need to access the file via the shared link every time. This feature is particularly valuable for efficient collaboration and knowledge sharing within teams.

Simplified sharing links combines convenience, control, and clarity in one package. Experience a more streamlined and intuitive way to share files both within and outside your organization, while always maintaining control over your files' security and accessibility.

Note: If you create a sharing link that tries to grant more permissions than internal people have, the internal sharing permissions will take effect for internal people. In other words: The link acts as a "pointer" for internal people. https://github.com/owncloud/web/pull/9299[#9299]

[discrete]
=== File Control Bar

The file control bar is a static, always accessible bar located within the user interface of the document viewer or editor. It is designed to provide a consistent location where users can find and use critical file-related functions such as btn:[close] or btn:[save]. https://github.com/owncloud/web/pull/8442[#8442], https://github.com/owncloud/web/pull/8447[#8447]

[discrete]
=== Links: Directly Open in Editor

When you share a document that has a standard associated application, the link will now open the document directly in its respective app, instead of showing the document as a single file listing as it did previously. This enables recipients to immediately begin viewing or editing the shared document, eliminating the extra step of navigating from the file listing to the actual document.

For instance, if you share a Word document, the recipient can click on the link and the document will open directly in its associated application, such as OnlyOffice or Microsoft Word, depending on the settings. https://github.com/owncloud/web/pull/9046[#9046], https://github.com/owncloud/web/pull/9307[#9307]

[discrete]
=== Drop Files to the Breadcrumb

You can now move files to a parent folder through a simple drag and drop action. Instead of navigating through multiple steps to move files, you can now simply grab the files you want to move and then drop them onto the breadcrumb trail representing the parent folders.

For example, if you're in a subfolder and want to move a file up one level, you can drag the file to the breadcrumb link representing the parent folder. The file will be moved instantly, eliminating the need for traditional cut-and-paste or move-to operations. https://github.com/owncloud/web/pull/9052[#9052]

[discrete]
=== Context Menu on Whitespace

This feature allows you to right-click on any empty space (whitespace) within your file view to access the context menu. This action was previously limited to direct file or folder interaction, but we've expanded its functionality to utilize the whitespace as well, enhancing your control over the workspace. This new context menu provides quick access to commonly used operations. For instance, you can create a new folder directly from the menu, offering an expedited process for organizing your files. In addition, you can easily view details for the current folder, including its contents, shared status, and more, all from the same context menu. https://github.com/owncloud/web/pull/8921[#8921]

[discrete]
=== View Spaces as List

Previously, viewing your spaces was limited to a tiles format. You can now switch to a list view that presents your projects in a clean, streamlined manner. This new view offers an overview of all your spaces, allowing for easy navigation and a concise visual of your work environment.

This list view provides additional information about the space:

* name of the manager
* number of members
* total quota
* used quota
* remaining quota
* status
* last modified date

in a more compact and organized manner. This is particularly useful for users who manage multiple spaces, as it allows for efficient scanning and selection. https://github.com/owncloud/web/pull/9195[#9195]

[discrete]
=== Other Notable Changes

* Bugfix - Fixes for the Infinite Scale postprocessing restart command: Restarts the complete postprocessing pipeline if there is no active postprocessing: https://github.com/owncloud/ocis/pull/6753[#6753]
* Enhancement - Add `ocis decomposedfs check-treesize` maintenance command: Verify the treesize metadata of a space in decomposedfs: https://github.com/owncloud/ocis/pull/6556[#6556]
* Enhancement - Add server-sent events endpoint for notifications: https://github.com/owncloud/ocis/pull/5998[#5998]
* Enhancement - Use reva client selectors to improve performance and scalability: https://github.com/owncloud/ocis/pull/6452[#6452]
* Enhancement - Allow disabling WOPI chat to disable the inline chat in Only Office: https://github.com/owncloud/ocis/pull/6544[#6544]
* Enhancement - Download a whole space as archive: https://github.com/owncloud/web/issues/9056[#9056]
* Enhancement - We've implemented a new solution to deal with long breadcrumbs even with long folder names: https://github.com/owncloud/web/pull/8984[#8984]
* Enhancement - Respect archiver limits. The archiver service announces a limit for the accumulated filesize of the currently selected resources. The web UI now respects those limits and shows a disabled download button once the limit has been reached. https://github.com/owncloud/web/pull/9055[#9055]
* Enhancement - Privacy statement in account menu. We've added the option to add an imprint and privacy statement via the config:
 https://github.com/owncloud/web/issues/9174[#9174]
* Enhancement - Allow local storage for auth token. We've introduced a new env var `WEB_OPTION_TOKEN_STORAGE_LOCAL`. When set to true (default), the auth token will be stored in the browser's local storage instead of the session storage. This will enable a persisted login state across multiple browser tabs. https://github.com/owncloud/web/pull/9386[#9386]
* Enhancement - Add login button to top bar. We've added a login button to the top bar, this might be handy if a user receives a public link, and they want to login with their user account. https://github.com/owncloud/web/pull/9178[#9178]
* Enhancement - Add pagination options to admin settings: https://github.com/owncloud/web/pull/9199[#9199]
* Enhancement - Add batch actions to search result list: https://github.com/owncloud/web/pull/9200[#9200]

=== Known Issues

* A critical issue has been discovered where users where able to search other users' spaces under certain circumstances.
* The environment variable `USERS_LDAP_USER_SCHEMA_ID` variable was accidently removed from the users service.

=== Migrations

* The space index of the decomposedFS will be migrated from symlinks to messagepack. This is an auto migration. See the xref:{latest-ocis-version}@ocis:ROOT:migration/upgrading-ocis.adoc[Upgrading Infinite Scale] documentation for more and important details.
* If you use a customized theme you need to add 3 new color tokens to the theme.json:
+
* `swatch-passive-hover-outline`
* `swatch-primary-muted-hover`
* `swatch-primary-gradient-hover`
+
{empty}
+
These colors ensure, that the primary and outlined buttons (e.g. "Upload" and "New") have a proper hover state.
* If you used `yes` or `no` in your YAML files, please change these values to `true` or `false`. Background: The YAML parser we use does not support `yes` or `no` any more.

=== Breaking Changes

* Client pool selectors have changed from IP addresses `127.0.0.1:9xxx` to service names `com.owncloud.api.*`.  https://github.com/owncloud/ocis/pull/6452[#6452]
* All environment variables that were marked for deprecation in Infinite Scale release 4.0.0 have finally been removed. https://github.com/owncloud/ocis/pull/7099[#7099]

See the xref:{latest-ocis-version}@ocis:ROOT:migration/upgrading-ocis.adoc[Upgrading Infinite Scale] documentation for important details.

== Infinite Scale 3.0.0

[discrete]
=== General

We are pleased to announce the availability of Infinite Scale 3.0.0 along with its clients for Web, Windows, MacOS, Linux, iOS and Android.

Please find the full list of changes here:

* Infinite Scale: https://github.com/owncloud/ocis/releases/tag/v3.0.0[Changes in 3.0.0]
* Web: https://github.com/owncloud/web/releases/tag/v7.0.0[Changelog for ownCloud Web 7.0.0]

[discrete]
=== Antivirus (ICAP)

The Antivirus interface ensures secure file sharing by protecting against Trojans, viruses, and other malicious software. It scans files using an external antivirus scanning engine before storing them, preventing the spread of infected files. The integration of antivirus scanners through ICAP (Internet Content Adaptation Protocol) allows offloading of scanning to a dedicated service, improving performance and scalability. The interface works, for example, with ClamAV, a comprehensive virus scanner that detects various forms of malware in different file types. Read more: xref:{latest-ocis-version}@ocis:ROOT:deployment/services/s-list/antivirus.adoc[Antivirus Service]

Note: Because Infinite Scale is capable of asynchronous post-processing, the system can efficiently handle a large number of simultaneous file scans without causing delays or bottlenecks that keep end users waiting. Read more: xref:{latest-ocis-version}@ocis:ROOT:deployment/services/s-list/postprocessing.adoc#virus-scanning[Postprocessing Service].

[discrete]
=== File Firewall

The file firewall adds an additional layer of security to the file-level. With definable rules and criteria, the admin can restrict file uploads based, for example, on file extensions, mime types or even content. This granular control helps prevent unwanted or unauthorized uploads. 

Note: The file firewall utilizes Infinite Scale's policies service to check whether a requested operation is allowed or not. To do so, Open Policy Agent (OPA) is used to define the set of rules of what is permitted and what is not.
Policies are written in the Rego query language. Read more: xref:{latest-ocis-version}@ocis:ROOT:deployment/services/s-list/policies.adoc[Policies Service].

[discrete]
=== Tags

Tags provide a flexible and intuitive way to categorize files. By assigning relevant tags to files, users can easily locate specific documents through powerful search functions. This eliminates the need to remember precise file names or navigate through complex folder structures, saving valuable time and effort. Unlike traditional folder-based systems, tags offer a flexible way to organize files that transcends rigid hierarchies. Users can assign multiple tags to a single file, enabling them to classify and retrieve documents using different criteria simultaneously. This adaptability allows for personalized organization methods that align with individual preferences and working styles.

Tags are saved as metadata on the storage without the need for a dedicated database to assure resilience and scalability of the system.

[discrete]
=== Fulltext Search

Fulltext search revolutionizes the way you search and retrieve files, making it easier and more efficient to find the information you need. It enables you to search for files based on their content, not just their titles or metadata. This means you can enter keywords or phrases related to the actual text within documents, spreadsheets, presentations, and more. Say goodbye to manually scanning through countless files and folders — finding the right document is now just a search away.
Fulltext search utilizes Apache Tika for more advanced content extraction. Apache Tika ensures lightning-fast search results, delivering near-instantaneous responses to your queries. Whether you have a large document repository or a vast number of files, full text search will provide you with swift and accurate results, enabling you to access the information you need without delay.
With Apache Tika you can search the contents of files of the types: PDF, DOCX, XLSX, PPTX, ODF, HTML, XML, EPUB, RTF, Tar, RAR, AR, CPIO, Zip, 7Zip, Gzip, BZip2 and many more... Read more: xref:{latest-ocis-version}@ocis:ROOT:deployment/services/s-list/search.adoc#tika-extractor[Search Service].

[discrete]
=== Space Templates

Applying a template is a breeze. When creating a new project space, simply right-click on a folder of your choice, select "Create Space from selection" and the entire folder structure, complete with subfolders and files, will be instantly generated for a project space. Save time and ensure consistency by eliminating the need to manually create folders and subfolders every time you start a new project or onboard a new team. Space templates ensure a consistent folder structure across projects providing a standardized, efficient, and customizable approach to organizing your documents. Space Templates are only available to users with the permission to create spaces.

[discrete]
=== Custom User Roles

Infinite Scale ships with the default user roles admin, space admin, user and user light. Each role has different permissions. For example, only space admins can create spaces, but people with the role "User" cannot create a space. With custom roles, you can now configure roles that fit the needs of your organization. For example, if you need custom roles for your school, you can configure the roles "Teacher" and "Pupil" and not give pupils the permission to create public links. If you are interested in creating custom roles, reach out to us on https://talk.owncloud.com/channel/infinitescale[Talk].

[discrete]
=== File Versions: Design Overhaul

File versions received a design overhaul so that you can go back easily in the version history of a file. With the new design of the file versions feature, you now have even easier access to a comprehensive version history for each file. Every time a file is modified or updated, a new version is created and stored, preserving a complete timeline of changes. This allows you to track and revert to previous versions as needed, ensuring data integrity and eliminating the risk of accidental data loss.

[discrete]
=== Administration Settings

This update brings a range of functions to streamline user, group, and space administration, enhancing the overall management experience. Let's explore the exciting new capabilities:

[discrete]
==== Users Administration:

* Filter Chips for Groups and Role: +
https://m2.material.io/components/chips#filter-chips[Filter chips] use tags or descriptive words to filter content. With that, you can now conveniently filter users based on groups and roles, making it easier to locate and manage specific user segments efficiently.

* Batch Actions:
** Quota: +
Administrators can now modify the storage quota for multiple users at once, simplifying the management of storage allocations.
** Add to Group: +
Administrators can add multiple users to a group simultaneously, streamlining the process of assigning users to specific teams or projects.
** Remove from Group: +
Administrators can remove multiple users from a group in one go, ensuring efficient group membership management.
** Disable Login: +
Administrators can now disable login access for multiple users simultaneously, providing better control over user accounts.
** Edit Login (Dis/-allow): +
Administrators can enable or disable login access for multiple users, providing greater flexibility in managing user authentication.

* Edit Username: +
Administrators have the ability to edit the usernames, which is very important if users change their last name. Remember: In ownCloud Server, users where not allowed to marry and/or change names due to technical limitations. With Infinite Scale, marriage and name changes are now possible.

[discrete]
==== Groups Administration:

* Rename Group: +
Administrators can now rename groups, enabling them to update group names to better reflect their purpose or current project.
* Show Members of a Group: +
You can easily view a list of members belonging to a specific group, facilitating better oversight and management of group memberships.
* Filter Members of a Group: +
Administrators can filter group members, making it effortless to locate specific users within a group.

[discrete]
==== Spaces Administration:

List All Spaces: With appropriate permissions, administrators can now view a comprehensive list of all spaces within the organization. The following attributes are visible:

* Space Name
* Managers of the Space
* Amount of Members in the Space
* Remaining Quota
* Last Modified Date
* Status
// *Not visible:*
* View Contents of a Space: Please note that this update does not enable the viewing of contents within a space, including files, space images, or descriptions. This limitation ensures the security and privacy of space contents even from the eyes of an administrator.

[discrete]
=== GDPR Export

This update focuses on fulfilling the legal requirements of Article 20 of the General Data Protection Regulation (GDPR) - the Right to Data Portability. This feature empowers users to exercise greater control over their personal data and ensures compliance with GDPR guidelines.

The GDPR Export feature enables users to easily export where and which personal data stored within Infinite Scale, in compliance with the Right to Data Portability outlined in Article 20 of the GDPR.
Users can now request and receive an export of their personal data in a JSON file, saved to the users' personal files.
The export can be requested at any time in self-service by the user.

[discrete]
=== Secret File Drop

The feature formerly known as "Uploader" has been renamed to "Secret File Drop", but the functionality stays the same: The Secret File Drop feature allows users to generate unique links that can be shared with external parties. Recipients can anonymously drop files through these links without the need for a registered account or visibility into other submissions. This ensures data privacy and eliminates the risk of unauthorized access.

Effortless File Collection: With Secret File Drop, collecting files becomes a seamless process. Simply create a file drop link, share it with recipients, and let them submit files directly without any additional steps or complications. This feature saves time and eliminates the need for manual file collection methods, such as email attachments or physical hand-ins.

[discrete]
=== 3 View Modes

Users can now choose three distinct view modes, enhancing file browsing and navigation options:

* *Compact List View* +
The Compact List View provides a condensed and space-efficient representation of your files and folders, designed for users who prefer a streamlined view.
* *Regular List View* +
The Regular List View offers a familiar and comprehensive approach to file organization.
* *Tiles View* +
The Tiles View introduces a visually appealing and intuitive way to browse your files and folders. In this mode, files and folders are displayed as colorful and resizable tiles, providing a visually engaging experience. Users can preview file contents and relevant details directly within the tiles, allowing for quick identification and navigation. This is particularly beneficial for users who prioritize visual recognition and prefer a visually rich interface.

[discrete]
=== Trash Bins for Spaces

The Separate Trash Bin for Spaces introduces individual trash bins for each space within your organization's file system. A space represents a dedicated area where teams collaborate on specific projects, departments, or initiatives. With this feature, accidental file deletions are a thing of the past, as files deleted within a space are now moved to a separate trash bin specific to that space.

[discrete]
=== Deny Access
The Deny Access feature, which is *experimental and not ready for production environments*, allows users to share folders with groups, but deny access to a single person in that group. Example: If you share the "Birthday Present" folder with all users in the organization, you want to exclude the one person whose birthday is coming up. This use case is now possible, but not yet production ready and disabled by default. To enable this feature, the xref:{latest-ocis-version}@ocis:ROOT:deployment/services/s-list/frontend.adoc#environment-variables[variable] `FRONTEND_OCS_ENABLE_DENIALS` needs to be set to to `true`. Please contact {oc-support-url}[ownCloud Support] or give us your feedback via {oc-central-url}[ownCloud Central] so that we can finalize this long-awaited feature with the help of your testing.

[discrete]
=== Other Notable Changes

- We added a config option for cross-origin resource sharing (CORS) which, for example, allows running the Web UI on another domain. https://github.com/owncloud/ocis/pull/5987[#5987]

- We changed the default behavior of shares: Share receivers have no access to versions. People in spaces with the "Editor" or "Manager" role can still see versions and work with them. https://github.com/owncloud/ocis/pull/5531[#5531]

- With ownCloud Web having transitioned to Vue 3 recently, we would have had to port the settings ui as well. The decision was made to discontinue the settings ui instead. As a result all traces of the settings ui have been removed. The only user facing setting that ever existed in the settings service is now integrated into the `account` page of ownCloud Web (click on top right user menu, then on your username to reach the account page). https://github.com/owncloud/ocis/pull/5463[#5463]

- We changed the default behavior of shares: Share receivers have no access to versions. People in spaces with the "Can edit" or "Can manage" role can still see versions and work with them. https://github.com/owncloud/ocis/pull/5531[#5531]

- To provide more monitoring metrics, we added a debug server to the services "audit", "idm", "userlog", "eventhistory" and "postprocessing". https://github.com/owncloud/ocis/pull/6178[#6178], https://github.com/owncloud/ocis/pull/6153[#6153], https://github.com/owncloud/ocis/pull/6203[#6203], https://github.com/owncloud/ocis/pull/6202[#6202], https://github.com/owncloud/ocis/pull/6204[#6204]

- You can now send prettier notification emails with HTML templates https://github.com/owncloud/ocis/pull/6147[#6147]

- Webfinger: If your deployment consists of multiple instances, the webfinger service offers the right instances for the right users so that they can login without having to rember instance specific urls. https://github.com/owncloud/ocis/pull/5373[#5373], https://github.com/owncloud/ocis/pull/6110[#6110]

- Async postprocessing allows the system to do postprocessing tasks like virusscan, copying of bytes to their final destination, etc. asynchronous to the users request. This is a huge enhancement only available with Infinite Scale!  https://github.com/owncloud/ocis/pull/5207[#5207]

- We introduced a new setting to disable email notifications https://github.com/owncloud/ocis/pull/6137[#6137]

- The LDAP base DN for new groups is now configurable: The LDAP backend for the Graph service introduced a new config option for setting the Parent DN for new groups created via the `/groups/` endpoint. (`GRAPH_LDAP_GROUP_CREATE_BASE_DN`). It defaults to the value of `GRAPH_LDAP_GROUP_BASE_DN`. If set to a different value the `GRAPH_LDAP_GROUP_CREATE_BASE_DN` needs to be a subordinate DN of `GRAPH_LDAP_GROUP_BASE_DN`. All existing groups with a DN outside the `GRAPH_LDAP_GROUP_CREATE_BASE_DN` tree will be treated as read-only groups. So it is not possible to edit these groups. In the UI this is indicated via a lock-icon in the administration settings. https://github.com/owncloud/ocis/pull/5974[#5974]

- Disable login for specific users: This new option in the administration settings allows login to be disabled / enabled for specific users. By setting the `accountEnabled` property to `false` for a user via the graph API, users can be disabled (i.e. they can no longer login). https://github.com/owncloud/ocis/pull/5588[#5588]

- New service `eventhistory`: It is a service that stores events and provides a grpc API to retrieve them. Users will notice this enhancement by the bell on the top right in the Web UI and the corresponding notifications (ex: if a user receives a share or becomes a member of a space). 

- New service `policies`: The policies-service provides a new grpc api which can be used to return whether a requested operation is allowed or not. Open Policy Agent is used to determine the set of rules of what is permitted and what is not.
+
--
2 further levels of authorization build on this:

* *Proxy Authorization* +
The simplest authorization layer is in the proxy, since every request is processed here, only simple decisions that can be processed quickly are made here, more complex queries such as file evaluation are explicitly excluded in this layer.

* *Event Authorization* (needs async post-processing enabled) +
The next layer is event-based as a pipeline step in asynchronous post-processing, since processing at this point is asynchronous, the operations there can also take longer and be more expensive, the bytes of a file can be examined here as an example.

Since the base block is a GRPC API, it is also possible to use it directly. Policies are written in the https://www.openpolicyagent.org/docs/latest/policy-language/[rego query language]. https://github.com/owncloud/ocis/pull/5714[#5714]
--

- Enforce passwords on public links: Added a new config option to enforce passwords on public links with "Uploader,Editor,Contributor" roles. The new options are: `OCIS_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD`,`SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD` and `FRONTEND_OCS_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD`. Check the docs on how to properly set them. https://github.com/owncloud/ocis/pull/5848[#5848]

- We added the possibility to restrict the creation of public links based on user roles (permission). https://github.com/owncloud/ocis/pull/5690[#5690]

- Added possibility to assign roles based on OIDC claims: https://github.com/owncloud/ocis/pull/6048[#6048]

- Default quota based on user role: With this enhancement roles can now be configured with a default quota (eg. Admins should have a default quota of 100GB, Users should have a default quota of 50GB). https://github.com/owncloud/ocis/pull/5616[#5616]

- Set default quota for project spaces: Additionally to `set-space-quota` for setting quota on personal spaces we now have `Drive.ReadWriteQuota.Project` for setting project spaces quota. https://github.com/owncloud/ocis/pull/5660[#5660]

- Automatically emtpy the trashbin (off per default): Introduction of a new cli command to purge old trash-bin items. https://github.com/owncloud/ocis/pull/5500[#5500]

=== Known Issues

- The environment variable xref:{latest-ocis-version}@ocis:ROOT:deployment/services/env-vars-special-scope.adoc[OCIS_LDAP_DISABLE_USER_MECHANISM] is an option to control the behavior for disabling users. The default value is `attribute` and requires configuration on the LDAP server. Enabling and disabling users is LDAP implementation specific.
+
--
- If you are using an external LDAP server you can either set `OCIS_LDAP_DISABLE_USER_MECHANISM` to `none` to disable it completely or to `attribute` in which case you need to set `OCIS_LDAP_USER_ENABLED_ATTRIBUTE` according to your external LDAP server's requirements.
- Additionally and due to a bug recently discovered in the xref:{latest-ocis-version}@ocis:ROOT:deployment/services/s-list/idp.adoc[IDP] service, you must set `OCIS_LDAP_USER_ENABLED_ATTRIBUTE=""` to overwrite the default setting when `OCIS_LDAP_DISABLE_USER_MECHANISM` is set to `none`. This bug will be fixed in a subsequent release.
--

=== Migrations

- Please note the xref:{latest-ocis-version}@ocis:ROOT:migration/upgrading-ocis.adoc#version-2-0-0-to-3-0-0[Upgrading Infinite Scale] documentation.

=== Breaking Changes

- Metadata in MessagePack: Metadata are no longer stored in the xattr of a file, but in a dedicated, more scalable and robust file in the binary `MessagePack` format. https://github.com/cs3org/reva/pull/3728[cs3org/reva#3728]
- The Web UI was updated from Vue.js 2 to Vue.js 3. https://github.com/owncloud/web/issues/7948[#7948]


== Infinite Scale 2.0.0

Infinite Scale 2.0.0 is the first stable release, ready for production scenarios. Infinite Scale bundles with ownCloud Web.

Please find the full list of changes here:

* Infinite Scale: https://github.com/owncloud/ocis/releases/tag/v2.0.0[Changes in 2.0.0]
* Web: https://github.com/owncloud/web/releases/tag/v6.0.0[Changelog for ownCloud Web 6.0.0]

// === Notable Changes
// === Migrations

=== Known Issues

This section will be updated if issues are discovered.

=== Breaking Changes

When upgrading from release candidates:

* https://github.com/owncloud/web/issues/6648[owncloud/web#6648]: Breaks existing bookmarks - they won't resolve anymore.

* A breaking change was introduced for Infinite Scale deployments.
+
[WARNING]
====
In order to make every ocis storage provider ID unique by default, the use use of a random uuidv4 during ocis init was needed. Existing installations need to set this value explicitly or ocis will terminate after the upgrade.

See the https://github.com/owncloud/ocis/releases/tag/v2.0.0[BREAKING CHANGE in ocis deployments] description for details.
====

== Beta Releases

=== Beta 8

Infinite Scale 2.0.0 Beta 8 includes a huge number of smaller bug fixes and polishing all around. It introduces a more efficient and scalable way to store share information and improves the performance of ownCloud Web in many areas very noticeably. Furthermore it is now possible to set user quotas in the UI and administrators can now delete orphaned spaces.

IMPORTANT: When updating from Infinite Scale Beta 7 or lower to Beta 8 it is necessary to run two migration steps from the previous to the new share manager **before** starting the system again.

**Migration for User/Group Shares**

`OCIS_LOG_LEVEL="debug" OCIS_LOG_PRETTY="true" OCIS_LOG_COLOR="true" ocis migrate shares --from cs3 --to jsoncs3`

If you have set up your system with Docker, you can just use the same syntax as with https://doc.owncloud.com/ocis/next/deployment/container/container-setup.html#first-time-start[ocis init]:

```
docker run --rm -it \
    --mount type=bind,source=$PWD/ocis/ocis-config,target=/etc/ocis \
    owncloud/ocis migrate shares
```

**Migration for Public Links**

`OCIS_LOG_LEVEL="debug" OCIS_LOG_PRETTY="true" OCIS_LOG_COLOR="true" ocis migrate publicshares --from cs3 --to jsoncs3`

If you have set up your system with Docker, you can just use the same syntax as with https://doc.owncloud.com/ocis/next/deployment/container/container-setup.html#first-time-start[ocis init]:

```
docker run --rm -it \
    --mount type=bind,source=$PWD/ocis/ocis-config,target=/etc/ocis \
    owncloud/ocis migrate publicshares
```

The most prominent changes in **Infinite Scale 2.0.0 beta8** and ownCloud Web 5.7.0 comprise:

* A new share manager implementation has been added that will store share information in a more efficient and scalable way. https://github.com/owncloud/ocis/issues/4431[ocis#4431] https://github.com/cs3org/reva/pull/3199[reva#3199]
* The number of items per page for pagination has been limited to 100 or 500. The options `1000` and `All` have been removed. https://github.com/owncloud/web/issues/7038[web#7038]
* Further improvements to the web upload performance have been made. https://github.com/owncloud/web/issues/7177[web#7177]
* It is now possible to set/modify user quotas (for personal spaces) in the user management UI. https://github.com/owncloud/web/pull/7182[web#7182]
* A new permission to 'Delete all spaces' has been added to allow the deletion of orphaned Spaces for users with certain roles. This permission has been added to the default 'Admin' role. https://github.com/cs3org/reva/pull/3180 https://github.com/cs3org/reva/pull/3203 https://github.com/owncloud/ocis/issues/4196
* Deleting a user will now also delete their personal space. https://github.com/owncloud/ocis/issues/4195[ocis#4195]
* Space members can now modify shares other members created. https://github.com/cs3org/reva/pull/3192[reva#3192]
* Some translations have been fixed/improved. https://github.com/owncloud/web/issues/7550[web#7550]
* The design of the default login screen has been improved for better consistency with ownCloud Web. https://github.com/owncloud/ocis/pull/4500[ocis#4500]
* Creating duplicate shares with the same recipient (e.g., via group shares or by resharing) will now be prevented. https://github.com/cs3org/reva/pull/3176[reva#3176]
* EXIF orientation information will now be properly used for images. https://github.com/owncloud/ocis/issues/4477[ocis#4477]
* Improvements for quota handling have been made. https://github.com/owncloud/web/pull/7522[web#7522]
* The right sidebar has been improved for smaller screens. https://github.com/owncloud/web/issues/7498[web#7498]
* The visual appearance and usability of the file search feature has been improved. https://github.com/owncloud/web/pull/7586[web#7586]
* The known issue about wrong file paths in file search results has been fixed. https://github.com/owncloud/web/issues/7391[web#7391] https://github.com/owncloud/ocis/pull/4485[ocis#4485]
* The file search now also works properly with shares. https://github.com/owncloud/web/pull/7560[web#7560]
* Creating a new file will now propose a unique file name. https://github.com/owncloud/web/pull/7555[web#7555]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta.8[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.7.0[ownCloud Web changelog] for further details on what has changed.

=== Beta 7

Infinite Scale 2.0.0 beta7 includes stability, security and performance improvements. ownCloud Web has been condensed a bit and the cut/copy/paste feature has been reworked. Web Office can now be configured to use a certain language and system administrators can recover a lost admin password.

The most prominent changes in **Infinite Scale 2.0.0 beta7** and ownCloud Web 5.7.0 rc.10 comprise:

* Files and folders can now be cut/copy/pasted using either action buttons after selecting them or by using well-known keyboard shortcuts. The former copy/paste dialog has been removed. This enables copy/paste across spaces. Cut/paste across spaces is not supported at the moment. https://github.com/owncloud/web/pull/7309[web#7309]
* The Web interface has a generally more condensed appearance. https://github.com/owncloud/web/pull/7363[web#7363]
* The language setting for Web Office applications (like ONLYOFFICE or Collabora Online) can now be configured. https://github.com/owncloud/ocis/pull/4399[ocis#4399] https://github.com/cs3org/reva/pull/3156[cs3org/reva#3156] https://github.com/owncloud/ocis/issues/4367[ocis#4367]
* It is now possible to reset a lost administrator password using the command `ocis idm resetpassword`. https://github.com/owncloud/ocis/issues/4084[ocis#4084] https://github.com/owncloud/ocis/pull/4365[ocis#4365]
* Encryption and authentication settings have been added to the mail server configuration. https://github.com/owncloud/ocis/pull/4443[ocis#4443]
* The authentication middleware has been rewritten to increase security and stability. https://github.com/owncloud/ocis/pull/4374[ocis#4374]
* There's a new endpoint `/app/open-with-web` which allows native clients to open applications like ONLYOFFICE or Collabora Online directly in the web browser. https://github.com/owncloud/ocis/pull/4376[ocis#4367] https://github.com/cs3org/reva/pull/3143[cs3org/reva#3143]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta.7[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.7.0-rc.10[ownCloud Web changelog] for further details on what has changed.

=== Beta 6

Infinite Scale 2.0.0 beta6 includes a huge number of bug fixes, cosmetic and performance improvements. It also brings a lot of improvements and fixes which further hardened the 'Spaces' feature.

The most prominent changes in **Infinite Scale 2.0.0 beta6** and ownCloud Web 5.7.0 comprise:

* The drop area for drag & drop uploads is now shown again. https://github.com/owncloud/web/issues/7080[web#7080]
* Deleting multiple files at once now works properly. https://github.com/owncloud/web/pull/7357[web#7357]
* Some bugs on the 'Shares' page have been addressed (share indicators, declining shares). https://github.com/owncloud/web/pull/7379[web#7379] https://github.com/owncloud/web/pull/7355[web#7355]
* The file list rendering performance has been improved. https://github.com/owncloud/web/issues/7038[web#7038]
* Upload stability in Web has been improved with a better access token handling. https://github.com/owncloud/web/issues/7240[web#7240]
* The file versions of a shared file will now be shown. https://github.com/owncloud/web/pull/7313[web#7313]
* Contextual helper texts for users have been improved. https://github.com/owncloud/web/pull/7404[web#7404]
* The drop menus in the right sidebar (e.g., role picker) have been visually aligned and improved. https://github.com/owncloud/web/pull/7365[web#7365]
* File search will now report the total number of results (if there are more than actually shown). https://github.com/owncloud/web/pull/7267[web#7267]
* Disabling a Space now shows immediate effect to the user. https://github.com/owncloud/web/pull/7334[web#7334]
* Leaving a Space and handing it over to a new Manager now works properly. https://github.com/owncloud/ocis/pull/4244[ocis#4244]
* The sharing autocomplete is not case-sensitive anymore and allows to find share recipients based on all terms in their display name. The substring search has been made configurabe to allow performance optimizations. https://github.com/owncloud/ocis/issues/547[ocis#547]
* Searching in received shares works again. https://github.com/owncloud/ocis/issues/4308[ocis#4308]
* The validation of OIDC access tokens has been improved. https://github.com/owncloud/ocis/issues/3841[ocis#3841]
* It is now possible to provide a list of services that should not start (for scale-out deployments). https://github.com/owncloud/ocis/pull/4254[ocis#4254]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta.6[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.7.0-rc.8[ownCloud Web changelog] for further details on what has changed.

=== Beta 5

Infinite Scale 2.0.0 beta5 includes a huge number of bug fixes and performance improvements. It further finalizes the 'Resharing' feature.

The most prominent changes in **Infinite Scale 2.0.0 beta5** and ownCloud Web 5.7.0 comprise:

* It is now possible to share received shares with other users ('Resharing'). https://github.com/owncloud/web/pull/7086[web#7086]
* It is now possible to add/remove users to/from groups in the integrated IDM UI. https://github.com/owncloud/web/pull/7176[web#7176]
* The authentication logic in ownCloud Web has been improved for highly increased stability. https://github.com/owncloud/web/issues/7030[web#7030]
* Users from the integrated IDM can now change their password on the profile page. https://github.com/owncloud/web/pull/7206[web#7206]
* Alerts in ownCloud Web have been repositioned and redesigned. https://github.com/owncloud/web/pull/7139[web#7139]
* The buttons to access user management and to create new Spaces will now only be shown when the user has the role/permission to use it. https://github.com/owncloud/web/pull/7197[web#7197]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta.5[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.7.0-rc.4[ownCloud Web changelog] for further details on what has changed.

=== Beta 4

Infinite Scale 2.0.0 beta4 introduces the 'Resharing' feature in the backend, brings major improvements for file uploads and adds keyboard shortcuts as well as full drag & drop support in ownCloud Web.

The most prominent changes in **Infinite Scale 2.0.0 beta4** and ownCloud Web 5.7.0 comprise:

* The 'Resharing' feature is now supported in the backend but it will still be disabled as there are some pending changes in Web to make it available. https://github.com/owncloud/ocis/pull/3904[ocis#3904] https://github.com/cs3org/reva/pull/2877[cs3org/reva#2877]
* The performance, stability and reliability of file uploads in Web has been further improved. https://github.com/owncloud/web/pull/7111[web#7111] https://github.com/owncloud/web/pull/7123[web#7123] https://github.com/owncloud/web/pull/7120[web#7120] https://github.com/owncloud/web/pull/7109[web#7109] https://github.com/owncloud/web/pull/7100[web#7100]
* Web now supports keyboard shortcuts for cut (e.g., `CTRL+X`), copy (e.g., `CTRL+C`) and paste (e.g., `CTRL+V`) operations. They apply for selected rows of the file list and enable cross-view cut/copy/paste (Personal space, received shares, project spaces). https://github.com/owncloud/web/pull/7078[web#7078]
* Web now supports drag & drop for move operations in all relevant views. https://github.com/owncloud/web/issues/7122[web#7122]
* Web now shows an upload time estimation. https://github.com/owncloud/web/pull/7088[web#7088]
* The file mimetype associations for the 'Preview' feature can now be customized. https://github.com/owncloud/web/issues/6933[web#6933]
* Further audit events and information have been added (folder creation, acting user). https://github.com/owncloud/ocis/pull/3941[ocis#3941] https://github.com/owncloud/ocis/issues/3753[ocis#3753]
* The `ocis version` command provides proper version information again. https://github.com/owncloud/ocis/pull/3953[ocis#3953]

IMPORTANT: Due to an issue, the `latest` version of the https://github.com/cs3org/wopiserver[WOPI Server extension] that is required for online office integrations (Collabora Online, ONLYOFFICE, Microsoft Office Online) is not compatible with the 2.0.0 beta4 release. Version `8.3.0` of the WOPI Server extension works as expected. 

You can also read the full https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta.4[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.7.0-rc.1[ownCloud Web changelog] for further details on what has changed.

=== Beta 3

The third beta release of Infinite Scale 2.0.0 allows clients to list the contents of "Shares" and rounds-off Spaces with a no-restriction quota feature. Web is shipped with the version 5.5.0-rc.9 and focuses on upload reliability and usability. 

The most prominent changes in **Infinite Scale 2.0.0 beta3** and ownCloud Web 5.5.0 comprise:

* Improved upload UI: The upload stability has been improved, especially for usecases with many small files and complex folder hierarchies. Also the initial view of the upload UI has been simplified and shows now more details, but only on demand. https://github.com/owncloud/web/pull/7067[web#7067] https://github.com/owncloud/web/pull/7036[web#7036] https://github.com/owncloud/web/pull/7032[web#7032]
* Improved "File already exists" dialog: When moving files to a different folder users can now choose to skip, replace or keep conflicting files. If both files should be kept, the existing filename gets extended with a number: filename (1) filename (2) etc. Similar to known dialogs from e.g. Windows or MacOS, users can now apply the chosen option to all conflicts. https://github.com/owncloud/web/pull/6994[web#6994]
* Allow listing of "Shares": Clients can now list the share jail content via `PROPFIND /dav/spaces/\{sharejailid}` https://github.com/cs3org/reva/pull/2931[reva#2931], https://github.com/cs3org/reva/pull/2904[reva#2904]
* Create Spaces without quota restiction: Space managers can now create Spaces without specific quota restrictions like "10 GB". With the quota option "No restriction" Spaces can use up all available storage entirely. This enables a more dynamic storage allocation. https://github.com/cs3org/reva/pull/2895[reva#2895]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta.3[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.5.0-rc.9[ownCloud Web changelog] for further details on what has changed.

=== Beta 2

The Infinite Scale 2.0.0 beta2 release ships the first round of bug fixes and performance improvements. ownCloud Web has received a lot of smaller improvements all around.

The most prominent changes in **Infinite Scale 2.0.0 beta2** and ownCloud Web 5.5.0 comprise:

* OIDC user autoprovisioning with the integrated user management works again. https://github.com/owncloud/ocis/pull/3860[ocis#3860]
* Caching for service discovery has been added. https://github.com/owncloud/ocis/pull/3833[ocis#3833]
* The user quota display now shows the correct values for the respective user's personal space. https://github.com/owncloud/web/pull/6923[web#6923]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta2[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.5.0-rc.8[ownCloud Web changelog] for further details on what has changed.

=== Beta 1

The first beta release of Infinite Scale 2.0.0 (beta1) introduces the `File Search` feature and completely replaces the integrated user management with a lightweight LDAP server that is shipped out-of-the-box (LibreIDM). ownCloud Web introduces a new, feature-rich upload manager based on uppy.io and comes with a couple of design and usability round-offs.

The most prominent changes in **Infinite Scale 2.0.0 beta1** and ownCloud Web 5.5.0 comprise:

* All `breaking changes` of Infinite Scale 1.20.0 Technology Preview have been fixed. Especially the https://github.com/cs3org/wopiserver[WOPI Server extension] is compatible with Infinite Scale 2.0.0 again.

* The `File Search` feature to find files and folders based on their name is now available in the backend and in ownCloud Web. https://github.com/owncloud/ocis/pull/3635[ocis#3635], https://github.com/owncloud/web/pull/6841[web#6841]

* ownCloud Web introduces a new upload manager based on Uppy (https://uppy.io). Uppy provides a well-designed upload manager overlay, integrates seamlessly with the TUS protocol for upload chunking and provides the ability to cancel, pause and resume uploads. https://github.com/owncloud/web/pull/6202[web#6202]

* The existing integrated user management has been replaced by LibreIDM which is a lightweight LDAP server being developed by ownCloud and the LibreGraph community (https://github.com/libregraph/idm). LibreIDM comes with a MS Graph-based API and integrates a user interface for user & group management in ownCloud Web. https://github.com/owncloud/ocis/pull/3331[ocis#3331], https://github.com/owncloud/web/issues/6673[web#6673]

* For security reasons, Infinite Scale will not start anymore without specifying certain secrets. A new command `ocis init` has been added to automatically prepare a new Infinite Scale installation by generating secure default secrets. https://github.com/owncloud/ocis/pull/3551[ocis#3551]

* The `Shares` folder has been moved into a dedicated entry point. It is now available in the left sidebar as `Shares` and will gather all incoming and outgoing shares of the user. With this, the transition to a clear separation of personal, shared and project files is complete. https://github.com/owncloud/web/issues/6448[web#6448]

* Cover images for spaces will now be rendered with an appropriate aspect ratio (16:9). https://github.com/owncloud/web/pull/6829[web#6829]

* When unsharing a file or folder, a confirmation dialog will now appear. https://github.com/owncloud/web/pull/6795[web#6795]

* It is now possible to show/hide file extensions in ownCloud Web using the file list settings. https://github.com/owncloud/web/pull/6793[web#6793]

* Infinite Scale now provides dedicated quick links that can be created using the quick action in the file list. Once created, the quick link will stay until it's removed and will be copied when the quick action is used. https://github.com/owncloud/web/pull/6820[web#6820]

* It is now possible to create links with the `Editor` role for single files. https://github.com/owncloud/web/pull/6787[web#6787]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v2.0.0-beta1[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.5.0-rc.5[ownCloud Web changelog] for further details on what has changed.

[discrete]
=== Known issues

This section will be updated if known issues are discovered.

== Technology Preview Releases

=== Infinite Scale 1.20.0 Technology Preview

Version 1.20.0 brings major improvements, new features and bug fixes to the platform. Infinite Scale now provides complete Auditing capabilities and the basic 'Spaces' feature has reached initial feature completeness. Furthermore, ownCloud Web introduces a number of smaller features as well as more design and usability improvements.

The most prominent changes in Infinite Scale 1.20.0 and ownCloud Web 5.4.0 comprise:

* The implementation of the basic `Auditing` feature is now complete. https://github.com/owncloud/ocis/pull/3467[ocis#3467]

* The implementation of the basic `Spaces` feature is now complete. https://github.com/owncloud/web/pull/6693[web#6693], https://github.com/owncloud/web/pull/6659[web#6659] https://github.com/owncloud/web/pull/6639[web#6639], https://github.com/owncloud/web/pull/6633[web#6633] https://github.com/owncloud/web/pull/6662[web#6662], https://github.com/owncloud/web/pull/6642[web#6642]

* All Space members can now list all links and shares. https://github.com/owncloud/ocis/issues/3370[ocis#3370]

* The LDAP configuration settings have been simplified and unified across services. https://github.com/owncloud/ocis/pull/3476[#3476]

* All sharing options (users & links) are now united in one panel in ownCloud Web. https://github.com/owncloud/web/pull/6701[web#6701]

* The "Media Viewer" in ownCloud Web has been renamed to "Preview". https://github.com/owncloud/web/pull/6514[web#6514]

* ownCloud Web now has support for audio playback in "Preview" (e.g., MP3, WAV, FLAC, OGG). https://github.com/owncloud/web/pull/6514[web#6514]

* The feedback link in ownCloud Web is now customizable. See https://owncloud.dev/clients/web/getting-started/#options[getting started] for more information. https://github.com/owncloud/web/issues/6702[web#6702]

* ownCloud Web now supports full screen mode for external apps like web office. https://github.com/owncloud/web/pull/6688[web#6688]

* ownCloud Web introduces an integrated PDF viewer that user native browser capabilities. https://github.com/owncloud/web/pull/6654[web#6654]

* The Text Editor in ownCloud Web has received a couple of improvements. https://github.com/owncloud/web/pull/6667[web#6667]

* The `Shared with me` and `Shared with others` pages in ownCloud Web have received a couple of improvements. https://github.com/owncloud/web/issues/5976[web#5976], https://github.com/owncloud/web/issues/6140[web#6140]

* The configuration file directory is now configurable. https://github.com/owncloud/ocis/pull/3440[ocis#3440]

* Infinite Scale will not create demo users by default anymore. https://github.com/owncloud/ocis/pull/3474[ocis#3474]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.20.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.4.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: Due to some breaking changes, the https://github.com/cs3org/wopiserver[WOPI Server extension] that is required for online office integrations (Collabora Online, ONLYOFFICE, Microsoft Office Online) is not compatible with the 1.20.0 release. This issue is under investigation and will be fixed with the next releases.

IMPORTANT: The archive download for multiple files and whole folders is currently disabled for public links. This issue is under investigation and will be fixed with the next releases.

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap]

=== Infinite Scale 1.19.1 Technology Preview

Version 1.19.1 is a bugfix release which fixes a regression in version 1.19.0.

* Bugfix - Return correct special item urls: https://github.com/owncloud/ocis/pull/3419[#3419]

=== Infinite Scale 1.19.0 Technology Preview

Version 1.19.0 brings major improvements, new features and bug fixes to the platform. Infinite Scale now has a full audit log and the `Spaces` feature has made a lot of progress towards its initial feature completeness. Sharing inside of spaces was added as well as a spaces aware trashbin. Furthermore, ownCloud Web comes with many design and usability improvements that round off the recent redesign initiative.

The most prominent changes in Infinite Scale 1.19.0 and ownCloud Web 5.3.0 comprise:

* Bugfix - Thumbnails only for accepted shares: https://github.com/owncloud/web/issues/5310[#5310]
* Bugfix - Show no auth popup on password protected public links in ownCloud 10: https://github.com/owncloud/web/pull/6530[#6530]
* Bugfix - Prevent cross-site scripting attack while displaying space description: https://github.com/owncloud/web/pull/6523[#6523]
* Bugfix - Replace public mountpoint fileid with grant fileid in ocdav: https://github.com/cs3org/reva/pull/2646[cs3org/reva#2646]
* Change - Switch NATS backend: https://github.com/cs3org/reva/pull/2574[cs3org/reva#2574]
* Change - Allow LDAP groups to have no gidNumber: https://github.com/cs3org/reva/pull/2667[cs3org/reva#2667]
* Change - Improve quota handling: https://github.com/cs3org/reva/pull/3233[cs3org/reva#3233]
* Change - Use the cs3 share api to manage spaces: https://github.com/cs3org/reva/pull/2600[cs3org/reva#2600]
* Change - Drop json config file support: https://github.com/owncloud/ocis/pull/3366[#3366]
* Change - Settings service now stores its data via metadata service: https://github.com/owncloud/ocis/pull/3232[#3232]
* Enhancement - Contextmenu background hover: https://github.com/owncloud/web/pull/6553[#6553]
* Enhancement - Design improvements: https://github.com/owncloud/web/issues/6492[#6492]
* Enhancement - Improve resource loading within spaces: https://github.com/owncloud/web/pull/6601[#6601]
* Enhancement - Internet Explorer deprecation warning banner: https://github.com/owncloud/web/pull/6629[#6629]
* Enhancement - Load space images as preview: https://github.com/owncloud/web/pull/6529[#6529]
* Enhancement - Resolve private links into folders instead of parent: https://github.com/owncloud/web/issues/5533[#5533]
* Enhancement - Share inheritance indicators: https://github.com/owncloud/web/pull/6613[#6613]
* Enhancement - Shares overview: https://github.com/owncloud/web/issues/6440[#6440]
* Enhancement - Side bar nav tags: https://github.com/owncloud/web/pull/6540[#6540]
* Enhancement - Show space members in share panel for files inside a space: https://github.com/owncloud/web/pull/6554[#6554]
* Enhancement - Allow updating space quota: https://github.com/owncloud/web/pull/6477[#6477]
* Enhancement - Implement edit quota action in spaces overview: https://github.com/owncloud/web/pull/6598[#6598]
* Enhancement - Implement people sharing for spaces: https://github.com/owncloud/web/pull/6455[#6455]
* Enhancement - Implement the spaces permission concept: https://github.com/owncloud/web/pull/6531[#6531]
* Enhancement - Implement people sharing for resources within a space: https://github.com/owncloud/web/pull/6577[#6577]
* Enhancement - Trash bin: https://github.com/owncloud/web/pull/6566[#6566]
* Enhancement - Trash bin breadcrumbs: https://github.com/owncloud/web/pull/6609[#6609]
* Enhancement - Audit logger will now log file events: https://github.com/owncloud/ocis/pull/3332[#3332]
* Enhancement - Add password reset link to login page: https://github.com/owncloud/ocis/pull/3329[#3329]
* Enhancement - Log sharing events in audit service: https://github.com/owncloud/ocis/pull/3301[#3301]
* Enhancement - Add space aliases: https://github.com/owncloud/ocis/pull/3283[#3283]
* Enhancement - Include etags in drives listing: https://github.com/owncloud/ocis/pull/3267[#3267]
* Enhancement - Improve thumbnails API: https://github.com/owncloud/ocis/pull/3272[#3272]
* Enhancement - Add new public share manager: https://github.com/cs3org/reva/pull/2644[cs3org/reva#2644]
* Enhancement - Add new share manager: https://github.com/cs3org/reva/pull/2626[cs3org/reva#2626]
* Enhancement - Add etags to virtual spaces: https://github.com/cs3org/reva/pull/2624[cs3org/reva#2624]
* Enhancement - File Events https://github.com/cs3org/reva/pull/2639[cs3org/reva#2639]
* Enhancement - Add events for sharing action https://github.com/cs3org/reva/pull/2627[cs3org/reva#2627]
* Enhancement - Add space aliases: https://github.com/cs3org/reva/pull/2623[cs3org/reva#2623]
* Enhancement - Add space specific events https://github.com/cs3org/reva/pull/2647[cs3org/reva#2647]
* Enhancement - Add the spaceid to propfind responses https://github.com/cs3org/reva/pull/3345[cs3org/reva#3345]
* Enhancement - Add etag to spaces response https://github.com/cs3org/reva/pull/2616[cs3org/reva#2616]
* Enhancement - Add spaces aware trash-bin API https://github.com/cs3org/reva/pull/2628[cs3org/reva#2628]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.19.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.3.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: Due to some breaking changes, the https://github.com/cs3org/wopiserver[WOPI Server extension] that is required for online office integrations (Collabora Online, ONLYOFFICE, Microsoft Office Online) is not compatible with the 1.19.0 release. This issue is under investigation and will be fixed with the next releases.

IMPORTANT: The archive download for multiple files and whole folders is currently disabled for public links. This issue is under investigation and will be fixed with the next releases.

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap]

=== Infinite Scale 1.18.0 Technology Preview

Version 1.18.0 brings major improvements, new features and bug fixes to the platform. Infinite Scale can now send user notifications via email and the `Spaces` feature has made a lot of progress towards its initial feature completeness. Furthermore, ownCloud Web comes with many design and usability improvements that round off the recent redesign initiative.

The most prominent changes in Infinite Scale 1.18.0 and ownCloud Web 5.2.0 comprise:

* Infinite Scale introduces a notification service to provide user notifications. Currently it can send email notifications for the event of creating a share with another user. The template used for the notification is basic and will be improved with the next versions. See the https://owncloud.dev/services/notifications/[developer documentation] on how to configure notification settings. https://github.com/owncloud/ocis/pull/3217[ocis#3217]

* Spaces now have a right sidebar for Space properties like quota, actions and more. https://github.com/owncloud/web/pull/6437[web#6437]

* Space descriptions and images can now be updated. https://github.com/owncloud/web/pull/6410[web#6410]

* The readme for Spaces can now be modified via a lightweight modal editor. https://github.com/owncloud/web/pull/6509[web#6509]

* Spaces now support thumbnail previews. https://github.com/owncloud/ocis/pull/3219[ocis#3219]

* The design of the breadcrumb in ownCloud Web has been improved. https://github.com/owncloud/web/issues/6218[web#6218]

* The "+ New" button in ownCloud Web has been split into "+ New" and "Upload". The design and context menu have been improved. https://github.com/owncloud/web/issues/6279[web#6279]

* The file list in ownCloud Web has received a number of visual and usability improvements. https://github.com/owncloud/web/issues/6207[web#6207]

* The endpoint to list Spaces now supports sorting by name and last modification time. https://github.com/owncloud/ocis/pull/3201[ocis#3201]

* The Search feature in ownCloud Web has been fixed and improved, e.g., the context menu works again properly (only available on ownCloud 10 currently). https://github.com/owncloud/web/pull/6445[web#6445],  https://github.com/owncloud/web/issues/6496[web#6496]

* Creating a new file now refreshes the file list in ownCloud Web. https://github.com/owncloud/web/issues/5530[web#5530]

* Further improvements have been made to comply with the URL scheme defined in https://owncloud.dev/ocis/adr/0011-global-url-format/#mixed-global-urls[mixed global urls]. https://github.com/owncloud/web/pull/6363[web#6363], https://github.com/owncloud/ocis/pull/3109[ocis#3109]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.18.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.2.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: Due to some breaking changes, the https://github.com/cs3org/wopiserver[WOPI Server extension] that is required for online office integrations (Collabora Online, ONLYOFFICE, Microsoft Office Online) is not compatible with the 1.18.0 release. This issue is under investigation and will be fixed with the next releases.

IMPORTANT: The archive download for multiple files and whole folders is currently disabled for public links. This issue is under investigation and will be fixed with the next releases.

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap]

=== Infinite Scale 1.17.0 Technology Preview

Version 1.17.0 brings major changes, new features and improvements. The Infinite Scale backend introduces an event system as an important platform component and adds support for file locking. ownCloud Web 5.0.0 comes with a full rework of the design and user experience and introduces initial support for the `Spaces` feature. Additionally ownCloud Web now supports Collabora Online with the ownCloud 10 backend.

The most prominent changes in Infinite Scale 1.17.0 and ownCloud Web 5.0.0 comprise:

* Infinite Scale now comes with the foundations of an event system based on https://nats.io[NATS]. The events system allows the oCIS services to communicate between each other based on events and will be the key component for features like notifications, auditing and other event-driven extensions/mechanisms. https://github.com/cs3org/reva/pull/2522[cs3org/reva#2522]

* ownCloud Web has been completely reworked in terms of design and user experience (main layout, app switcher, navigation sidebar, icons, user menu, etc.). https://github.com/owncloud/web/issues/6102[web#6102], https://github.com/owncloud/web/issues/6036[web#6036], https://github.com/owncloud/web/pull/6272[web#6272]

* Initial support for the 'Spaces' feature in Infinite Scale and ownCloud Web has been added. https://github.com/owncloud/web/pull/6254[web#6254], https://github.com/owncloud/web/pull/6199[web#6199], https://github.com/owncloud/web/pull/6262[web#6262], https://github.com/owncloud/ocis/pull/2931[ocis#2931], https://github.com/owncloud/ocis/pull/3095[ocis#3095]

* Infinite Scale now supports file locking on CS3 and WebDAV levels to prevent concurrent/conflicting edits in shared areas. ownCloud Web will soon follow-up with the respective actions and indicators. https://github.com/cs3org/reva/pull/2460[cs3org/reva#2460]

* Spaces can now be disabled, restored and permanently deleted. https://github.com/owncloud/ocis/pull/3092[ocis#3092]

* ownCloud Web now provides a light and dark mode with an interactive switcher. https://github.com/owncloud/web/issues/6242[web#6242]

* ownCloud Web now provides skeleton loading bars in the file list. https://github.com/owncloud/web/pull/6204[web#6204]

* ownCloud Web now provides an ID- and path-based URL scheme according to https://owncloud.dev/ocis/adr/0011-global-url-format/#mixed-global-urls[mixed global url's]. https://github.com/owncloud/web/pull/6137[web#6137]

* ownCloud Web now supports Collabora Online with the ownCloud 10 backend. More information on configuration can be found in the https://owncloud.dev/clients/web/deployments/oc10-app/#collabora-online[documentation].

* ownCloud Web now respects share expiration date enforcement and defaults with the ownCloud 10 backend. https://github.com/owncloud/web/pull/6176[web#6176]

* The People sharing dialog in ownCloud Web has received a couple of improvements. https://github.com/owncloud/web/pull/6039[web#6039]

* ownCloud Web now persists sorting preferences. https://github.com/owncloud/web/issues/5930[web#5930]

* ownCloud Web will now sort properly, even on paginated views. https://github.com/owncloud/web/issues/5687[web#5687]

* The right-click menu works again in public links. https://github.com/owncloud/web/issues/6123[web#6123]

* GraphAPI endpoints for Spaces and user/group management are now available. https://github.com/owncloud/ocis/pull/2858[ocis#2858], https://github.com/owncloud/ocis/pull/2947[ocis#2947], https://github.com/owncloud/ocis/pull/2946[ocis#2946], https://github.com/owncloud/ocis/pull/2978[ocis#2978], https://github.com/owncloud/ocis/pull/2979[ocis#2979]

* Public links with passwords now work properly. https://github.com/owncloud/ocis/pull/2831[ocis#2831]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.17.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v5.0.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

INPORTANT: Due to some breaking changes, the https://github.com/cs3org/wopiserver[WOPI Server extension] that is required for online office integrations (Collabora Online, ONLYOFFICE, Microsoft Office Online) is not compatible with the 1.17.0 release. This issue is under investigation and will be fixed with the next releases.

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap]

=== Infinite Scale 1.16.0 Technology Preview

Version 1.16.0 brings bug fixes, new features and progress for ongoing feature implementations like `Spaces` and application integrations. ownCloud Web comes with a couple of usability improvements (e.g., breadcrumb context menu, right-click menu for multi-select). Infinite Scale has got a revamped config handling that makes deployments easier and more flexible. Additionally, it enables easy and fast collaboration via public links.

The most prominent changes in Infinite Scale 1.16.0 and ownCloud Web 4.6.0 comprise:

* ownCloud Web now provides a context menu in the navigation breadcrumb that allows users to conduct actions for the parent folder (e.g., sharing). https://github.com/owncloud/web/pull/6044[web#6044]

* It is now possible to edit files with integrated applications in public links. https://github.com/cs3org/reva/pull/2310[cs3org/reva#2310]

* Infinite Scale now provides the API endpoints to manage Spaces (e.g., add/remove users, manage their roles). https://github.com/owncloud/ocis/issues/2740[ocis#2740], https://github.com/cs3org/reva/pull/2250[cs3org/reva#2250]

* The config handling in Infinite Scale has received a huge rework to better enable different deployment and configuration models (environment variables, single config file, service-specific config files). More information can be found in the https://owncloud.dev/ocis/config/[documentation]. https://github.com/owncloud/ocis/pull/2708[ocis#2708]

* The right-click context menu in ownCloud Web now works when multiple files have been selected. https://github.com/owncloud/web/pull/5973[web#5973]

* ownCloud Web now shows accessibility-optimized tooltips with absolute dates on relative dates. https://github.com/owncloud/web/pull/6037[web#6037]

* Pagination in folders with many files now works properly again. https://github.com/owncloud/web/pull/6056[web#6056]

* The s3ng metadata storage backend works again. https://github.com/owncloud/ocis/pull/2807[ocis#2807]

* Improvements have been added to support more identity providers (e.g., Authelia). https://github.com/cs3org/reva/pull/2314[cs3org/reva#2314]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.16.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v4.6.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap]

=== Infinite Scale 1.15.0 Technology Preview

Version 1.15.0 brings improvements for the app provider (external application integrations) and more progress on the 'Spaces' feature. Public links now support multi-file and folder downloads as well as all other external application integrations. ownCloud Web 4.5.0 furthermore comes with improvements for use with the ownCloud Classic backend.

The most prominent changes in Infinite Scale 1.15.0 and ownCloud Web 4.5.0 comprise:

* Multi-file and folder downloads as well as other external application (Collabora Online, ONLYOFFICE, CodiMD, etc.) integrations now work in public links. https://github.com/owncloud/web/pull/5924[web#5924]

* New files (created/uploaded and file versions) will now be highlighted in ownCloud Web. https://github.com/owncloud/web/pull/6020[web#6020]

* When using ownCloud Web with the ownCloud Classic backend, Web will now automatically display app entries in the app switcher based on the entries in the app switcher of the Classic UI (e.g., Activity, Market) so that users can easily find and use the apps. https://github.com/owncloud/web/pull/5996[web#5996]

* The width of the right sidebar in the Files app of ownCloud Web has been reduced to make it better usable on medium-sized screens. https://github.com/owncloud/web/pull/5983[web#5983]

* ownCloud Web has received performance and other improvements for external application integrations. https://github.com/owncloud/web/pull/5952[web#5952]

* Spaces: A new API endpoint has been introduced that allows listing all Spaces in an installation. https://github.com/owncloud/ocis/pull/2692[ocis#2692]

* Spaces: A permission has been added to control which users can list all Spaces. https://github.com/cs3org/reva/pull/2207[cs3org/reva#2207]

* The app provider (for external application integrations) has received improvements for announcing and prioritizing applications as well as for error handling. https://github.com/cs3org/reva/pull/2230[cs3org/reva#2230],  https://github.com/cs3org/reva/pull/2263[cs3org/reva#2263], https://github.com/cs3org/reva/pull/2258[cs3org/reva#2258]

* The configuration defaults have been revisited and improved towards better security. https://github.com/owncloud/ocis/issues/2700[ocis#2700]

* IPv6 support for Infinite Scale has been added. https://github.com/owncloud/ocis/pull/2698[ocis#2698]

* A capability for the 'Resharing' feature will now be correctly announced. https://github.com/owncloud/ocis/pull/2690[ocis#2690]

* Restoring a file version now works properly. https://github.com/cs3org/reva/pull/2270[cs3org/reva#2270]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.15.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v4.5.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap]

=== Infinite Scale 1.14.0 Technology Preview

Version 1.14.0 brings more progress on the backend for the `Spaces` and `Quota` features. ownCloud Web 4.4.0 has received performance and usability improvements.

The most prominent changes in Infinite Scale 1.14.0 and ownCloud Web 4.4.0 comprise:

* The media viewer in ownCloud Web is now accessible and themeable. https://github.com/owncloud/web/pull/5900[web#5900]

* The share expiration date setting has been moved to a dropdown menu to better fit the interface. https://github.com/owncloud/web/pull/5806[web#5806]

* The performance of ownCloud Web has been improved by removing unnecessary requests and redirects. https://github.com/owncloud/web/pull/5910[web#5910], https://github.com/owncloud/web/pull/5893[web#5893], https://github.com/owncloud/web/pull/5917[web#5917]

* It is now possible for the sysadmin to set a default quota for new Spaces. This way, users with the respective permission can create new Spaces but administrators still keep a leverage on storage usage. https://github.com/owncloud/ocis/pull/2619[ocis#2619]

* The permission to change Space quota is now enforced. https://github.com/owncloud/ocis/pull/2650[ocis#2650]

* The maximum chunk size for upload file chunking has been set to 100 MB which will make chunking apply more frequently resulting in more stable uploads. https://github.com/owncloud/ocis/pull/2584[ocis#2584]

* It is now possible to set a default storage path for Infinite Scale. https://github.com/owncloud/ocis/pull/2590[ocis#2590]

* Infinite Scale services now by default only listen on localhost to prevent accidental exposure. https://github.com/owncloud/ocis/pull/2612[ocis#2612]

* A capability for the user settings endpoint has been added to improve request handling in Web between when used with ownCloud Classic and Infinite Scale, respectively. https://github.com/owncloud/ocis/pull/2655[ocis#2655]

* Requests in public links are now authenticated properly paving the way for Office capabilities in public links. https://github.com/owncloud/ocis/pull/2536[ocis#2536]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.14.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v4.4.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.13.0 Technology Preview

Version 1.13.0 brings progress on the backend for the `Spaces` feature. ownCloud Web and Infinite Scale now provide ZIP/TAR download for multiple files/folders and can integrate external file viewer/editor applications (e.g., Collabora Online, ONLYOFFICE, CodiMD, Microsoft Office Online).

The most prominent changes in Infinite Scale 1.13.0 and ownCloud Web 4.3.0 comprise:

* Infinite Scale and Web now allow downloading multiple files or folders as archives https://github.com/owncloud/ocis/pull/2509[ocis#2509], https://github.com/cs3org/reva/pull/2088[cs3org/reva#2088]

* Infinite Scale and Web can now integrate external applications like file viewers/editors via the https://github.com/cs3org/wopiserver[cs3org/wopiserver] (e.g., Collabora Online, ONLYOFFICE, CodiMD, Microsoft Office Online). https://github.com/owncloud/web/pull/5805[web#5805]

* The `Shared with me` page in ownCloud Web now clearly separates pending, declined and accepted shares. Pending shares are always displayed prominently so that users are aware and can react accordingly. https://github.com/owncloud/web/pull/5814[web#5814]

* Legacy URLs (e.g., from the address bar, public links) from ownCloud Classic are now properly resolved after migrating to Infinite Scale and Web https://github.com/cs3org/reva/pull/1989[cs3org/reva#1089]

* A capability for the Favorites feature has been added https://github.com/owncloud/ocis/pull/2599[ocis#2599]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.13.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v4.3.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.12.0 Technology Preview

Version 1.12.0 is a maintenance release with the foundations for the `Spaces` feature and for viewer/editor application integrations. The Infinite Scale backend has been further hardened by fixing known issues, improving error handling and stabilizing existing features. Apart from bugfixing, ownCloud Web 4.2.0 has received a number of usability and design improvements for sharing and the file list.

The most prominent changes in Infinite Scale 1.12.0 and ownCloud Web 4.2.0 comprise:

* The Infinite Scale backend now supports the first parts of the `Spaces` feature

** Creating a new Space is now possible via Graph API https://github.com/owncloud/ocis/pull/2471[ocis#2471]

** A new sharing role, `Manager`, has been introduced for Spaces https://github.com/cs3org/reva/pull/2065[cs3org/reva#2065]

** A capability for Spaces has been added https://github.com/cs3org/reva/pull/2015[cs3org/reva#2015]

* Infinite Scale now provides an app provider and an app registry as a foundation for integrations with viewer/editor applications. https://github.com/owncloud/ocis/pull/2204[ocis#2204]

* ownCloud Web now has a re-designed sharing role selection. https://github.com/owncloud/web/pull/5632[web#5632]

* ownCloud Web now shows people in sharing as a collapsed list of avatars to save space. This can be expanded to show more details and the full list. https://github.com/owncloud/web/pull/5758[web#5758]

* ownCloud Web now shows sharing information in file/folder details. https://github.com/owncloud/web/issues/5735[web#5735]

* The file size calculation in ownCloud Web has been changed from base-2 (e.g., KB / Kibibyte) to base-10 (e.g., kB / Kilobyte) to match better with user expectations. https://github.com/owncloud/web/pull/5739[web#5739]

* The URL encoding/decoding in ownCloud Web has been improved. https://github.com/owncloud/web/issues/5714[web#5714]

* ownCloud Web now provides a robots.txt file. https://github.com/owncloud/web/pull/5762[web#5762]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.12.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v4.2.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.11.0 Technology Preview

Version 1.11.0 brings new features, usability improvements and bug fixes. ownCloud Web 4.1.0 now supports drag & drop and allows users to do actions (e.g., sharing) for the folder they are currently in.

The most prominent changes in Infinite Scale 1.11.0 and ownCloud Web 4.1.0 comprise:

* ownCloud Web now supports drag & drop to move files/folders. https://github.com/owncloud/web/issues/5592[web#5592]

* The right sidebar in ownCloud Web can now be collapsed and expanded. This change also allows to open the sidebar without selecting a file/folder which will select the current folder and enable the user to do actions (e.g., sharing) for it. https://github.com/owncloud/web/issues/5165[web#5165]

* The right sidebar in ownCloud Web now presents details for multiple selected files/folders. https://github.com/owncloud/web/issues/5164[web#5164]

* The owncloud/ocis Docker image now uses a non-root user for improved security. This is a breaking change for existing Docker deployments. The permission on the files and folders in persistent volumes need to be changed to the UID and GID used for oCIS (default 1000:1000 if not changed by the user). https://github.com/owncloud/ocis/pull/2380[ocis#2380]

* Infinite Scale now supports request tracing through the whole stack to facilitate debugging. https://github.com/cs3org/reva/pull/1984[reva#1984]

* Infinite Scale now provides a WebDAV endpoint for the new Spaces feature https://github.com/cs3org/reva/pull/1803[#1803]

* The Infinite Scale backend has been further hardened by fixing known issues, improving error handling and stabilizing existing features.

* All test scenarios for file-related operations now pass in Infinite Scale (e.g., file operations, trash bin).

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.11.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v4.1.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.10.0 Technology Preview

Version 1.10.0 brings new features, usability improvements and bug fixes. ownCloud Web 4.0.0 now supports ONLYOFFICE document editors and can search/filter files and folders. Furthermore it brings a new context menu for file actions that can be accessed via right click and comes with a big bunch of other notable improvements and fixes.

The most prominent changes in Infinite Scale 1.10.0 and ownCloud Web 4.0.0 comprise:

* ownCloud Web now supports ONLYOFFICE document editors when used with ownCloud Classic Server. See the https://owncloud.dev/clients/web/deployments/oc10-app/#onlyoffice[documentation] for more information on requirements and configuration.

* ownCloud Web now supports global search and filtering for the current folder via the search bar. Both will work when ownCloud Web is used with ownCloud Classic. The Infinite Scale capabilities are currently limited to filtering the current folder. https://github.com/owncloud/web/pull/5415[web#5415]

* A context menu for a file/folder which contains related actions has been introduced to ownCloud Web (in addition to the actions in the right sidebar). https://github.com/owncloud/web/issues/5160[web#5160]

* The context menu for a file/folder in ownCloud Web can be opened via right click and using the "..." menu. https://github.com/owncloud/web/issues/5102[web#5102]

* As a first step of a larger redesign of the sharing dialog in ownCloud Web, the autocomplete and share recipient selection have been redesigned. https://github.com/owncloud/web/pull/5554[web#5554]

* The right sidebar navigation in ownCloud Web has been redesigned. Moving away from structuring all functionality on a single view using accordions, each section now has their own, dedicated view. https://github.com/owncloud/web/pull/5549[web#5549]

* The maximum number of sharing autocomplete suggestions in ownCloud Web can now be configured. See the https://owncloud.dev/clients/web/getting-started/#options[documentation] for more information. https://github.com/owncloud/web/pull/5506[web#5506]

* ownCloud Web works now with ownCloud Classic when OpenID Connect authentication is used. https://github.com/owncloud/web/pull/5536[web#5536]

* ownCloud Web now respects the server-side capability for user avatars. https://github.com/owncloud/web/pull/5178[web#5178]

* The login page has been optimized in regards of accessibility. https://github.com/owncloud/web/issues/5376[web#5376]

* The Infinite Scale backend is being further hardened by fixing known issues, improving error handling and stabilizing existing features.

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.10.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v4.0.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.9.0 Technology Preview

Version 1.9.0 is a feature and maintenance release. More features have been added and the platform was matured further. ownCloud Web 3.4.1 brings usability improvements and new features. The right sidebar now shows details about the selected resource and offers previews for images. View options for the file list and a feedback button have been added.

The most prominent changes in Infinite Scale 1.9.0 and ownCloud Web 3.4.1 comprise:

* The right sidebar in ownCloud Web now shows details about the selected file/folder (e.g., size, owner, sharing status, modification time). https://github.com/owncloud/web/issues/5161[web#5161]

* The right sidebar in ownCloud Web now shows previews for images. https://github.com/owncloud/web/pull/5501[web#5501]

* View options for the file list have been introduced in ownCloud Web. Currently this allows to change the number of files/folders per page and to show/hide hidden files. https://github.com/owncloud/web/pull/5408[web#5408], https://github.com/owncloud/web/pull/5470[web#5470]

* A feedback button has been added to the top bar. It guides the user to an ownCloud Web feedback survey. If undesired, this feature can be disabled in the https://owncloud.dev/clients/web/getting-started/#options[ownCloud Web configuration]. https://github.com/owncloud/web/pull/5468[web#5468]

* Received shares can now be accepted/declined as batches in the "Shared with me" view. https://github.com/owncloud/web/pull/5374[web#5374]

* The oCIS backend now supports to enable extensions by name. https://github.com/owncloud/ocis/pull/2229[ocis#2229]

* Storage drivers can be set to read only. https://github.com/owncloud/ocis/pull/2230[ocis#2230]

* Micro service init has been improved for faster startup. https://github.com/owncloud/ocis/pull/1705[ocis#1705]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.9.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v3.4.1[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.8.0 Technology Preview

Version 1.8.0 is a maintenance and bug fix release. ownCloud Web 3.3.0 has received further performance and major accessibility improvements.

The most prominent changes in Infinite Scale 1.8.0 and ownCloud Web 3.3.0 comprise:

* ownCloud Web is now fully translatable on Transifex https://github.com/owncloud/web/pull/5042[web#5042]

* ownCloud Web now supports keyboard navigation https://github.com/owncloud/web/pull/4937[web#4937], https://github.com/owncloud/web/pull/5013[web#5013], https://github.com/owncloud/web/pull/5027[web#5027], https://github.com/owncloud/web/pull/5147[web#5147]

* ownCloud Web now supports screenreaders https://github.com/owncloud/web/pull/5182[web#5182], https://github.com/owncloud/web/pull/5166[web#5166], https://github.com/owncloud/web/pull/5058[web#5058], https://github.com/owncloud/web/pull/5046[web#5046], https://github.com/owncloud/web/pull/5010[web#5010]

* ownCloud Web has received many performance improvements (image cache, fixes to avoid duplicate resource loading, asynchronous image loading) https://github.com/owncloud/web/pull/5194[web#5194]

* The file lists in ownCloud Web are now paginated to control loading times https://github.com/owncloud/web/pull/5224[web#5224], https://github.com/owncloud/web/pull/5309[web#5309]

* ownCloud Web now supports TypeScript https://github.com/owncloud/web/pull/5194[web#5194]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.8.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v3.3.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.7.0 Technology Preview

Version 1.7.0 is a maintenance and bug fix release. ownCloud Web 3.2.0 has received further performance improvements and minor usability tweaks.

The most prominent changes in Infinite Scale 1.7.0 and ownCloud Web 3.2.0 comprise:

* The S3 storage driver can now be used for testing using the configuration values in the https://owncloud.dev/services/storage-users/[documentation] https://github.com/owncloud/ocis/pull/1886[ocis#1886]

* A confirmation dialog for public link deletion has been added https://github.com/owncloud/web/pull/5125[web#5125]

* To improve performance, the file types which are being rendered as previews can now be specified using an https://owncloud.dev/clients/web/getting-started/#options[allow list in config.json],  https://github.com/owncloud/web/pull/5159[web#5159]

* A warning has been added when a user tries to leave the page while an operation is in progress (e.g., an upload) https://github.com/owncloud/web/issues/2590[web#2590]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.7.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v3.2.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.6.0 Technology Preview

To get the full potential out of the microservice architecture, version 1.6.0 introduces a dynamic service registry to Infinite Scale. The dynamic service registry facilitates the configuration and contributes to the scalability of the platform. ownCloud Web 3.1.0 has received further improvements for accessibility like keyboard navigation and it comes with performance improvements by loading certain elements asynchronously.

The most prominent changes in Infinite Scale 1.6.0 and ownCloud Web 3.1.0 comprise:

* Introducing a dynamic service registry: The dynamic service registry takes care of dynamically assigning network addresses between the oCIS services and enables the services to find and work with each other automatically. It replaces the previous hardcoded service configuration which simplifies the initial setup and makes distributed, scale-out environments a lot easier to handle. https://github.com/cs3org/reva/pull/1509[reva#1509]

* User avatars are now fetched asynchronously, enabling a non-blocking loading of the file list and improving user experience https://github.com/owncloud/owncloud-design-system/pull/1295[design#1295]

* Further accessibility and keyboard navigation improvements have been added https://github.com/owncloud/ocis/pull/1979[ocis#1979], https://github.com/owncloud/ocis/pull/1991[ocis#1991], https://github.com/owncloud/web/pull/4942[web#4942], https://github.com/owncloud/web/pull/4965[web#4965], https://github.com/owncloud/web/pull/4991[web#4991]

* The OCS user deprovisioning endpoint has been added, enabling a full user deprovisioning including storage. https://github.com/owncloud/ocis/pull/1962[ocis#1962]

* Text files (.txt) now have previews (thumbnails) https://github.com/owncloud/ocis/pull/1988[ocis#1988]

* The translations in the Settings and Accounts extensions have been improved https://github.com/owncloud/ocis/pull/2003[ocis#2003]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.6.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v3.1.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

===== Changed oCIS JSON share driver storage format

Related: https://github.com/cs3org/reva/pull/1655[reva#1655]

The storage format of the oCIS JSON share driver has changed. You will be affected if you plan to update from a previous version of oCIS to oCIS 1.6.0, you have shared files or folders with users or groups and you are using the oCIS JSON share driver, which is currently the default share driver.

.Implications:
* manual action required

.Our recommended update strategy to oCIS 1.6.0 is:
. let users note all their shares with users and groups they set up in oCIS
. stop oCIS
. move / delete the JSON share driver storage file `/var/tmp/ocis/storage/shares.json`
. update to oCIS 1.6.0
. let users recreate their shares

===== Fixed / changed oCIS metadata storage driver filesystem path

Related: https://github.com/owncloud/ocis/pull/1956[ocis#1956]

The filesystem path of the oCIS metadata storage driver has changed (been fixed). You will be affected if you plan to update from a previous version of oCIS to oCIS 1.6.0 and are using the oCIS storage driver for metadata storage.

.Implications:
* manual action required

.Our recommended update strategy to oCIS 1.6.0 is:
. let users backup all their data stored in oCIS
. stop oCIS
. prune all oCIS data in `/var/tmp/ocis`
. update to oCIS 1.6.0
. recreate user accounts (can be skipped if an external IDP is used)
. let users upload all their data again
. let users recreate their shares

If you want to use oCIS 1.6.0 without following our recommended update strategy, you can also keep the pre 1.6.0 behaviour by setting this environment variable:

[source,bash]
----
export STORAGE_SYSTEM_ROOT=/var/tmp/ocis/storage/users
----

This may lead to faulty behaviour since both the metadata and user storage driver will be storing their data in the same filesystem path.

=== Infinite Scale 1.5.0 Technology Preview

Version 1.5.0 is a maintenance release for the Infinite Scale backend with a number of bug fixes and smaller improvements. For ownCloud Web it brings further accessibility improvements and a whole bunch of new features. The web interface can now be branded and there is a new, dedicated view in the left sidebar to list all link shares of a user.

The most prominent changes in Infinite Scale 1.5.0 and ownCloud Web 3.0.0 comprise:

* Config file based https://owncloud.dev/clients/web/theming/[theming for ownCloud Web] https://github.com/owncloud/web/pull/4822[web#4822]

* A dedicated view for "Shared by link" has been added https://github.com/owncloud/web/pull/4881[web#4881]

* The file list table has been replaced and is now more performant and accessible https://github.com/owncloud/web/pull/4627[web#4627]

* Many further accessibility improvements have been added, e.g., around the app switcher, sidebar, sharing list and focus management

* User storage quotas will now be enforced https://github.com/cs3org/reva/pull/1557[reva#1557]

* The "owncloud" storage driver now supports file integrity checking with checksums https://github.com/cs3org/reva/pull/1629[reva#1629]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.5.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v3.0.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.4.0 Technology Preview

Version 1.4.0 brings new features, bug fixes and further improvements. The accessibility of ownCloud Web has greatly improved, paving the way for WCAG 2.1 compliance. The Infinite Scale platform has received major improvements regarding memory consumption. The user storage quota feature has been implemented and folder sizes are now properly calculated. It is now possible to write log messages to log files and to specify configuration values using a config file.

The most prominent changes in Infinite Scale 1.4.0 and ownCloud Web 2.1.0 comprise:

* ownCloud Web is now able to use pre-signed url downloads for password protected shares https://github.com/owncloud/core/pull/38376[core#38376]

* Reduced the memory consumption of the runtime drastically (by a factor of 24) https://github.com/owncloud/ocis/pull/1762[ocis#1762]

* Initial quota support to impose storage space restrictions for users (query / set) https://github.com/cs3org/reva/pull/1405[reva#1405]

* Folder sizes are now calculated correctly (tree size accounting) https://github.com/cs3org/reva/pull/1405[reva#1405]

* Added the possibility to write the log to a file with the option to write separated log files by service https://github.com/owncloud/ocis/pull/1816[ocis#1816]

* Added the possibility to specify configuration values for the entire platform in a single config file https://github.com/owncloud/ocis/pull/1762[ocis#1762]

* Added GIF and JPEG file types for thumbnail generation (allows to display thumbnails and use the media viewer for GIF/JPEG images) https://github.com/owncloud/ocis/pull/1791[ocis#1791]

* Fixes for the trash bin feature https://github.com/cs3org/reva/pull/1552[reva#1552]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.4.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v2.1.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

===== Changed oCIS storage driver file layout

Related: https://github.com/cs3org/reva/pull/1452[reva#1452]

Despite a breaking change in the oCIS storage driver file layout, data is not automatically migrated. You will be affected if you plan to update from a previous version of oCIS to oCIS 1.4.0 and are using the oCIS storage driver, which is currently the default storage driver.

.Implications:
* manual action required

.Our recommended update strategy to oCIS 1.4.0 is:
. let users backup all their data stored in oCIS
. stop oCIS
. prune all oCIS data in `/var/tmp/ocis`
. update to oCIS 1.4.0
. recreate user accounts (can be skipped if an external IDP is used)
. let users upload all their data again
. let users recreate their shares

If you already updated to oCIS 1.4.0 without our recommended update strategy you will see no data in oCIS anymore, even after a downgrade to your previous version of oCIS. But be assured that your data is still there.

.You have to follow these steps to be able to access your data again in oCIS:
. stop oCIS
. navigate to `/var/tmp/ocis/storage/users/nodes/root/`
. in this directory you will find directories with UUID as names. These are the home folders of the oCIS users. In the ones with content your oCIS users uploaded to oCIS.
. create an temporary directory e.g. `/tmp/dereferenced-ocis-storage`
. copy the data from oCIS to the temporary directory while dereferencing symlinks. On Linux you can do this by running `cp --recursive --dereference /var/tmp/ocis/storage/users/nodes/root/ /tmp/dereferenced-ocis-storage`
. you now have a backup of all users data in `/tmp/dereferenced-ocis-storage` and can follow our recommended update strategy above


=== Infinite Scale 1.3.0 Technology Preview

Version 1.3.0 is a regular maintenance and bugfix release. It provides the latest improvements to users and administrators.

==== Changes in Reva

https://github.com/cs3org/[Reva] is one of the fundamental components of oCIS. It has these significant changes:

* Align href URL encoding with oc10 https://github.com/cs3org/Reva/pull/1425[reva#1425]
* Fix public link webdav permissions https://github.com/cs3org/Reva/pull/1461[reva#1461]
* Purge non-empty dirs from trash-bin https://github.com/cs3org/Reva/pull/1429[reva#1429]
* Checksum support https://github.com/cs3org/Reva/pull/1400[reva#1400]
* Set quota when creating home directory in EOS https://github.com/cs3org/Reva/pull/1477[reva#1477]
* Add functionality to share resources with groups https://github.com/cs3org/Reva/pull/1453[reva#1453]
* Add s3ng storage driver, storing blobs in a s3-compatible blobstore https://github.com/cs3org/Reva/pull/1428[#reva1428]

==== Changes in oCIS

These are the major changes in oCIS:

* Update ownCloud Web to v2.0.2: https://github.com/owncloud/ocis/pull/1776[ocis#1776]

* Enhancement - Update go-micro to v3.5.1-0.20210217182006-0f0ace1a44a9: https://github.com/owncloud/ocis/pull/1670[ocis#1670]

* Enhancement - Update reva to v1.6.1-0.20210223065028-53f39499762e: https://github.com/owncloud/ocis/pull/1683[ocis#1683]

* Enhancement - Add initial nats and kubernetes registry support: https://github.com/owncloud/ocis/pull/1697[ocis#1697]

More details about this release can be found in the full https://github.com/owncloud/ocis/releases/tag/v1.3.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v2.0.2[ownCloud Web changelog].

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

=== Infinite Scale 1.2.0 Technology Preview

Version 1.2.0 brings more functionality and stability to Infinite Scale. ownCloud Web now loads a lot faster and is prepared for the introduction of accessibility features. An initial implementation for S3 storage support is available and file integrity checking has been introduced.

The most prominent changes in ownCloud Infinite Scale 1.2.0 and ownCloud Web 2.0.0 comprise:

* The initial loading time for ownCloud Web has been reduced by handling dependencies more efficiently (the bundle size of ownCloud Web has been drastically reduced) https://github.com/owncloud/web/pull/4584[web#4584]

* Preparations for accessibility features have been implemented to work towards WCAG 2.1 compliance https://github.com/owncloud/web/pull/4594[web#4594]

* Initial S3 storage support is available https://github.com/cs3org/reva/issues/1429[reva#1429]

* File integrity checking has been introduced: When uploading files, Infinite Scale now makes sure that the file integrity is protected between server and clients by comparing checksums https://github.com/cs3org/reva/issues/1400[reva#1400]

* Public link passwords are now stored as hashes to improve security https://github.com/cs3org/reva/issues/1462[reva#1462]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.2.0[Infinite Scale changelog] and https://github.com/owncloud/web/releases/tag/v2.0.0[ownCloud Web changelog] for further details on what has changed.

==== Breaking changes

IMPORTANT: We are currently in a Tech Preview state and breaking changes may occur at any time. For more information see our {release-roadmap-url}[release roadmap].

===== Fix IDP service user

Related: https://github.com/owncloud/ocis/pull/1390[ocis#1390], https://github.com/owncloud/ocis/issues/1569[ocis#1569]

After upgrading oCIS from a previous version to oCIS 1.2.0 you will not be able to login in ownCloud Web

.Implications:
* manual action required

.Migration steps:
. Stop oCIS
. Open following file `/var/tmp/ocis/storage/metadata/nodes/root/accounts/820ba2a1-3f54-4538-80a4-2d73007e30bf`
. Change password to `$2y$12$ywfGLDPsSlBTVZU0g.2GZOPO8Wap3rVOpm8e3192VlytNdGWH7x72`
. Change onPremisesSamAccountName to `idp`
. Change preferredName to `idp`
. Save the changed file
. Start oCIS
. You now are able to lock back in again.

Please have a look at https://github.com/owncloud/ocis/blob/master/docs/ocis/deployment/_index.md#secure-an-ocis-instance[how to secure an oCIS instance] since you seem to run it with default secrets.

===== Reset shares

Related: https://github.com/owncloud/ocis/pull/1626[ocis#1626]

After upgrading oCIS from a previous version to oCIS 1.2.0 you will will not be able to use previous shares or create new shares.

.Implications:
+ manual action required
* loss of shares (manual resharing is needed, files will not be lost)

.Migration steps:
. Stop oCIS
. Delete following file `/var/tmp/ocis/storage/shares.json`
. Start oCIS
. Recreate shares manually

=== Infinite Scale 1.1.0 Technology Preview

Version 1.1.0 is a hardening and patch release. It ships with the latest version of ownCloud Web and brings a couple of minor improvements. The minor version increase is needed due to non-backwards compatible changes in configuration. The documentation has been updated to reflect the changes. Please note that this version is still a Technology Preview and not suited for production use.

The most prominent changes in Infinite Scale 1.1.0 and ownCloud Web 1.0.1 comprise:

* Performance and stability improvements for installations with multiple concurrent users

* Simplified configuration by introducing the new environment variable OCIS_URL

* Beta release of https://github.com/owncloud/cdperf[ownCloud performance scripts]

* Update ownCloud web to https://github.com/owncloud/web/releases/tag/v1.0.1[v1.0.1]

* Update reva to https://github.com/cs3org/reva/releases/tag/v1.5.1[v1.5.1]

You can also read the full https://github.com/owncloud/ocis/releases/tag/v1.1.0[Infinite Scale changelog] for further details on what has changed.

=== Infinite Scale 1.0.0 Technology Preview

We are pleased to announce the availability of Infinite Scale 1.0.0 Technology Preview which is released as the first public version of the new Infinite Scale platform.

==== Microservice architecture

Infinite Scale is following the microservices architectural pattern. It is implemented as a set of microservices which are independent of each other. They are coupled with well-defined APIs. This architecture fosters a lot of benefits that we were aiming for with the new design for oCIS:

* Every service is independent, comparably small and brings it's own webserver, backend/APIs and frontend components

* Each service runs as a separate service on the system, increasing security and stability

* Scalability:  High performance demands can be fulfilled by scaling and distributing of services

* Testability: Each service can be tested on its own due to well-defined APIs and functionality

* Protocol-driven development using protobuf

* High-performance communication between services through gRPC

* Multi-platform support powered by Golang - only minimal dependency on platform packages

* Cloud-native deployment, update, monitoring, logging, tracing and orchestration strategies

==== Key figures

* The all-new ownCloud Web frontend is shipped as part of the platform

* OpenID Connect is the future-proof technology choice for authentication

* An Identity Provider is bundled to ease deployment and operations. It can be replaced with an external OpenID IdP, if desired

* Automatically built and fully maintained Docker containers are available

* Flexible configuration through environment variables, config files or command-line flags

* Database-less architecture - metadata and data are kept together in the storage as a single source of truth

* Native storage capabilities are used where like native versioning and trashbin

* Public APIs like WebDAV and OCS have been kept compatible with ownCloud 10

* A secure and flexible framework to create extensions

===== Supported platforms

* Linux-amd64
* Darwin-amd64
* Experimental: Windows, ARM (e.g., Raspberry Pi, Termux on Android)

===== Client support

All official ownCloud Clients support the Infinite Scale server with the following versions:

* Desktop >= 2.7
* Android >= 2.15
* iOS >= 1.2

==== Architecture components

Infinite Scale is built as a modular framework in which components can be scaled individually. It consists of

* a user management service
* a settings service
* a frontend service
* a storage backend service
* a built-in IdP
* an application gateway/proxy

These components can be deployed in a multi-tier deployment architecture. See the https://owncloud.dev[developer documentation] for an overview of the services.

==== Operation modes

===== Standalone mode (with oCIS storage driver)

In standalone mode oCIS uses its built-in orchestrator to start all necessary services. This allows you to run oCIS on a single node without any outside dependencies like docker-compose, kubernetes or even a webserver. It will start an OpenID IdP and create a self-signed certificate. You can start right away by navigating to `\https://localhost:9200`

===== Single services scaleout

oCIS allows you to scale individual services using well-known orchestration frameworks like docker-compose, dockerSwarm and kubernetes.

===== Bridge mode with ownCloud 10 backend

For the product transition phase, Infinite Scale comes with an operation mode ("bridge mode") that allows a hybrid deployment, between both server generations to operate the new web frontend with ownCloud 10 and Infinite Scale in parallel. This setup allows the ownCloud Web frontend to operate with both server generations and provides the foundation to migrate users gradually to the new backend.

**Requirements for the bridge mode**

* ownCloud Server >= 10.6
* https://marketplace.owncloud.com/apps/openidconnect[Open ID Connect] is used for user authentication
* The https://marketplace.owncloud.com/apps/graphapi[Graph API] app is installed on ownCloud Server
* The latest client versions are rolled-out to users (required for OpenID Connect support). See the https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/#owncloud-desktop-and-mobile-clients[documentation] for more information.

See the https://owncloud.dev/ocis/deployment/bridge/[documentation] on how to deploy Infinite Scale in bridge mode.

[IMPORTANT]
====
**Technology Preview**

Infinite Scale is currently in Technology Preview. The bridge mode should only be used in non-production environments.
====

==== What to expect?

This is the first promoted public release of Infinite Scale, released as "Technical Preview". Infinite Scale is not yet ready for production installations. Technical audiences will be able to get a good understanding of the potential of ownCloud's new platform.

Version 1.0.0 comes with the base functionality for sync and share with a much higher performance-, stability- and security-level compared to all available platforms. Based on ten years of experience in enterprise sync and share and a long standing collaboration with the biggest global science organizations this new platform will exceed what content collaboration is today.

==== How to get started?

One of the most important objectives for oCIS was to ease the setup of a working instance dramatically. Since oCIS is built with Google's powerful Go language it supports the single-file-deployment: Installing oCIS 1.0.0 is as easy as downloading a single file, applying execution permission to it and get started. No more fiddling around with complicated LAMP stacks.

===== Deployment Options

Given the architecture of Infinite Scale, there are various deployment options based on the users requirements. In our experience setting up the LAMP stack for ownCloud 10 was difficult for many users. Therefore a big emphasis was put on easy yet functional https://owncloud.dev/ocis/deployment/[deployment] strategies.

===== Delivery as single binary

The single binary is the best option to test the new Infinite Scale 1.0.0 Technical Preview release on a local machine. Follow these instructions to get the platform running in the most simple way:

1. Download the binary +
    **Linux** +
    `curl https://download.owncloud.com/ocis/ocis/1.0.0/ocis-1.0.0-linux-amd64 -o ocis` +
    **MacOS** +
    `curl https://download.owncloud.com/ocis/ocis/1.0.0/ocis-1.0.0-darwin-amd64 -o ocis`

2. Make it executable +
    `chmod +x ocis`

3. Run it +
    `./ocis server`

4. Navigate to `\https://localhost:9200` and log in to ownCloud Web (admin:admin)

Production environments will need a more sophisticated setup, see https://owncloud.dev/ocis/deployment/[deployment] for more information.

===== Containerized Setup

For more sophisticated setups we recommend using one of our docker setup examples. See the https://owncloud.dev/ocis/deployment/ocis_traefik/[documentation] for a setup with https://traefik.io/traefik/[Traefik] as a reverse proxy which also includes automated SSL certificate provisioning using Letsencrypt tools.

==== ownCloud Web Features

===== Framework

+ User avatars (compatible with oC 10 API)
* Alerts for information/errors
* Notifications (bell icon, compatible with oC 10 API)
* Extension points
* Available extensions
** Media Viewer (images and videos)
** Draw.io

===== Files

* Listing and browsing the hierarchy
* Sorting by columns (name/size/updated)
* Breadcrumb
* Thumbnail previews for images (compatible with oC 10 API and Thumbnails service API)
* Upload (file/folder), using the TUS protocol for reliable uploads
* Download (file)
* Rename
* Copy
* Move
* Delete
* Indicators for resources shared with people (including subfiles and subfolders)
* Indicators for resources shared by link (including subfiles and subfolders)
* Quick actions
** Add people
** Create public link on-the-fly and copy it to the clipboard
* Favorites (view + add/remove)
* Shared with me (view)
* Shared with others (view)
* Deleted files
* Versions (list/restore/download/delete)
* File/folder search

===== Sharing with People (user/group shares)

* Adding people to a resource
** Adding multiple people at once (users and groups)
** Autocomplete search to find users
** Roles: Viewer / Editor (folder) / Advanced permissions (granular permissions)
** Expiration date

* Listing people who have access to a resource
** People can be listed when a resource is directly shared and when it's indirectly shared via a parent folder
** When listing people of an indirectly shared resource, there is a "via" indicator that guides to the directly shared parent
** Every person can recognize the owner of a resource
** Every person can recognize their role
** The owner of a resource can recognize persons that added other people (reshare indicator)
** Editing persons
** Removing persons

===== Sharing with Links

* Private links (copy)
* Public links
** Adding public links on single files and folders
*** Roles: Viewer / Editor (folder) / Contributor (folder) / Uploader (folder)
*** Password-protection
*** Expiration date

** Listing public links
*** Public links can be listed when a resource is directly shared and when it's indirectly shared via a parent folder
*** When listing public links of an indirectly shared resource, there is a "via" indicator that guides to the directly shared parent
*** Copying existing public links
*** Editing existing public links
** Removing existing public links
** Viewing public links

===== User Profile

* Display basic profile information (user name, display name, e-mail, group memberships)

* "Edit" button guides to ownCloud 10 user settings (when used with oC 10)

====== Basic user settings

* Language of the web interface

==== oCIS Backend Features

===== Storage

The default oCIS storage driver deconstructs a filesystem to be able to efficiently look up files by fileid as well as path. It stores all folders and files by a uuid and persists share and other metadata using extended attributes. This allows using the linux VFS cache using stat syscalls instead of a database or key/value store. The driver implements trash, versions and sharing. It not only serves as the current default storage driver, but also as a blueprint for future storage driver implementations.

===== User and group management

- Functionality available via API and frontend ("Accounts" extension)
- User listing (API/FE)
- User creation (API/FE)
- User deletion (API/FE)
- User activation/blocking (API/FE)
- Role assignment for users (API/FE)
- User editing (API)
- Multi-select in the frontend (delete & block/activate)
- Group creation (API)
- Add/remove users to/from groups (API)
- Group deletion (API)
- Create/read/update/delete users and groups (CLI)

====== Settings

The settings service provides APIs for other services for registering a set of settings as `Bundle`. It also provides a pluggable extension for ownCloud Web which provides dynamically built web forms, so that users can customize their own settings. Some well known settings are directly used by ownCloud Web for adapted user experience, e.g. the UI language. Services can query the users' chosen settings for customized backend and frontend operations as needed.

====== Roles & Permissions System

Infinite Scale follows a role-based access control model. Based on permissions for actions which are provided by the system and by extensions, roles can be composed. Ultimately, these roles can be assigned to users to define what users are permitted to do. This model allows a segregation of duties for administration and allows granular control of how different types of users (e.g., Guests) can use the platform.

* Currently available permissions: Manage accounts (gives access to the internal user management), manage roles (allows assigning roles to users)

* The current roles are exemplary default roles which are used for demonstration purposes
** "Admin": Has the permissions to "manage accounts" and to "manage roles"
** "User": Does not have any dedicated permission
** "Guest": Does not have any dedicated permission

* Currently a user can only have one role

* Users with the role "Admin" can assign/unassign roles to/from other users (as part of the permission to "manage roles")

===== APIs

* WebDAV
* OCS

==== Known issues

* There are feature differences depending on the operation mode, e.g., no user management with ownCloud Web and oC 10 backend

* Public links do not yet respect the given role (a recipient has full permissions no matter which role has been set)

* Resharing does not yet work as expected
** Share recipients can create public links with higher permissions than they originally had
** Share recipients can add other people but they will not be able to access the data

* Sharing indicators in the file list will only be shown after opening the right sidebar for a resource

* Users can't change their password yet

* Folder sizes will not be calculated

* Cleanups are not yet available (e.g., shares of a deleted user will not be removed)

* Sharing from the desktop client does not work yet

* There are no notifications yet

* There can be issues with access tokens not being refreshed correctly, leading to interruptions, e.g., during uploads

* Deleting non-empty folders from the trash bin does not work

* Emptying the whole trash bin does not work

For feedback and bug reports, please use the https://github.com/owncloud/ocis/issues[public issue tracker].
