= ownCloud Releases
:toc: right
:toclevels: 3

== Introduction

ownCloud provides in depth documentation for three different releases. This in depth documentations contain a `online` browser based and `pdf` based version. You can select the online releases via the release selector in the browser window or by replacing the release name in the URL. If you replace the shown release name with `latest` in the URL, you will always be directed to the current stable release if the page exists. The selectable releases are:

- The current stable release
- The last release before the current stable release
- The next upcoming, but not published release

ownCloud also provides a `pdf` only documentation for older releases.

== ownCloud Server Releases

include::{partialsdir}maintenance-release-schedule-link.adoc[]

=== Latest Stable Release (version {latest-server-version})

* xref:{latest-server-version}@admin_manual:index.adoc[Administration Manual]
  ({docs-base-url}/pdf/server/{latest-server-version}_ownCloud_Admin_Manual.pdf[Download PDF])
* xref:{latest-server-version}@developer_manual:index.adoc[Developer Manual]
  ({docs-base-url}/pdf/server/{latest-server-version}_ownCloud_Developer_Manual.pdf[Download PDF])
* xref:{latest-server-version}@user_manual:index.adoc[User Manual]
  ({docs-base-url}/pdf/server/{latest-server-version}_ownCloud_User_Manual.pdf[Download PDF])

=== Previous Stable Release (version {previous-server-version})

* xref:{previous-server-version}@admin_manual:index.adoc[Administration Manual]
  ({docs-base-url}/pdf/server/{previous-server-version}_ownCloud_Admin_Manual.pdf[Download PDF])
* xref:{previous-server-version}@developer_manual:index.adoc[Developer Manual]
  ({docs-base-url}/pdf/server/{previous-server-version}_ownCloud_Developer_Manual.pdf[Download PDF])
* xref:{previous-server-version}@user_manual:index.adoc[User Manual]
  ({docs-base-url}/pdf/server/{previous-server-version}_ownCloud_User_Manual.pdf[Download PDF])

=== ownCloud X Appliance

The ownCloud X Appliance is a complete virtual machine image running ownCloud X, on _Univention Server_.

* xref:master@admin_manual:appliance/index.adoc[ownCloud X Appliance Manual]

== Desktop Client and Mobile Apps

=== ownCloud Desktop Client

==== Latest Stable Desktop Release (version {latest-desktop-version})

The latest ownCloud Desktop Sync Client release, suitable for production use.

* xref:{latest-desktop-version}@desktop:ROOT:index.adoc[ownCloud Desktop Client Manual]
  ({docs-base-url}/pdf/desktop/{latest-desktop-version}_ownCloud_Desktop_Client_Manual.pdf[Download PDF])

==== Previous Stable Release (version {previous-desktop-version})

* xref:{previous-desktop-version}@desktop:ROOT:index.adoc[ownCloud Desktop Client Manual]
  ({docs-base-url}/pdf/desktop/{previous-desktop-version}_ownCloud_Desktop_Client_Manual.pdf[Download PDF])

=== ownCloud iOS App (iOS 11+)

==== Latest Stable iOS App Release (version {latest-ios-version})

The latest ownCloud iOS App release, suitable for production use.

* xref:{latest-ios-version}@ios-app:ROOT:index.adoc[ownCloud iOS App Manual]
  ({docs-base-url}/pdf/ios-app/{latest-ios-version}_ownCloud_iOS_App_Manual.pdf[Download PDF])

=== ownCloud Android App

* xref:master@android:ROOT:index.adoc[ownCloud Android App Manual]
  (Download PDF)

=== Building Branded ownCloud Clients (Enterprise only)

Instructions for building branded ownCloud iOS, Android, and Desktop Sync clients.

* {docs-base-url}/branded_clients/[Building Branded ownCloud Clients]
  ({docs-base-url}/branded_clients/Building_Branded_ownCloud_Clients.pdf[Download PDF])

== Older ownCloud Server Releases

include::{partialsdir}maintenance-release-schedule-link.adoc[]

These are the older ownCloud releases.
Users of these releases are *strongly encouraged* to upgrade to the latest production release.

[discrete]
=== ownCloud 10.6

* Administration Manual {docs-base-url}/pdf/server/10.6_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.6_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.6_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.5

* Administration Manual {docs-base-url}/pdf/server/10.5_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.5_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.5_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.4

* Administration Manual {docs-base-url}/pdf/server/10.4_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.4_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.4_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.3

* Administration Manual {docs-base-url}/pdf/server/10.3_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.3_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.3_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.2

* Administration Manual {docs-base-url}/pdf/server/10.2_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.2_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.2_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.1

* Administration Manual {docs-base-url}/pdf/server/10.1_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.1_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.1_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.0

* Administration Manual {docs-base-url}/pdf/server/10.0_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.0_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.0_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 9.1

* Administration Manual {docs-base-url}/pdf/server/9.1_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/9.1_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/9.1_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 9.0

* Administration Manual {docs-base-url}/pdf/server/9.0_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/9.0_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/9.0_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 8.2

* Administration Manual {docs-base-url}/pdf/server/8.2_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/8.2_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/8.2_ownCloud_User_Manual.pdf[Download PDF]

All documentation licensed under the Creative Commons Attribution 3.0 Unported license.
