= ownCloud Server Releases
:toc: right
:toclevels: 3
:page-aliases: releases.adoc

== Introduction

include::{partialsdir}release-intro-text.adoc[]

== ownCloud Server Releases

include::{partialsdir}maintenance-release-schedule-link.adoc[]

=== Latest Stable Release (version {latest-server-version})

* xref:{latest-server-version}@admin_manual:index.adoc[Administration Manual]
  ({docs-base-url}/pdf/server/{latest-server-version}_ownCloud_Admin_Manual.pdf[Download PDF])
* xref:{latest-server-version}@developer_manual:index.adoc[Developer Manual]
  ({docs-base-url}/pdf/server/{latest-server-version}_ownCloud_Developer_Manual.pdf[Download PDF])
* xref:{latest-server-version}@user_manual:index.adoc[User Manual]
  ({docs-base-url}/pdf/server/{latest-server-version}_ownCloud_User_Manual.pdf[Download PDF])

=== Previous Stable Release (version {previous-server-version})

* xref:{previous-server-version}@admin_manual:index.adoc[Administration Manual]
  ({docs-base-url}/pdf/server/{previous-server-version}_ownCloud_Admin_Manual.pdf[Download PDF])
* xref:{previous-server-version}@developer_manual:index.adoc[Developer Manual]
  ({docs-base-url}/pdf/server/{previous-server-version}_ownCloud_Developer_Manual.pdf[Download PDF])
* xref:{previous-server-version}@user_manual:index.adoc[User Manual]
  ({docs-base-url}/pdf/server/{previous-server-version}_ownCloud_User_Manual.pdf[Download PDF])

=== ownCloud X Appliance

The ownCloud X Appliance is a complete virtual machine image running ownCloud X, on _Univention Server_.

* xref:admin_manual:appliance/index.adoc[ownCloud X Appliance Manual]

== Older ownCloud Server Releases

include::{partialsdir}maintenance-release-schedule-link.adoc[]

These are the older ownCloud releases.
Users of these releases are *strongly encouraged* to upgrade to the latest production release.

[discrete]
=== ownCloud 10.7

* Administration Manual {docs-base-url}/pdf/server/10.7_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.7_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.7_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.6

* Administration Manual {docs-base-url}/pdf/server/10.6_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.6_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.6_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.5

* Administration Manual {docs-base-url}/pdf/server/10.5_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.5_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.5_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.4

* Administration Manual {docs-base-url}/pdf/server/10.4_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.4_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.4_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.3

* Administration Manual {docs-base-url}/pdf/server/10.3_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.3_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.3_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.2

* Administration Manual {docs-base-url}/pdf/server/10.2_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.2_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.2_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.1

* Administration Manual {docs-base-url}/pdf/server/10.1_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.1_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.1_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 10.0

* Administration Manual {docs-base-url}/pdf/server/10.0_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/10.0_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/10.0_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 9.1

* Administration Manual {docs-base-url}/pdf/server/9.1_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/9.1_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/9.1_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 9.0

* Administration Manual {docs-base-url}/pdf/server/9.0_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/9.0_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/9.0_ownCloud_User_Manual.pdf[Download PDF]

[discrete]
=== ownCloud 8.2

* Administration Manual {docs-base-url}/pdf/server/8.2_ownCloud_Admin_Manual.pdf[Download PDF]
* Developer Manual {docs-base-url}/pdf/server/8.2_ownCloud_Developer_Manual.pdf[Download PDF]
* User Manual {docs-base-url}/pdf/server/8.2_ownCloud_User_Manual.pdf[Download PDF]

All documentation licensed under the Creative Commons Attribution 3.0 Unported license.
