= WND Configuration Quick Guide

== Installation

First, you need to install samba packages and libraries that are required for the Windows Network Drives app.

----
sudo apt-get update -y
sudo apt-get install -y smbclient php-smbclient coreutils
----

If you are on Ubuntu 20.04, you will need to add a repository

---
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install smbclient php-smbclient libsmbclient
---

Next you have to enable the Windows Network Drives app:

----
occ app:enable windows_network_drive
----

== Configuration

=== WebUI

Next you will have to configure share.

- Navigate to admin -> settings -> storage (admin section)

- Enable the external storage by ticking the checkbox for it

- Create a new share and choose Windows Network Drives

Now configure:

- Folder Name: A name for the WND Share
- Authentication: Choose Log-in credentials, save in database
- Host: domain name or IP address
- Share: the name of the main share
- Remote Subfolder: enter "$user" to get each user his own home share
- Permission Manager: leave empty for default setups
- Domain: the domain of your server
- Available for: define groups or users this share is for
- Settings: (gear wheel) check the options you need

If you don't plan to use the Windows Network Drives with the **Desktop Sync client**, your configuration ends here.

If you plan to use the sync client, please continue:

=== Command Line

Lastly you need to setup the **wnd listener** and the **wnd process queue** to propagate the changes made directly on the storage of your share to the sync client.

This can be done in 2 ways:

- You configure a new systemd service for the listener and setup a process queue cron job

- You setup a cronjob for the wnd:listen command with flock and a process queue cron job

==== WND Listener Configuration

----
sudo -u www-data php occ wnd:listen <host> <share> <username> <password>
----

Create a service for systemd following the instructions below that checks the share for changes:

- For each WND mount point distinguished by a SERVER - SHARE pair:
	- Place one copy of a file with following content under /etc/systemd/system/owncloud-wnd-listen-SERVER-SHARE.service
	- Replace the all upper case words SERVER, SHARE, USER and PASSWORD in both, the filename and in the contents below with their respective values.
	- Take care to also adjust the paths in WorkingDirectory and ExecStart according to your installation.
	- Password: Create a file readable only by the www-data and outside the directories handled by apache (let’s suppose in /tmp/mypass). The file must contain only the password for the share. In this example our file is: "/tmp/mypass". The listener will read the contents of the file and use them as the password for the account. This way, only root and the apache user should have access to the password.
	- "--password-trim" removes blank characters from the password file added by 3rdparty software or other services.

----
[Unit]
Description=ownCloud WND Listener for SERVER SHARE
After=syslog.target
After=network.target
Requires=apache2.service
[Service]
User=www-data
Group=www-data
WorkingDirectory=/var/www/owncloud
ExecStart=/usr/bin/php ./occ wnd:listen -vvv SERVER SHARE USER --password-file=/tmp/mypass --password-trim
Type=simple
StandardOutput=journal
StandardError=journal
SyslogIdentifier=%n
KillMode=process
RestartSec=1
Restart=always
[Install]
WantedBy=multi-user.target
----

==== WND Process Queue Configuration

----
sudo -u www-data php occ wnd:process-queue <host> <share>
----

- Create or add a crontab file in /etc/cron.d/oc-wnd-process-queue.
- Make a crontab entry to run a script iterating over all SERVER SHARE pairs with an appropriate occ wnd:process-queue command. The commands must be strictly sequential. This can be done by using flock -n and tuning the -c parameter of occ wnd:process-queue

----
* * * * *  sudo -u www-data /usr/bin/php /var/www/owncloud/occ wnd:process-queue <HOST> <SHARE>
----

==== Execution Serialization

Parallel runs of wnd:process-queue might lead to a user lockout. The reason for this is that several wnd:process-queue might use the same wrong password because it hasn’t been updated by the time they fetch it.
It’s recommended to force the execution serialization of the wnd:process-queue command. You might want to use Anacron, which seems to have an option for this scenario, or wrap the command with flock.
If you need to serialize the execution of the wnd:process-queue, check the following example with flock

----
flock -n /my/lock/file sudo -u www-data php occ wnd:process-queue <host> <share>
----

== Troubleshooting

Known Limitations:

- process queue will not work if there is a backslash in the share path configured in webui

