repository:
  name: docs
  description: ownCloud Documentation (v2)
  homepage: https://doc.owncloud.com/
  has_wiki: false
labels:
  - name: 1 - To develop
    color: ededed
  - name: 2 - Developing
    color: ededed
  - name: 3 - To Review
    color: ededed
  - name: 4 - To release
    color: ededed
  - name: Acceptance tests
    color: ededed
  - name: Drone
    color: 6474c1
  - name: 'Effort: 0.5d'
    color: c2e0c6
  - name: 'Effort: 1d'
    color: c2e0c6
  - name: 'Effort: 1w'
    color: c2e0c6
  - name: 'Effort: 2d'
    color: c2e0c6
  - name: 'Effort: 2w'
    color: c2e0c6
  - name: 'Effort: 4d'
    color: c2e0c6
  - name: 'Effort: trivial'
    color: c2e0c6
  - name: Hardening
    color: ededed
  - name: PM prio 1
    color: fbca04
  - name: PM prio 2
    color: fbca04
  - name: PM prio 3
    color: fbca04
  - name: QA
    color: 1d76db
  - name: QA-blocker
    color: 0052cc
  - name: QA-known
    color: 0052cc
  - name: QA-ready
    color: 0052cc
  - name: QA-team
    color: 4cc948
  - name: QA-testing
    color: 0052cc
  - name: Sys Admin
    color: ededed
  - name: WIP
    color: 8c8cea
  - name: Waiting
    color: e6e6e6
  - name: Waiting Internal
    color: e6e6e8
  - name: Waiting On Review/Feedback
    color: ededed
  - name: Waiting on PR merge
    color: fc26105B2929
    description: This PR cannot be merged until another one is.
  - name: work in progress
    color: 9d0ED1
    description: Still in development. Not to be merged.
  - name: bug
    color: fc2929
    description: Something isn't working
  - name: clean up
    color: fc2929
    description: Is a clean up of some part of the existing documentation
  - name: bug-solved
    color: 0e8a16
  - name: clarification request
    color: d4c5f9
  - name: encryption
    color: AD96E8
  - name: dependencies
    color: 0025ff
  - name: design
    color: cc317c
  - name: discussion
    color: fbca04
  - name: enhancement
    color: 02e10c
    description: New feature or request.
  - name: enterpise docs
    color: 6040ad
  - name: enhancement-PM
    color: FF9900
  - name: in progress
    color: ededed
  - name: invalid
    color: ededed
  - name: junior job
    color: f6d300
  - name: needs info
    color: 0b02e1
  - name: overview
    color: fef2c0
  - name: p1-urgent
    color: fc2929
    description: Consider a hotfix release with only that fix (ex: lost trust, money, security issue, ...)
  - name: p2-high
    color: fc2929
    description: Escalation, on top of current planning, release blocker.
  - name: p3-medium
    color: fc2929
    description: Normal priority.
  - name: p4-low
    color: fc2929
    description: Low priority.
  - name: pdf generation
    color: 330272
    description: Anything related to the generation of the PDF manuals.
  - name: packaging
    color: F7C6C7
  - name: performance
    color: fbca04
  - name: ready
    color: ededed
  - name: regression
    color: e11d21
  - name: release note
    color: BFD4F2
  - name: research
    color: FFFF00
  - name: review carefully!
    color: ededed
  - name: security
    color: 02d7e1
  - name: technical debt
    color: FFFF00
  - name: tested
    color: FBCA04
  - name: won't fix
    color: ffffff
  - name: admin docs
    color: 0847A5
  - name: APIs
    color: FCDCC7
  - name: desktop client docs
    color: 7108D3
  - name: iOS client docs
    color: 530D89
  - name: Android client docs
    color: 530D89
  - name: developer docs
    color: B7D653
  - name: enterprise docs
    color: B7D653
  - name: user docs
    color: B7D653
  - name: duplicate
    color: CFD3D7
  - name: invalid
    color: E4E669
    description: This doesn't seem right
  - name: analytics
    color: B522CC
  - name: LDAP
    color: 6341B5
    description: Relates to LDAP interaction and integration with ownCloud.
  - name: logging
    color: 4EE8D1
  - name: appliance
    color: 9B99DD
  - name: backport
    color: 9551B5
  - name: blocked
    color: 4938AA
  - name: command-line
    color: 3F1E99
    description: Documentation relates to the command-line.
  - name: deprecation
    color: B7DEF4
    description: Involves removing existing content that is no longer valid.
  - name: help wanted
    color: 008672
    description: Extra attention is needed.
  - name: good first issue
    color: CCCC33
    description: Good task for newcomers.
  - name: outdated documentation
    color: B1DEED
    description: Update or remove outdated documentation.
  - name: question
    color: D876E3
    description: Further information has been requested.
  - name: training
    color: 6A737D
    description: Training and educational resources for contributors.
  - name: installation and configuration
    color: 390B93
  - name: Marketplace
    color: 6341B5
    description: Anything related to the ownCloud Marketplace.
  - name: no backport
    color: 8C043A
  - name: occ
    color: 59039B
  - name: seo
    color: 59039B
  - name: deployment
    color: E89D53
    description: Tasks relating to deploying the documentation.
  - name: database
    color: 9C1EFC
    description: Anything related to databases.
  - name: shares
    color: B87FF4
  - name: waiting on PR merge
  - name: occ
    color: E697F4
    description: Anything related to the occ command.
