= Search & Full Text Search
:toc: right

== Introduction

ownCloud comes with a regular search function allowing you to find files by their file name or parts of it. Click on the the magnifier icon in the upper right-hand corner of the web interface. In addition, the Full Text Search app can be enabled. This is something the system administrator needs to take care of. For more information on deploying it, refer to the respective section in the xref:admin_manual:configuration/search/index.adoc[Admin Manual].

== Regular Search

The regular search function in the ownCloud web interface offers a simple search for elements of file names. This also works when you only enter "pain" but meant to look for Spain. However, you also get results for pain or painful. If you start at the top level "All files", you will also see results in subfolders. If you change into a directory, the search starts in this folder, displays the results, then continues to search in all other folders.

A click on one of the results takes you either to the location of the file, if you are not already in that folder, or the item is opened.

The search is not case-sensitive, so capital letters are treated the same as lower case characters. You can type Spain or spain and will get the same results. When you start typing, the search also starts.

== Full Text Search App

Things get tricky when you don't remember what the file you're looking for was called and guess work doesn't help. A key word search within text documents is only possible if the Full Text Search app is installed. Contact your admin if you need it and it's not installed. With this app enabled, you can search within files of the most common formats. Like with the regular search, you can enter only the first part of a string and it matches all occurances of words starting with the search string.

If you are looking for all terms containing a specific string like in the above example "pain", wildcards can be used, e.g. an asterisk: *ain gives you results like braine, pain, Spain and painful. Using a question mark instead of the asterisk limits the preceeding characters to exactly one. In this example, only pain and painful would show up if you entered the search string "?ain".

TIP: Using the asterisk within a word will ignore everything that follows after the asterisk. A trailing asterisk is always assumed in the search.
