= Search & Full Text Search
:toc: right
:elastic-query-url: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

== Introduction

ownCloud comes with a regular search function allowing you to find files by their file name or parts of it. Click on the the magnifier icon in the upper right-hand corner of the web interface. In addition, the Full Text Search app can be enabled. This is something the system administrator needs to take care of. For more information on deploying it, see xref:admin_manual:configuration/search/index.adoc

== Regular Search

The regular search function in the ownCloud web interface offers a simple search for elements of file names. This also works when you only enter "pain" but meant to look for spain. However, you may also get results for pain or painful. If you start at the top level "All files", you will also see results in subfolders. If you change into a directory, the search starts in this folder, displays the results, then continues to search in all other folders.

A click on one of the results takes you either to the location of the file, if you are not already in that folder, or the item is opened.

The search is not case sensitive, so capital letters are treated the same as lower case characters. You can type Spain or spain and will get the same results. When you start typing, the search also starts.

== Full Text Search App

Things get tricky when you don't remember what the file you're looking for was called and guess work doesn't help. A key word search within text documents is only possible if the Full Text Search app is installed. Contact your admin if you need it and it's not installed. With this app enabled, you can search in files of the most common formats.

Version 1.0.0 of the Full Text Search app works like the regular search. You start typing and the search starts even on incomplete words or partials.

With version 2 of the Full Text Search app, this behavior changes. You can no longer simply enter "pain" and expect to see all results containing this string. Instead you need to add an asterisk * to search for all instances starting with "pain": pain*. In the highly unlikely case you actually do want to get results for pain and Spain, add an asterisk as prefix *pain. To get results for pain, Spain and painful, use *pain*.

The asterisk works as a wildcard. Any string of characters can preceed or follow the characters you enter. More complex searches are now possible to help you define more precisely what to look for. Check out the instructions on how to use the {elastic-query-url}[simple query string query] by Elasticsearch for more complex search options.

NOTE: While the regular search is not case sensitive, the Full Text Search app is. A search for "spain" won't display hits for "Spain".
