= Search & Full Text Search
:toc: right

== Introduction

ownCloud comes with a regular search function allowing you to find files by their file name or parts of it. Click on the the magnifier icon in the upper right-hand corner of the web interface. In addition, the Full Text Search app can be enabled. This is something the system administrator needs to take care of. For more information on deploying it, see xref:admin_manual:configuration/search/index.adoc

== Regular Search

The regular search function in the ownCloud web interface offers a simple search for elements of file names. This also works when you only enter "pain" but meant to look for spain. However, you may also get results for pain or painful, Spaniard and spaniels. If you start at the top level "All files", you will also see results in subfolders. If you change into a directory, the search starts with the respective folder, shows you the results, then continues the search in all other folders and presents the results under the heading xx search results in other folders. 

A click on one of the results takes you either to the location of the file, if you are not already in that folder or, or a picture simply is displayed. With text files you're asked in which application to open it, as usual.

The search is not case sensitive, so capital letters are treated the same as lower case characters. You can type Spain or spain and will get the same results. When you start typing, the search also starts.

== Full Text Search App

Things get tricky when you don't remember what the file you're looking for was called and guess work doesn't help. A key word search within text documents is only possible if the Full Text Search app is installed. Contact your admin if you need it and it's not installed. With this app present, you can search in files of the most common types, e.g. PPT, PDF and XLS.

Version 1.0.0 of the Full Text Search app works like the regular search. You start typing and the search starts even on incomplete words.
