workspace:
  base: /drone
  path: src

branches:
  - master

clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  build-pdfs:
    image: toolhippie/asciidoctor:latest
    pull: true
    commands:
      - make pdf

  build-docs:
    image: antora/antora:1.0.1
    pull: true
    commands:
      - antora generate --cache-dir cache/ --redirect-facility static site.yml

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - cache
    when:
      local: false
      event: [ push ]

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]

  publish-netlify:
    image: lucap/drone-netlify:latest
    pull: true
    secrets: [ netlify_token ]
    site_id: 78b01cd5-9958-4423-af3d-6040d873132f
    path: public/
    when:
      event: [ push ]

  notify-slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: documentation
    when:
      local: false
      event: [ push ]
      status: [ success, failure ]
