workspace:
  base: /drone
  path: src

branches:
  - master

clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  docs-deps:
    image: owncloudci/nodejs:11
    pull: true
    commands:
      - yarn install

  docs-validate:
    image: owncloudci/nodejs:11
    pull: true
    commands:
      - yarn validate --pull

  docs-build:
    image: owncloudci/nodejs:11
    pull: true
    secrets: [ algolia_search_key, algolia_write_key, algolia_app_id, algolia_index_name ]
    commands:
      - yarn antora --pull

  docs-pdf:
    image: owncloudci/asciidoctor:latest
    pull: true
    commands:
      - make pdf

  docs-artifacts:
    image: owncloud/ubuntu:latest
    pull: true
    commands:
      - tree public/

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - cache
      - node_modules
    when:
      local: false
      event: [ push ]

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]

  upload-pdf:
    image: plugins/s3-sync:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: uploads
    endpoint: https://doc.owncloud.com
    path_style: true
    source: build/
    target: /deploy
    delete: false
    when:
      local: false
      event: [ push ]

  upload-html:
    image: plugins/s3-sync:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: uploads
    endpoint: https://doc.owncloud.com
    path_style: true
    source: public/
    target: /deploy
    delete: false
    when:
      local: false
      event: [ push ]

  notify-slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: documentation
    when:
      local: false
      event: [ push ]
      status: [ failure, changed ]
