workspace:
  base: /drone
  path: src

branches:
  - master

clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  cache-restore:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    restore: true
    when:
      local: false

  install-deps:
    image: owncloudci/antora:latest
    pull: true
    commands:
      - yarn install

  validate-adoc:
    image: owncloudci/antora:latest
    pull: true
    commands:
      - make validate

  build-html:
    image: owncloudci/antora:latest
    pull: true
    commands:
      - make html

  build-pdfs:
    image: owncloudci/asciidoctor:latest
    pull: true
    commands:
      - make pdf

  list-artifact:
    image: owncloudci/asciidoctor:latest
    pull: true
    commands:
      - tree public/

  cache-rebuild:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - cache
    when:
      local: false
      event: [ push ]

  cache-flush:
    image: plugins/s3-cache:1
    pull: true
    secrets: [ cache_s3_endpoint, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14
    when:
      local: false
      event: [ push ]

  upload-artifact:
    image: plugins/s3-sync:1
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    bucket: uploads
    endpoint: https://doc.owncloud.com
    path_style: true
    source: public/
    target: /deploy
    delete: false
    when:
      local: false
      event: [ push ]

  notify-slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: documentation
    when:
      local: false
      event: [ push ]
      status: [ success, failure ]
