[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self'"
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000; includeSubdomains; preload"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "SAMEORIGIN"
        X-XSS-Protection = "1; mode=block"
