[[redirects]]
	from = "/server/latest/admin_manual"
	to = "/server/administration_manual/"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/installation/"
	to = "/server/administration_manual/installation/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/installation/source_installation.html"
	to = "/server/administration_manual/installation/manual_installation.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/installation/docker/"
	to = "/server/administration_manual/installation/docker/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/installation/letsencrypt/"
	to = "/server/administration_manual/installation/letsencrypt/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/upgrading/"
	to = "/server/administration_manual/upgrading/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/configuration/"
	to = "/server/administration_manual/configuration/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/configuration/database"
	to = "/server/administration_manual/configuration/database/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/configuration/files"
	to = "/server/administration_manual/configuration/files/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/configuration/mimetypes"
	to = "/server/administration_manual/configuration/mimetypes/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/configuration/server"
	to = "/server/administration_manual/configuration/server/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/configuration/user"
	to = "/server/administration_manual/configuration/user/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/maintenance/"
	to = "/server/administration_manual/maintenance/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/admin_manual/issues/"
	to = "/server/administration_manual/issues/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/user_manual/"
	to = "/server/user_manual/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/user_manual/files/"
	to = "/server/user_manual/files/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/user_manual/pim/"
	to = "/server/user_manual/pim/index.html"
	status = "301"

[[redirects]]
	from = "/server/latest/user_manual/files/troubleshooting.html"
	to = "/server/user_manual/troubleshooting.html"
	status = "301"

[[redirects]]
	from = "/server/latest/user_manual/pim/troubleshooting.html"
	to = "/server/user_manual/troubleshooting.html"
	status = "301"

[[redirects]]
	from = "/server/latest/developer_manual/commun/"
	to = "/server/developer_manual/commun/help_and_communication.html"
	status = "301"

[[redirects]]
	from = "/server/latest/developer_manual/app/"
	to = "/server/developer_manual/app/introduction.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/app/fundamentals/"
	to = "/server/developer_manual/app/fundamentals/index.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/app/advanced/"
	to = "/server/developer_manual/app/advanced/index.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/app/tutorial/"
	to = "/server/developer_manual/app/tutorial/index.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/core/"
	to = "/server/developer_manual/core/index.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/app/general/"
	to = "/server/developer_manual/general/index.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/mobile_development/"
	to = "/server/developer_manual/mobile_development/index.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/mobile_development/android_library/"
	to = "/server/developer_manual/mobile_development/android_library/index.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/mobile_development/ios_library/"
	to = "/server/developer_manual/mobile_development/ios_library/index.html"
	status = "301"

[[redirects]]
	from = "/server/developer_manual/bugtracker/"
	to = "/server/developer_manual/bugtracker/index.html"
	status = "301"

[[redirects]]
	from = "/android_app/"
	to = "/android_app/android_app_app.html"
	status = "301"

[[redirects]]
	from = "/ios/"
	to = "/ios/ios_app.html"
	status = "301"

[[redirects]]
	from = "/desktop/latest/"
	to = "/desktop/introduction.html"
	status = "301"

[[redirects]]
	from = "/desktop/latest/advanced_usage.html"
	to = "/desktop/advanced_usage/options.html"
	status = "301"

[[redirects]]
	from = "/desktop/latest/autoupdate.html"
	to = "/desktop/automatic_updater.html"
	status = "301"
