site:
  title: Documentation for ownCloud (A Kiteworks Company)
  url: https://doc.owncloud.com
  # the site's landing page resides in the docs_main repository/component
  # but it MUST be named ROOT to get a component/version less than the  landing page
  # this now makes the landing page reside in the url given above WITHOUT getting redirected
  # see: https://docs.antora.org/antora/latest/page/start-page/
  # see: https://docs.antora.org/antora/latest/component-name-key/#root-component
  start_page: ROOT::index.adoc

# define all content sources
# note that branches must already exist if changed here
content:
  sources:
  - url: https://github.com/owncloud/docs-main.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-server.git
    branches:
    - master
    - '10.16'
    - '10.15'
  - url: https://github.com/owncloud/docs-ocis.git
    branches:
    - master
    - '7.3'
    - '7.2'
  - url: https://github.com/owncloud/docs-webui.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-client-desktop.git
    branches:
    - master
    - '6.0'
    - '5.3'
  - url: https://github.com/owncloud/docs-client-ios-app.git
    branches:
    - master
    - '12.6'
    - '12.5'
  - url: https://github.com/owncloud/docs-client-android.git
    branches:
    - master
    - '4.7'
    - '4.6'

ui:
  # supplemental_files: supplemental
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   global attributes loaded via antora extension
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki # integrated via npm

antora:
  extensions:
    - ./ext-antora/generate-index.js
    - ./ext-antora/comp-version.js
    - require: ./ext-antora/load-global-site-attributes.js
      #attributefile: https://raw.githubusercontent.com/owncloud/docs/refs/heads/master/global-attributes.yml
      attributefile: ./global-attributes.yml
      enabled: true
    # for testing only, prints out attributes used
    # use only one or the other, output can be big
    #- ./ext-antora/attributes-used-in-site-yml.js
    #- ./ext-antora/attributes-used-in-antora-yml.js
