site:
  title: ownCloud Documentation
  url: https://doc.owncloud.com

content:
  sources:
  - url: .
    branches:
    - HEAD
  - url: https://github.com/owncloud/docs.git
    branches:
    - '10.9'
    - '10.8'
  - url: https://github.com/owncloud/docs-client-desktop.git
    branches:
    - master
    - '2.10'
    - '2.9'
  - url: https://github.com/owncloud/docs-client-ios-app.git
    branches:
    - master
    - '11.8'
    - '11.7'
  - url: https://github.com/owncloud/docs-client-android.git
    branches:
    - master
    - '2.19'
    - '2.18'
  - url: https://github.com/owncloud/docs-client-branding.git
    branches:
    - master

ui:
  supplemental_files: overlay
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
    branch-specific-variables: 'see antora.yml'
    idprefix: ''
    idseparator: '-'
    experimental: ''
    latest-server-version: '10.9'
    latest-server-download-version: '10.9.1'
    previous-server-version: '10.8'
    current-server-version: '10.9'
    latest-desktop-version: '2.10'
    previous-desktop-version: '2.9'
    latest-ios-version: '11.8'
    previous-ios-version: '11.7'
    latest-android-version: '2.19'
    previous-android-version: '2.18'
    latest-branded-version: 'next'
    previous-branded-version: 'next'
    docs-base-url: 'https://doc.owncloud.com'
    oc-contact-url: 'https://owncloud.com/contact/'
    oc-help-url: 'https://owncloud.com/docs-guides/'
    oc-marketplace-url: 'https://marketplace.owncloud.com'
    oc-changelog-url: 'https://owncloud.com/changelog/server/'
    oc-central-url: 'https://central.owncloud.org'
    oc-support-url: 'https://owncloud.com/support'
    oc-install-package-url: 'https://software.opensuse.org//download.html?project=isv%3AownCloud%3Aserver%3A10&package=owncloud-complete-files'
    oc-examples-server-url: 'https://owncloud.install.com/owncloud'
    oc-examples-server-ip: '127.0.0.1'
    oc-examples-username: 'username'
    oc-examples-password: 'password'
    oc-complete-name: 'owncloud-complete-20220112'
    occ-command-example-prefix: 'sudo -u www-data php occ'
    occ-command-example-prefix-no-sudo: 'php occ'
    page-component-build-list: 'docs, server, ocis, user, desktop, ios-app, android'
    php-net-url: 'https://www.php.net'
    php-supported-versions-url: 'https://www.php.net/supported-versions.php'
    http-status-codes-base-url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Status'
    std-port-http: '8080'
    std-port-memcache: '11211'
    std-port-mysql: '3306'
    std-port-redis: '6379'
  extensions:
    - ./lib/extensions/tabs.js
    - ./lib/extensions/remote-include-processor.js
    - ./node_modules/asciidoctor-kroki/src/asciidoctor-kroki.js

