site:
  title: ownCloud Documentation
  url: https://owncloud-docs.netlify.com/ 

content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/owncloud/android.git
    branches:
    - master-antora
    start_path: docs/
  - url: https://github.com/owncloud/ios.git
    branches:
    - master-antora
    start_path: docs/
  - url: https://github.com/owncloud/client.git
    branches:
    - master-antora
    start_path: docs/

ui:
  bundle:
    url: ui-bundle.zip
  output_dir: assets

output:
  clean: true
  dir: public
