site:
  title: ownCloud Documentation
  url: https://doc.owncloud.com

content:
  sources:
  - url: .
    branches:
    - HEAD
  - url: https://github.com/owncloud/docs.git
    branches:
    - '10.6'
    - '10.5'
  - url: https://github.com/owncloud/android.git
    branches:
    - master
    start_path: docs/
  - url: https://github.com/owncloud/ios-app.git
    branches:
    - master
    start_path: docs/
  - url: https://github.com/owncloud/ios.git
    branches:
    - master
    start_path: docs/
  - url: https://github.com/owncloud/client.git
    branches:
    - master
    - '2.7'
    - '2.6'
    start_path: docs/
  - url: https://github.com/owncloud/branded_clients.git
    branches:
    - master

ui:
  supplemental_files: overlay
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
    experimental: ''
    latest-version: 10.6
    latest-download-version: 10.6.0
    previous-version: 10.5
    current-version: 10.6
    page-version: 10.6
    oc-contact-url: https://owncloud.com/contact/
    oc-help-url: https://owncloud.com/docs-guides/
    oc-examples-server-url: 'https://owncloud.install.com/owncloud'
    oc-examples-server-ip: '127.0.0.1'
    oc-examples-username: username
    oc-examples-password: password
    oc-marketplace-url: https://marketplace.owncloud.com
    occ-command-example-prefix: 'sudo -u www-data php occ'
    occ-command-example-prefix-no-sudo: 'php occ'
    owncloud-changelog-url: https://owncloud.org/changelog/server/
    php-supported-versions-url: https://secure.php.net/supported-versions.php
    http-status-codes-base-url: https://developer.mozilla.org/en-US/docs/Web/Status
    minimum-php-version: 7.2
    minimum-php-version-short-code: 72
    recommended-php-version: 7.4
    recommended-php-version-short-code: 74
    std-port-http: 8080
    std-port-memcache: 11211
    std-port-mysql: 3306
    std-port-redis: 6379
    supported-php-versions: '7.2, 7.3, and 7.4'
  extensions:
    - ./lib/extensions/tabs.js
    - ./node_modules/asciidoctor-kroki/src/asciidoctor-kroki.js
