site:
  title: Documentation for ownCloud (A Kiteworks Company)
  url: https://doc.owncloud.com
  # the site's landing page resides in the docs_main repository/component
  # but it MUST be named ROOT to get a component/version less than the landing page
  # this now makes the landing page reside in the url given above WITHOUT getting redirected
  # see: https://docs.antora.org/antora/latest/page/start-page/
  # see: https://docs.antora.org/antora/latest/component-name-key/#root-component
  start_page: ROOT::index.adoc

# define all content sources
# note that branches must already exist if changed here
content:
  sources:
  - url: https://github.com/owncloud/docs-main.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-server.git
    branches:
    - master
    - '10.16'
    - '10.15'
  - url: https://github.com/owncloud/docs-ocis.git
    branches:
    - master
    - '8.0'
    - '7.3'
  - url: https://github.com/owncloud/docs-webui.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-client-desktop.git
    branches:
    - master
    - '6.0'
    - '5.3'
  - url: https://github.com/owncloud/docs-client-ios-app.git
    branches:
    - master
    - '12.6'
    - '12.5'
  - url: https://github.com/owncloud/docs-client-android.git
    branches:
    - master
    - '4.7'
    - '4.6'

urls:
  # https://docs.antora.org/antora/latest/playbook/urls-redirect-facility/
  redirect_facility: static
  # see https://docs.antora.org/antora/latest/playbook/urls-latest-prerelease-version-segment/
  # for multi version components, the prerelease key defines if the latest segment is shown in the URL or only redirected when entered
  latest_version_segment: latest
  # latest_prerelease_version_segment: next  # do not enable, we are not using this. the upcoming release version is unknown
  latest_version_segment_strategy: replace   # default, do not change. GH Pages currently do not support 302 as gitlab does

runtime:
  fetch: true
  cache_dir: ./.cache

output:
  clean: true
  dir: public

ui:
  # supplemental_files: supplemental
  output_dir: assets
  bundle:
    snapshot: true
    url: https://github.com/owncloud/docs-ui/releases/download/latest/ui-bundle.zip

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   global attributes loaded via antora extension
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki # integrated via npm

antora:
  extensions:
    - ./ext-antora/generate-index.js
    - ./ext-antora/comp-version.js
    - require: ./ext-antora/load-global-site-attributes.js
      #attributefile: https://raw.githubusercontent.com/owncloud/docs/refs/heads/master/global-attributes.yml
      attributefile: ./global-attributes.yml
      enabled: true
    # for testing only, prints out attributes used
    # use only one or the other, output can be big
    #- ./ext-antora/attributes-used-in-site-yml.js
    #- ./ext-antora/attributes-used-in-antora-yml.js
