site:
  title: ownCloud Documentation
  url: https://doc.owncloud.com
  start_page: docs_main::index.adoc

content:
  sources:
  - url: https://github.com/owncloud/docs-main.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-server.git
    branches:
    - master
    - '10.13'
    - '10.12'
  - url: https://github.com/owncloud/docs-ocis.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-webui.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-client-desktop.git
    branches:
    - master
    - '5.2'
    - '5.1'
  - url: https://github.com/owncloud/docs-client-ios-app.git
    branches:
    - master
    - '12.0'
    - '11.11'
  - url: https://github.com/owncloud/docs-client-android.git
    branches:
    - master
    - '4.1'
    - '4.0'
  - url: https://github.com/owncloud/docs-client-branding.git
    branches:
    - master

ui:
  supplemental_files: overlay
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   build relevant
    # asciidoctor prefix for section IDs
    idprefix: ''
    idseparator: '-'
    # Antora User Interface Macros (btn, menu)
    experimental: true
    # Antora pagination (prev page, next page)
    page-pagination: true
    # Custom attribute page-component-build-list
    # Only embed named opengraph images in docs-ui via src/partials/head-meta-opengraph.hbs sourced from docs/overlay
    page-component-build-list: 'android, branding, desktop, docs, ios-app, ocis, server, user, webui'
#   common
    docs-base-url: 'https://doc.owncloud.com'
    oc-complete-base-url: 'https://download.owncloud.com/server/stable'
    oc-contact-url: 'https://owncloud.com/contact/'
    oc-help-url: 'https://owncloud.com/docs-guides/'
    oc-marketplace-url: 'https://marketplace.owncloud.com'
    oc-central-url: 'https://central.owncloud.org'
    oc-support-url: 'https://owncloud.com/support'
#   docs
    latest-docs-version: 'next'
    previous-docs-version: 'next'
#   server
    latest-server-version: '10.13'
    latest-server-download-version: '10.13.4'
    previous-server-version: '10.12'
    current-server-version: '10.13'
    oc-changelog-url: 'https://owncloud.com/changelog/server/'
    oc-install-package-url: 'https://download.owncloud.com/server/stable/?sort=time&order=asc'
    oc-examples-server-url: 'https://owncloud.install.com/owncloud'
    oc-examples-server-ip: '127.0.0.1'
    oc-examples-username: 'username'
    oc-examples-password: 'password'
    oc-complete-name: 'owncloud-complete-latest'
    occ-command-example-prefix: 'sudo -u www-data ./occ'
    occ-command-example-prefix-no-sudo: 'occ'
    php-net-url: 'https://www.php.net'
    php-supported-versions-url: 'https://www.php.net/supported-versions.php'
    http-status-codes-base-url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Status'
    std-port-http: '8080'
    std-port-memcache: '11211'
    std-port-mysql: '3306'
    std-port-redis: '6379'
#   ocis
    latest-ocis-version: 'next'
    previous-ocis-version: 'next'
    # these versions are just for printing like in releases but not used for referencing
    ocis-actual-version: '4.0.4'
    ocis-former-version: '3.0.0'
    ocis-compiled: '2023-10-06 00:00:00 +0000 UTC'
    ocis-downloadpage-url: 'https://download.owncloud.com/ocis/ocis/stable/'
#   webui
    latest-webui-version: 'next'
    previous-webui-version: 'next'
#   desktop
    latest-desktop-version: '5.2'
    previous-desktop-version: '5.1'
#   ios-app
    latest-ios-version: '12.0'
    previous-ios-version: '11.11'
#   android
    latest-android-version: '4.1'
    previous-android-version: '4.0'
#   branded
    latest-branded-version: 'next'
    previous-branded-version: 'next'
  extensions:
    - ./lib/extensions/tabs.js
    - ./lib/extensions/remote-include-processor.js
    - ./node_modules/asciidoctor-kroki/src/asciidoctor-kroki.js


