site:
  title: ownCloud Documentation
  url: https://doc.owncloud.com

content:
  sources:
  - url: .
    branches:
    - HEAD
  - url: https://github.com/owncloud/docs.git
    branches:
    - '10.1'
    - '10.0'
  - url: https://github.com/owncloud/android.git
    branches:
    - master
    start_path: docs/
  - url: https://github.com/owncloud/ios.git
    branches:
    - master
    start_path: docs/
  - url: https://github.com/owncloud/client.git
    branches:
    - master
    - '2.6'
    start_path: docs/
  - url: https://github.com/owncloud/branded_clients.git
    branches:
    - master

ui:
  supplemental_files: overlay
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
    oc-contact-url: https://owncloud.com/contact/
    php-supported-versions-url: https://secure.php.net/supported-versions.php
    recommended-php-version: 7.2
