site:
  title: ownCloud Documentation
  url: https://doc.owncloud.com

content:
  sources:
  - url: .
    branches:
    - HEAD
    - '10.1'
    - '10.0'
  - url: https://github.com/owncloud/android.git
    branches:
    - master
    start_path: docs/
  - url: https://github.com/owncloud/ios.git
    branches:
    - master
    start_path: docs/
  - url: https://github.com/owncloud/client.git
    branches:
    - master
    start_path: docs/
  - url: https://github.com/owncloud/branded_clients.git
    branches:
    - master

ui:
  output_dir: assets
  bundle:
    url: https://minio.owncloud.com/documentation/ui-bundle.zip
    snapshot: true

output:
  clean: true
  dir: public

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
