= Manual ownCloud Upgrade
:toc: right

== Introduction

This section describes how to manually upgrade your ownCloud installation.

== Enable Maintenance Mode

Put your server in xref:configuration/server/occ_command.adoc#maintenance-commands[maintenance mode] and disable xref:configuration/server/background_jobs_configuration.adoc#cron-jobs[Cron jobs].
Doing so prevents new logins, locks the sessions of logged-in users, and displays a status screen so that users know what is happening.

There are two ways to enable maintenance mode.
The preferred method is to use xref:configuration/server/occ_command#maintenance-commands[the occ command] — which you must run as your webserver user.
The other way is by entering your `config.php` file and changing `'maintenance' => false,` to `'maintenance' => true,`.

[source,console]
----
# Enable maintenance mode using the occ command.
sudo -u www-data php occ maintenance:mode --on
----

In clustered environment please check that all nodes are in maintenance mode.

[[stop-the-webserver]]
== Stop the Webserver

With those steps completed, stop your webserver.

[source,console]
----
sudo service apache2 stop
----

[[backup-your-existing-installation]]
== Backup Your Existing Installation

First, xref:maintenance/backup.adoc[backup] the following items:

* The ownCloud server data directory
* The `config.php` file
* All 3rd party apps
* The ownCloud server database

[source,console]
----
# This example assumes Ubuntu Linux and MariaDB
mkdir /opt/backup/
cp -rv /var/www/owncloud /opt/backup/owncloud
mysqldump -u<username> -p<password> <databasename> > <ownCloud-Version-Dump.sql>
----

== Review Third-Party Apps

Review any installed third-party apps for compatibility with the new ownCloud release.
Ensure that they are all disabled before beginning the upgrade.

. Disable via Command Line
+
[source,console]
----
# This command lists all apps by <app-id> and app version
sudo -u www-data php occ app:list

# This command disables the app with the given <app-id>
sudo -u www-data php occ app:disable <app-id>
----
. Disable via Browser +
Goto menu:Settings[Admin > Apps] and disable all third-party apps

== Download the Latest Installation

Download the latest ownCloud server release from https://owncloud.org/install[owncloud.org/install] into an empty directory *outside* of your current installation.

NOTE: Enterprise users must download their new ownCloud archives from their accounts on
https://customer.owncloud.com/owncloud/.

== Upgrade

NOTE: For this description we assume that your existing ownCloud installation is located in the
default location: `/var/www/owncloud`. The path might differ, depending on your installation.


=== Extract the New Source

Rename your current ownCloud directory, for example, from `owncloud` to `owncloud-old`.
Extract the unpacked ownCloud server directory and its contents to the location of your original ownCloud installation.

[source,console]
----
# Assumes that the new release was unpacked into /tmp/
sudo mv /tmp/owncloud /var/www/
----

With the new source files now in place of the old ones, next copy the `config.php` file from your old ownCloud directory to your new ownCloud directory. :

[source,console]
----
sudo cp /var/www/owncloud-old/config/config.php /var/www/owncloud/config/config.php
----

* If you keep your `data/` directory _inside_ your `owncloud/` directory, copy it from your old version of ownCloud to your new version.
* If you keep it _outside_ of your `owncloud/` directory, then you don’t have to do anything with it, because its location is configured in your original `config.php`, and none of the upgrade steps touch it.

=== Market and Marketplace App Upgrades

Before getting too far into the upgrade process, please be aware of how the Market app and its configuration options affect the upgrade process.

* The Market app is not upgraded if it is either disabled because
** in config.php `appstoreenabled` is set to `false`)
** or it is not available.
* If `upgrade.automatic-app-update` is set to `false` apps installed from the Marketplace are not automatically upgraded.

In addition to these two points, if there are installed apps (whether compatible or incompatible with the next version, or missing source code) and the Market app is enabled but there is no available internet connection, these apps will need to be manually updated once the upgrade is finished.

=== Copy Old Apps
If you are using third party or enterprise applications, look in your new `/var/www/owncloud/apps/` directory to see if they are present. If not, copy them from your old `apps/` directory to your new one.

=== Setting the Ownership for Upgrading
To finalize the preparation of the upgrade, you need to set the correct ownersip of the new ownCloud files and folders.

[source,console]
----
sudo chown -R www-data:www-data /var/www/owncloud
----

=== Start the Upgrade

With the apps disabled and owncloud in maintenance mode, start xref:configuration/server/occ_command.adoc#command-line-upgrade[the upgrade process] from the command line:

[source,console]
----
# Here is an example on Ubuntu Linux. Execute this within the ownCloud root folder.
sudo -u www-data php occ upgrade
----

The upgrade operation can take anywhere from a few minutes to a few hours, depending on the size of your installation.
When it is finished you will see either a success message, or an error message which indicates why the process did not complete successfully.

=== Reset Strong Permissions and Ownership

To re-harden security, we recommend setting the permissions on your ownCloud directories as strictly as possible.
To get/set the correct ownership and permissions, see xref:installation/manual_installation.adoc#set-strong-directory-permissions[strong permissions].
The script provided will do the job for you.

=== Disable Maintenance Mode

Assuming your upgrade succeeded, next disable maintenance mode.

[source,console]
----
# Disable maintenance mode using the occ command.
sudo -u www-data php occ maintenance:mode --off
----

=== Restart the Webserver

With all that done, restart your web server:

[source,console]
----
sudo service apache2 start
----

=== Finalize the Installation

With maintenance mode disabled, login and:

* Check that the version number reflects the new installation. +
It can be reviewed at the bottom of menu:Settings[Admin > General].
* Check that your other settings are correct.
* Go to the menu:Settings[Admin > Apps] page and review the core apps to make sure the right ones are enabled.
* After the upgrade is complete, re-enable any third-party apps that are compatible with the new release.
+
. Enable via Command Line
+
[source,console]
----
# This command enables the app with the given <app-id>
sudo -u www-data php occ app:enable <app-id>
----
. Enable via Browser +
Goto menu:Settings[Admin > Apps > "Show disabled apps"] and enable all compatible third-party apps
+
WARNING: Install or enable unsupported apps at your own risk.

== Reverse Upgrade

If you need to reverse your upgrade, see the xref:maintenance/restore.adoc[Restoring owncloud] documentation.

== Troubleshooting

When upgrading ownCloud and you are running MySQL or MariaDB with binary logging enabled, your upgrade may fail with these errors in your MySQL/MariaDB log:

....
An unhandled exception has been thrown:
exception 'PDOException' with the message 'SQLSTATE[HY000]: General error: 1665
Cannot execute statement: impossible to write to binary log since
BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.'
....

Please refer to xref:configuration/database/linux_database_configuration.adoc#mysql-mariadb-with-binary-logging-enabled[MySQL / MariaDB with Binary Logging Enabled] on how to correctly configure your environment.

Occasionally, _files do not show up after an upgrade_. A rescan of the files can help:

[source,console]
----
sudo -u www-data php occ files:scan --all
----

See https://owncloud.org/support[the owncloud.org support page] for further resources for both home and enterprise users.

Sometimes, ownCloud can get _stuck in a upgrade_.
This is usually due to the process taking too long and encountering a PHP time-out.
Stop the upgrade process this way:

[source,console]
----
sudo -u www-data php occ maintenance:mode --off
----

Then start the manual process:

[source,console]
----
sudo -u www-data php occ upgrade
----

If this does not work properly, try the repair function:

[source,console]
----
sudo -u www-data php occ maintenance:repair
----
