= Restoring ownCloud
:toc: right

== Introduction

When you install ownCloud from packages, follow these steps to restore
your ownCloud installation. Start with a fresh ownCloud package
installation in a new, empty directory. Then restore these items from
your xref:maintenance/backup.adoc[Backup]:

1.  Your `config/` directory.
2.  Your `data/` directory.
3.  Your ownCloud database.
4.  Your custom theme files, if you have any. (See xref:developer_manual:core/theming.adoc[Theming ownCloud])

If you install ownCloud from the source tarballs, you may safely
restore your entire ownCloud installation from backup, with the
exception of your ownCloud database. Databases cannot be copied, instead you
must use the database tools to make a correct restoration.

After you have completed the restoration, see xref:installation/manual_installation.adoc#set-strong-directory-permissions[Set Strong Directory Permissions].

== Restore Directories

Simply copy your `config/` and `data/` folders to your ownCloud
environment, for example by running the following command from the backup directory:

[source,console]
----
sudo rsync -Aax config data /var/www/owncloud/
----

There are many ways to restore normal files from backup. Use whatever method you are accustomed to.

== Restore Database

NOTE: This guide assumes that your previous backup is called `owncloud-dbbackup.bak`.

=== MySQL/MariaDB

MySQL or MariaDB are the recommended database engines. To restore MySQL/MariaDB:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} maintenance:mode --on
sudo mysql -h [server] -u [username] -p[password] [db_name] < owncloud-dbbackup.bak
{occ-command-example-prefix} maintenance:data-fingerprint
{occ-command-example-prefix} maintenance:mode --off
----

=== SQLite

[source,console]
----
sudo rm data/owncloud.db
sudo sqlite3 data/owncloud.db < owncloud-dbbackup.bak
----

=== PostgreSQL

[source,console]
----
PGPASSWORD="password" pg_restore -c -d owncloud -h [server] -U [username] owncloud-dbbackup.bak
----
