= How to Upgrade Your ownCloud Server
:toc: right

== Introduction

We recommend that you keep your ownCloud server up to date. When an
update is available for your ownCloud server, you will see a
notification at the top of your ownCloud Web interface. When you click
the btn:[notification], it will bring you here.

Before beginning an upgrade, please keep the following points in mind:

* Review xref:release_notes.adoc[the release notes] for important information
about the needed migration steps during that upgrade to help ensure a
smooth upgrade process.
* Check ownCloud's xref:installation/manual_installation#requirements[mandatory requirements] (such as PHP versions and extensions), which can change from one version to the next.
  Ensure that you review them and update your server(s), if required, before upgrading ownCloud.
* Upgrading is disruptive, as your ownCloud server will be put into
xref:configuration/server/occ_command.adoc#maintenance-commands[maintenance mode].
* Large installations may take several hours to complete the upgrade.
* Review any installed xref:maintenance/manual_upgrade.adoc#review-third-party-apps[third-party apps] for compatibility with the new ownCloud release.
* Downgrading *is not supported* as it risks corrupting your data. If
you want to revert to an older ownCloud version, make a new, fresh
installation and then restore your data from backup. Before doing this,
file a support ticket (if you have paid support) or ask for help in the
ownCloud forums to resolve your issue without downgrading.

include::{partialsdir}maintenance/major_release_note.adoc[]

== Prerequisites

We strongly recommend that you always maintain xref:maintenance/backup.adoc[regular backups]
as well as make a fresh backup before every upgrade. We also recommend
that you review any installed xref:maintenance/manual_upgrade.adoc#review-third-party-apps[third-party apps] for compatibility with
the new ownCloud release. Ensure that they are all disabled before
beginning the upgrade. After the upgrade is complete re-enable any which
are compatible with the new release.

CAUTION: Unsupported apps may disrupt your upgrade.

== Upgrade Options

There are two ways to upgrade your ownCloud server:

1.  *(Recommended)* Perform a xref:maintenance/manual_upgrade.adoc[manual upgrade], using
http://owncloud.org/install/[the latest ownCloud release].
2.  *(Discouraged)* Use xref:maintenance/package_upgrade.adoc[your distribution’s package manager],
in conjunction with our official ownCloud repositories. *Note:* This approach should not be used unattended
nor in clustered setups.
We discourage upgrades with Linux Package Manager because you might encounter unwanted side effects.

NOTE: Enterprise customers will use their Enterprise software repositories to maintain their ownCloud servers, rather than the Open Build Service. Please see xref:enterprise/installation/install.adoc[Installing & Upgrading ownCloud Enterprise Edition] for more information.
