= Media Viewer App
:media-viewer-app-url: https://github.com/owncloud/files_mediaviewer 
:nodejs-url: https://nodejs.org/en/
:npm-url: https://www.npmjs.com/get-npm
:install-imagemagick-url: https://www.tecmint.com/install-imagemagick-on-debian-ubuntu/
:install-imagemagick-pecl-url: https://www.php.net/manual/en/imagick.installation.php

The {media-viewer-app-url}[Media Viewer App] is a simple viewer for pictures and videos integrated into the files app.

== Requirements

* {nodejs-url}[Node.js]
* {npm-url}[NPM]

== Installing

Before installing the Media Viewer app, run `npm install` && `npm run build` to build the Media Viewer app's dependencies.

== Add Support For More Media Types

To add support for additional media types, in addition to the default set, ensure that {install-imagemagick-url}[ImageMagick] and its {install-imagemagick-pecl-url}[PECL extension] are installed and enabled. 
Next, add new entries to the `enabledPreviewProviders` in `config/config.php`.
Below, is an example of how to configure it.

[source,php]
----
'enabledPreviewProviders' => [
  'OC\\Preview\\PNG',
  'OC\\Preview\\JPEG',
  'OC\\Preview\\GIF',
  'OC\\Preview\\Illustrator',
  'OC\\Preview\\Postscript',
  'OC\\Preview\\Photoshop',
  'OC\\Preview\\TIFF'
],
----

TIP: Look at the sample configuration (`config.sample.php`) in your config folder, for more information about this configuration key.
