= Frequently Asked Questions
:toc: right

== I want to upgrade from Community Version to Enterprise Version. What are the changes?

In ownCloud Enterprise you will get access to new apps and features, mainly targeted towards enterprises; apps and features that ensure security, for example.

You can upgrade to the Enterprise version without concern, as your existing files, shares, and users remain as they are.

== How do I transfer files from one user to another?

See xref:configuration/files/file_sharing_configuration.adoc#transferring-files-to-another-user[transferring files to another user].

== How do I deal with problems caused by using self-signed SSL certificates?

See xref:configuration/server/occ_command.adoc#security[the security section of the OCC command].

== I’m the admin and I lost my password! What do I do now!

See xref:configuration/user/reset_admin_password.adoc[the reset admin password documentation].

== What is a Federated System?

A Federated System is another ownCloud or https://oc.owncloud.com/opencloudmesh.html[OpenCloudMesh]
supporting cloud service.

== Platform-wide known limitations, excluded files

There are known file names that can not be synced with ownCloud, these are:

* Folders and files with a trailing space.
* .htaccess.
* `*.part` files.
* File names that exceed 253 characters.
* https://github.com/owncloud/client/blob/master/sync*exclude.lst[client/sync*exclude list].
* Desktop.ini in the root directory.
* UNIX/Linux hidden files (files whose names have a leading dot, e.g., `.12345.pdf`). 
  Users must activate "_sync hidden files_" to sync them.
