= Frequently Asked Questions
:toc: right

== I Cannot See New LDAP Accounts

Set up a new xref:configuration/server/background_jobs_configuration.adoc#cron-jobs[Cron job] for your Apache user to run occ with xref:configuration/server/occ_command.adoc#listing-users[the `user:sync` command] regularly.
To do so, use `crontab` to open the cron configuration editor.

[source,console]
....
# Replace `www-data` with the correct Apache user for your Linux distribution.
crontab -u www-data -e
....

Then, add the configuration below, save the changes, and exit the cron configuration editor.

[source,cron]
....
*/6 * * * * /usr/bin/php /var/www/owncloud/occ user:sync -n -m disable -r "OCA\User_LDAP\User_Proxy"
....

The command will now be executed every ten minutes.

== I Want To Upgrade From The Community To Enterprise Version. What Is Required?

To make this migration, please contact sales@owncloud.com.
For a comparison of the two editions, see https://owncloud.com/standard-or-enterprise/.

== Code Integrity Warning

Please see xref:configuration/general_topics/code_signing.adoc#fixing-invalid-code-integrity-messages[].

== Warnings in Admin Settings

Please see xref:configuration/server/security_setup_warnings.adoc[].

== Why Do My Uploads Fail?

PHP may time out when uploading large files. 
This issue has been resolved with ownCloud 10.0.10. 
From this version onwards, the web interface also supports https://doc.owncloud.com/server/10.1/admin_manual/release_notes.html#improved-reliability-for-uploads-via-web-interface-on-unreliable-connections[chunked uploads].

== Why Am I Unable To Upgrade My Enterprise Apps Via The Marketplace?

Please log in to https://customer.owncloud.com/, navigate to "_ownCloud Enterprise_", then to your version and then to "_Enterprise Apps_". 
Here, you can download all enterprise Apps.

== I'm The Admin And I Lost My Password! What Do I Do Now!

See xref:configuration/user/reset_admin_password.adoc[the reset admin password documentation].

== How Do I Transfer Files From One User To Another?

See xref:configuration/files/file_sharing_configuration.adoc#transferring-files-to-another-user[transferring files to another user].

TIP: You can find more frequently asked questions answered at https://central.owncloud.org/c/faq.
