= Frequently Asked Questions
:toc: right

[[cannot-see-new-ldap-accounts]]
== I cannot see new LDAP accounts

Set up a new cronjob for your Apache user to run occ with the user:sync command regularly.

Example for Ubuntu:

....
crontab -u www-data -e
....

WARNING: Replace "www-data" with the correct Apache user for your Linux distribution.

Insert

....
*/6 * * * * /usr/bin/php /var/www/owncloud/occ user:sync -n -m disable -r "OCA\User_LDAP\User_Proxy"
....

Save and exit. The command will now be executed every ten minutes.

[[i-want-to-upgrade-from-community-version-to-enterprise-version.-what-are-the-changes]]
== I want to upgrade from Community Version to Enterprise Version. What are the changes?

Please contact sales@owncloud.com.

For a comparison between the editions, see: https://owncloud.com/standard-or-enterprise/

[[code-integrity-warning]]
== Code integrity warning

Please see https://doc.owncloud.com/server/admin_manual/configuration/general_topics/code_signing.html#fixing-invalid-code-integrity-messages

[[warnings-in-admin-settings]]
== Warnings in Admin settings

Please see https://doc.owncloud.com/server/10.0/admin_manual/configuration/server/security_setup_warnings.html

[[why-do-my-uploads-fail]]
== Why do my uploads fail?

Usually, php may time out when uploading large files. This issue has been resolved with ownCloud 10.0.10. From this version onwards, the web interface also supports https://doc.owncloud.com/server/10.1/admin_manual/release_notes.html#improved-reliability-for-uploads-via-web-interface-on-unreliable-connections[chunked uploads].

[[why-am-i-unable-to-upgrade-my-enterprise-apps-via-the-marketplace]]
== Why am I unable to upgrade my Enterprise apps via the Marketplace?

Please log in to https://customer.owncloud.com/, navigate to "ownCloud Enterprise", then to your version and then to "Enterprise Apps". Here you can download all Enterprise Apps.

[[im-the-admin-and-i-lost-my-password-what-do-i-do-now]]
== I’m the admin and I lost my password! What do I do now!

See xref:configuration/user/reset_admin_password.adoc[the reset admin password documentation].

[[how-do-i-transfer-files-from-one-user-to-another]]
== How do I transfer files from one user to another?

See xref:configuration/files/file_sharing_configuration.adoc#transferring-files-to-another-user[transferring files to another user].



Please find more frequently asked questions answered at https://central.owncloud.org/c/faq

