= Frequently Asked Questions
:toc: right

[[i-want-to-upgrade-from-community-version-to-enterprise-version.-what-are-the-changes]]
== I want to upgrade from Community Version to Enterprise Version. What are the changes?

In ownCloud Enterprise you will get access to new apps and features, mainly targeted towards enterprises; apps and features that ensure security, for example.

You can upgrade to the Enterprise version without concern, as your existing files, shares, and users remain as they are.

[[how-do-i-transfer-files-from-one-user-to-another]]
== How do I transfer files from one user to another?

See xref:configuration/files/file_sharing_configuration.adoc#transferring-files-to-another-user[transferring files to another user].

[[how-do-i-deal-with-problems-caused-by-using-self-signed-ssl-certificates]]
== How do I deal with problems caused by using self-signed SSL certificates?

See xref:configuration/server/occ_command.adoc#security[the security section of the OCC command].

[[im-the-admin-and-i-lost-my-password-what-do-i-do-now]]
== I’m the admin and I lost my password! What do I do now!

See xref:configuration/user/reset_admin_password.adoc[the reset admin password documentation].

[[what-is-a-federated-system]]
== What is a Federated System?

A Federated System is another ownCloud or https://oc.owncloud.com/opencloudmesh.html[OpenCloudMesh]
supporting cloud service.
