= Manual Installation Databases
:toc: right
:page-partial:

== Introduction

This document gives you an overview of databases supported by ownCloud. It describes some basic installation steps and how to create an administrative user for the database. This administrative user is necessary so that the ownCloud database and user who further manages the ownCloud database can be created The ownCloud database user has no access
to other databases! 

== Possible Databases

When installing ownCloud Server & ownCloud Enterprise editions, the administrator may choose one of four supported database products. These are:

* SQLite
* MYSQL/MariaDB (recommended)
* PostgreSQL
* Oracle 11g (Enterprise-edition only)

IMPORTANT: After selecting and installing a database as described below, read the xref:configuration/database/linux_database_configuration.adoc[Database Configuration on Linux]
documentation for more information regarding database engine configuration.

== SQLite

NOTE: SQLite is not supported by the ownCloud Enterprise edition.

IMPORTANT: SQLite should **only** be used for testing and lightweight single user setups.

SQLite has no client synchronization support, so other devices will not be able to synchronize with the data stored in an ownCloud SQLite database.

SQLite will be installed by ownCloud when installed via package manager. The necessary dependencies will be satisfied. If you used the package manager to install ownCloud, you may "Finish Setup" with no additional steps to configure ownCloud using the SQLite database for limited use.

== MYSQL/MariaDB

MariaDB is the ownCloud recommended database. It may be used with either ownCloud Server or ownCloud Enterprise editions. Please look for additional configuration parameters in the
xref:configuration/database/linux_database_configuration.adoc[Database Configuration on Linux]
guides.

include::{partialsdir}installation/manual_installation/mariadb.adoc[leveloffset=+1]

== PostgreSQL

To install postgres, use the following command (or that of your preferred package manager):

[source,console]
----
sudo apt-get install postgresql
----

In order to allow ownCloud access to the database, create a known password for the default user, `postgres`, which was added when the database was installed.

[source,console]
----
sudo -i -u postgres psql
postgres=# \password
Enter new password:
Enter it again:
postgres=# \q
exit
----

== Oracle 11g

Oracle 11g is **only** supported for the ownCloud Enterprise edition. Please see the
xref:enterprise/installation/oracle_db_configuration.adoc[Oracle Database Setup & Configuration]
in the Enterprise documentation section.
