= Scripts for the Script-Guided Installation
:toc: right
:toclevels: 1
:apache_docs: https://httpd.apache.org/docs/2.4/

== Introduction

There are two scripts you can copy and paste for easy installation and upgrades of ownCloud instances. Using these scripts, you can also reapply ownership and access rights. If you administrate more than one ownCloud instance, you still only need the one `owncloud_prep.sh` script. This script is doing the main job. Have as many instance scripts as you have instances to maintain. Only the instance scripts need configuration, e.g. the respective target directory and other predefined information. The `instance.sh` script (or however you will name it) calls `owncloud_prep.sh` with the configuration you defined for the respective instance.

The scripts are written for the `bash` shell. After you copy and paste them, save both in a location where you can easily reuse them.

WARNING: Use the following scripts at your own risk. They may not work as expected if not
properly configured.

NOTE: The scripts are only working with tar archives as sources for installations and upgrades.

TIP: You can also use these scripts if you want to set strong permissions.

== Configuration

NOTE: You only need to edit the `instance.sh` script (or however you name it), if you want to change the default settings.

The following table illustrates the variables to be configured and what they mean.

[width="90%",cols="20%,80%",options="header"]
|===
|Variable | Description
|ocname   | The name of your directory containing the owncloud files (default is owncloud)
|ocroot   | The path to ocname, usually /var/www (no trailing slash, default is /var/www)
|linkroot | The path to your source directory for linking data and apps-external (default /mnt/owncloud_data)
|htuser   | The webserver user (default www-data)
|htgroup  | The webserver group (default www-data)
|rootuser | The root user (default root)
|===

. `ocname` +
This is the _directory name_ where your ownCloud files will be saved. Suggestion: Use `owncloud` for a single instance but feel free to pick any name you like. Do not use slashes (`/`).
+
NOTE: With only one site to serve, use `html` as it requires no additional settings to maintain on the Apache webserver after the installation. If you use any other name like `owncloud`, you need to set the correct directory in the Apache configuration. For more information, see the {apache_docs}[Apache documentation]. If you are hosting additional websites on the same server, better use a name different from the Apache default (html).

. `ocroot` +
This is the _path_ where `ocname` will be created, for example `/var/www`. +
The path must be resolvable! Do not use trailing slashes (`/`). +
`ocroot`/`ocname` is the  path/directory where your webserver points to (document root). +
The script resolves this for example to `/var/www/owncloud`.

. `linkroot` +
Although not mandatory, it is highly recommended that you use symbolic links for the `data` and `apps-external` directories. The `data` directory can grow very large and any copy or move process might take a long time on upgrades. Therefore this directory is often put on external drives or on NFS mounts. The `apps-external` directory is used for all apps not provided by the ownCloud installation. With any physical upgrade you perform, manual intervention like copying may be necessary before finalizing and upgrade. The use of symbolic links makes the administration much easier and less error-prone.
+
The script uses `linkroot` as base for both the `data` and `apps-external` directories. If not already present, it creates the directories from scratch and links them, both for the installation and on upgrades.
+
If you consider using symbolic links, create a base directory at the location of choice (for example: `/mnt/oc_data`) and let that directory be owned by your webserver's user or group. Use this directory as your `linkroot`. Do not use trailing slashes (`/`).

. `htuser` and `htgroup` +
This is the user and group the webserver uses, usually `www-data`.

. `rootuser` +
This is the name of the root user, usually `root`.

== Usage

It is mandatory to run this script with root privileges, because files and directories will be created and ownership and permissions will be set. Call the instance script like:

[source,console]
----
sudo ./instance.sh
----

The script asks you a couple of questions which follow a logical path. Default answers are capitalized.

.When installing
the script extracts the files with tar and automatically extracts them to the target location without copying.

.In case of an upgrade
the old instance path is backed up by renaming and adding a time stamp. A new target folder with the old name is created. This ensures that in case of extracting and preparation issues, you can easily go back to the previous version. After a successful upgrade, you must manually remove the backup folder.

TIP: If you do not install or upgrade, the script sets ownership and permissions only.

NOTE: In case of upgrading, if you have customized the `.htaccess` file in the ownCloud webroot, you have to manually backup your changes and reapply the changes made after the script has finished. Only backup the changes made but not the complete file as this file will be recreated on upgrades and may contain different settings provided by ownCloud. Customizing `.htaccess` can be necessary when you e.g. xref:configuration/integration/ms-teams.adoc[Integrate ownCloud into Microsoft Teams].

=== Script Questions

* **Do you want to secure your .htaccess files post installing/upgrade (y/N)?** +
  Use this if you have configured or upgraded your instance successfully to protect
  your .htaccess files.

* **Do you want to install a new instance (y/N)?** +
  Self explaining

* **Do you want to upgrade an existing installation (y/N)?** +
  Use this if you already have a running instance. Prepare your instance by enabling
  maintenance mode. For security reasons, you will be asked before the script continues! 

* **Use links for data and apps-external directories (Y/n)?** +
  The script uses respectively checks if links or local directories will be / are used. 

* **Do you want to chmod/chown these links (y/N)?** +
  This question is only asked when you use links. If you are not installing or upgrading, 
  answering with yes, you can e.g. re-apply ownership and permissions to the `data` and
  `apps-external` directories. As written above, the data directory can be very large
  and may take long to complete. Note, by design, there is no progressbar... 

* **Please specify the tar file to extract with full path:** +
  Used when installing or upgrading only. Enter the full path/filename to the tar source
  file, downloaded from owncloud.

== Creating the scripts

Save both scripts together in a directory of your choice. Name the `instance.sh` script according to your needs, so you can easily identify to which ownCloud installation it applies. However, the script `owncloud_prep.sh` is called with exactly that name by the instance script, therefore you must save it with exactly that name.

Edit your version of the `instance.sh` script with the parameters that apply to your environment.

Next, make both scripts executable (use the correct script names instead of the placeholder):

[source,console]
----
sudo chmod +x scriptname.sh
----

. The `instance.sh` script
+
[source,bash]
----
include::{examplesdir}installation/manual_installation/instance.sh[]
----

. The `owncloud_prep.sh` script
+
[source,bash]
----
include::{examplesdir}installation/manual_installation/owncloud_prep.sh[]
----

== Final Steps

When running the script, you will see success messages when finished.

.When installing
enter the URL of your ownCloud instance in a browser and continue the setup via the graphical installation wizard. For more information, see xref:installation/installation_wizard.adoc[The Installation Wizard].
The URL you need to enter in the browser depends on the webserver setup taken and either is an external URL or if you installed locally, you should be able to access your ownCloud instance via a browser at `\http://127.0.0.1/owncloud/` or `\http://localhost/owncloud/`.

.When upgrading
follow the steps printed on the screen. Do not forget to reapply manually made changes made to `.htaccess` in your owncloud root directory.
