[[disable-encryption]]
= Disable Encryption
Matthew Setter <matthew@matthewsetter.com>
:keywords: encryption, occ
:description: This guide will show you how to disable encryption in ownCloud.

You may disable encryption only with `occ`. 
Make sure you have backups of all the encryption keys, including those for all users. 
When you do, put your ownCloud server into single-user mode, and then disable your encryption module with this command:

[source,console]
....
sudo -u www-data php occ maintenance:singleuser --on
sudo -u www-data php occ encryption:disable
....

IMPORTANT: Encryption cannot be disabled without the user’s password or
xref:configuration/files/encryption/enabling-user-key-encryption.adoc#how-to-enable-users-file-recovery-keys[file recovery key]. 
If you don’t have access to at least one of these then there is no way to decrypt all files.

When decryption has finished, disable single-user mode, using the following command.

[source,console]
....
sudo -u www-data php occ maintenance:singleuser --off
....

It is possible to disable encryption with the file recovery key, _if_ every user uses them.
If so, xref:configuration/server/occ_command.adoc#encryption[decrypt-all] will use it to decrypt all files.
