= Encryption Configuration Quick Guide
:toc: right
:toclevels: 1

include::encryption-types.adoc[leveloffset=+1]

include::enable-encryption.adoc[leveloffset=+1]

[[master-key-encryption]]
== Master Key Encryption

=== Overview

- The **recommended** type of encryption.
- Best to activate on new instances with no data.
- If you have existing data, use **encrypt all** command. Depending on the amount of existing data, this operation can take a long time.

=== Activate Master Key-Based Encryption

[source,console,subs="attributes"]
....
{occ-command-example-prefix} maintenance:singleuser --on
{occ-command-example-prefix} encryption:enable
{occ-command-example-prefix} encryption:select-encryption-type masterkey -y
{occ-command-example-prefix} encryption:encrypt-all
{occ-command-example-prefix} maintenance:singleuser --off
....

=== View the Encryption Status

[source,console,subs="attributes"]
....
{occ-command-example-prefix} encryption:status
....

==== Decrypt Encrypted Files

Depending on the amount of existing data, this operation can take a long time.

[source,php,subs="attributes"]
....
{occ-command-example-prefix} maintenance:singleuser --on
{occ-command-example-prefix} encryption:decrypt-all
{occ-command-example-prefix} maintenance:singleuser --off
....

==== Deactivate Master Key-based Encryption

[source,console,subs="attributes"]
....
{occ-command-example-prefix} encryption:disable
# ignore the "already disabled" message
{occ-command-example-prefix} app:disable encryption
....

If the master key has been compromised or exposed, you can recreate it.
You will need the current master key for it.

[source,console,subs="attributes"]
....
{occ-command-example-prefix} encryption:recreate-master-key
....

[[user-specific-key-encryption]]
== User-Specific Key-based Encryption

=== Activate User-Specific Key-based Encryption

[source,console,subs="attributes"]
....
{occ-command-example-prefix} maintenance:singleuser --on
{occ-command-example-prefix} encryption:enable
{occ-command-example-prefix} encryption:select-encryption-type user-keys
{occ-command-example-prefix} encryption:encrypt-all
{occ-command-example-prefix} maintenance:singleuser --off
....

After User-specific encryption is enabled, users must log out and log back in to trigger the automatic personal encryption key generation process.

=== Set a Recovery Key

- Go to the "_Encryption_" section of your Admin page.
- Set a recovery key password.
- Ask the users to opt-in to the recovery key.

If a user decides not to opt-in to the recovery key and forgets or loses their password, **the user's data cannot be decrypted**.
This leads to **permanent data loss**.

They need to:

- Go to menu:Settings[Personal > Encryption]
- Enable the Recovery Key

=== View the Encryption Status

[source,console,subs="attributes"]
....
{occ-command-example-prefix} encryption:status
....

=== Decrypt Encrypted Files

[source,console,subs="attributes"]
....
{occ-command-example-prefix} maintenance:singleuser --on
{occ-command-example-prefix} encryption:decrypt-all
#enter **Recovery Key** for **each user**

# Recovery Key is a password set by the admin
{occ-command-example-prefix} maintenance:singleuser --off
....

=== Deactivate User-Specific Key-based Encryption

[source,console,subs="attributes"]
....
{occ-command-example-prefix} encryption:disable

# ignore the "already disabled" message
{occ-command-example-prefix} app:disable encryption
....
