= Encryption Configuration Quick Guide
:toc: right
:toclevels: 1

include::encryption-types.adoc[leveloffset=+1]

include::enable-encryption.adoc[leveloffset=+1]

== Master Key Encryption

=== Overview

- The **recommended** type of encryption.
- Best to activate on new instances with no data.
- If you have existing data, use **encrypt all** command. Depending on the amount of existing data, this operation can take a long time.

=== Activate Master Key-Based Encryption

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} maintenance:singleuser --on
{occ-command-example-prefix} app:enable encryption
{occ-command-example-prefix} encryption:enable
{occ-command-example-prefix} encryption:select-encryption-type masterkey -y
{occ-command-example-prefix} encryption:encrypt-all --yes
{occ-command-example-prefix} maintenance:singleuser --off
----

=== View the Encryption Status

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} encryption:status
----

=== Decrypt Encrypted Files

Depending on the amount of existing data, this operation can take a long time.

[source,php,subs="attributes+"]
----
{occ-command-example-prefix} maintenance:singleuser --on
{occ-command-example-prefix} encryption:decrypt-all
{occ-command-example-prefix} maintenance:singleuser --off
----

=== Deactivate Master Key-based Encryption

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} encryption:disable
# ignore the "already disabled" message
{occ-command-example-prefix} app:disable encryption
----

If the master key has been compromised or exposed, you can recreate it.
You will need the current master key for it.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} encryption:recreate-master-key
----

== User-Specific Key-based Encryption

=== Activate User-Specific Key-based Encryption

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} maintenance:singleuser --on
{occ-command-example-prefix} app:enable encryption
{occ-command-example-prefix} encryption:enable
{occ-command-example-prefix} encryption:select-encryption-type user-keys
{occ-command-example-prefix} encryption:encrypt-all --yes
{occ-command-example-prefix} maintenance:singleuser --off
----

After User-specific encryption is enabled, users must log out and log back in to trigger the automatic personal encryption key generation process.

=== Set a Recovery Key

- Go to the "_Encryption_" section of your Admin page.
- Set a recovery key password.
- Ask the users to opt-in to the recovery key.

If a user decides not to opt-in to the recovery key and forgets or loses their password, **the user's data cannot be decrypted**.
This leads to **permanent data loss**.

They need to:

- Go to menu:Settings[Personal > Encryption]
- Enable the Recovery Key

=== View the Encryption Status

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} encryption:status
----

=== Decrypt Encrypted Files

If you have an instance with a few users, you can use this example to decrypt the files. Note that you have to enter the password for each user manually.
The ownCloud admin must be certain all users already have enabled the recovery password option in their personal settings page.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} maintenance:singleuser --on
{occ-command-example-prefix} encryption:decrypt-all
#Choose the "Recovery key" Option
#Enter **Recovery Key** for **each user**

# Recovery Key is a password set by the admin
{occ-command-example-prefix} maintenance:singleuser --off
----

If you have a large instance with many users, use this to decrypt the files:

* Set the variable as export `OC_RECOVERY_PASSWORD=1111`, then run this set of commands:
(Replace "1111" with your actual Recovery Key)

[source,console,subs="attributes+"]
----
export OC_RECOVERY_PASSWORD=1111
{occ-command-example-prefix} maintenance:singleuser --on
sudo -E -u www-data php occ encryption:decrypt-all -m recovery -c yes
{occ-command-example-prefix} maintenance:singleuser --off
----

=== Deactivate User-Specific Key-based Encryption

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} encryption:disable

# ignore the "already disabled" message
{occ-command-example-prefix} app:disable encryption
----

=== Cleanup your database

Access your ownCloud database and remove the remaining entries 
that haven't been automatically removed with this command:

[source,sql]
----
DELETE FROM oc_appconfig WHERE appid='encryption';
----

=== Cleanup your storage

Lastly you have to delete all encryption keys on storage by running this command: 

(Modify the path to your data directory according to your installation)

----
find /var/www/html/owncloud/data -type d -name "files_encryption" -exec rm -R {} +
----

At this point, keys are deleted from storage. 
