= Moving Encryption Key Location

View current location of keys:

[source,console,subs="attributes"]
....
{occ-command-example-prefix} encryption:show-key-storage-root
Current key storage root:  default storage location (data/)
....

You can move the keys to another folder inside your data directory. Moving your keys outside of your data folder is not supported.
The folder must already exist, be owned by root and your HTTP group, and be restricted to root and your HTTP group.

This example is for _Ubuntu Linux_.
Note that the new folder is relative to your `occ` directory (which in the example below is assumed that owncloud is installed at `/var/www/owncloud`):

[source,console,subs="attributes"]
....
mkdir /var/www/owncloud/data/new_keys
chown -R root:www-data /var/www/owncloud/data/new_keys
chmod -R 0770 /var/www/owncloud/data/new_keys
{occ-command-example-prefix} encryption:change-key-storage-root new_keys
Change key storage root from default storage location to new_keys
Start to move keys:
   4 [============================]
Key storage root successfully changed to new_keys
....

