= Configuring the Activity App
:page-aliases: configuration_server/activity_configuration.adoc

You can configure your ownCloud server to automatically send out e-mail
notifications to your users for various events like:

* A file or folder has been shared
* A new file or folder has been created
* A file or folder has been changed
* A file or folder has been deleted

Users can see actions (delete, add, modify) that happen to files they
have access to. Sharing actions are only visible to the sharer and
recipient.

== Enabling the Activity App

The Activity App is shipped and enabled by default. If it is not enabled
simply go to your ownCloud Apps page to enable it.

== Configuring your ownCloud for the Activity App

To configure your ownCloud to send out e-mail notifications a working
email_configuration is mandatory.

Furthermore it is recommended to configure the https://doc.owncloud.com/server/10.2/admin_manual/configuration/server/background_jobs_configuration.html#cron-jobs[background job] `Webcron`
or `Cron`.

There is also a https://doc.owncloud.com/server/10.2/admin_manual/configuration/server/config_apps_sample_php_parameters.html#app-activityconfig.php[configuration option] `activity_expire_days` available in your `config.php` which allows you to
clean-up older activities from the database.