= Background Jobs
:toc: right

== Introduction

A system like ownCloud sometimes requires tasks to be done on a regular
basis without requiring user interaction or hindering ownCloud’s
performance. For that reason, as a system administrator, you can
configure background jobs (for example, database clean-ups) to be
executed without any user interaction.

These jobs are typically referred to as https://en.wikipedia.org/wiki/Cron[Cron Jobs]. 
Cron jobs are commands or shell-based scripts that are scheduled to periodically run at fixed times, dates, or intervals. 

To run Cron jobs with ownCloud, you can use the `system:cron.php`.

include::{partialsdir}configuration/server/system_command.adoc[]

== Available Background Jobs

A number of existing background jobs are available to be run just for
specific tasks.

[NOTE]
====
These jobs are generally only needed on large instances and can be run as background jobs.
If the number of users in your installation ranges between 1,000 and 3,000, or if you’re using LDAP and it becomes a bottleneck, then admins can delete several entries in the `oc_jobs` table and replace them with the corresponding `occ` command, which you can see here:

* `OCA\\DAV\CardDAV\\SyncJob` -> `occ dav:sync-system-addressbook`
* `OCA\\Federation\\SyncJob` -> `occ federation:sync-addressbooks`
* `OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash` -> `occ trashbin:expire`
* `OCA\\Files_Versions\\BackgroundJob\\ExpireVersions` -> `occ versions:expire`

If used, these should be scheduled to run on a daily basis.
====

While not exhaustive, these include:

==== CleanupChunks

The CleanupChunks command, `occ dav:cleanup-chunks`, will clean up outdated chunks (uploaded files) more than a certain number of days old and needs to be added to your crontab.

NOTE: There is no matching background job to delete from the `oc_jobs` table.

==== ExpireTrash

The ExpireTrash job, contained in
`OCA\Files_Trashbin\BackgroundJob\ExpireTrash`, will remove any file in
the ownCloud trash bin which is older than the specified maximum file
retention time. It can be run, as follows, using the OCC command:

----
occ trashbin:expire
----

==== ExpireVersions

The ExpireVersions job, contained in
`OCA\Files_Versions\BackgroundJob\ExpireVersions`, will expire versions
of files which are older than the specified maximum version retention
time. It can be run, as follows, using the OCC command:

----
occ versions:expire
----

CAUTION: Please take care when adding `ExpireTrash` and `ExpireVersions` as xref:cron[Cron] jobs. Make sure that they’re not started in parallel on multiple machines. Running in parallel on a single machine is fine. But, currently, there isn’t sufficient locking in place to prevent them from conflicting with each other if running in parallel across multiple machines.

==== SyncJob (CardDAV)

The CardDAV SyncJob, contained in `OCA\DAV\CardDAV\SyncJob`, syncs the
local system address book, updating any existing contacts, and deleting
any expired contacts. It can be run, as follows, using the OCC command:

----
occ dav:sync-system-addressbook
----

==== SyncJob (Federation)

OCAFederationSyncJob

It can be run, as follows, using the OCC command:

----
occ federation:sync-addressbooks
----

== Troubleshooting

=== Forbidden error for Scanner.php
If you find a **Forbidden** error message in your log files, with a reference to the `Scanner.php` file, then you should

- check if you have any shares with the status `pending`

- configure `conditional logging` for cron to see more output
