= Memory Caching
:toc: right

== Introduction

You can significantly improve ownCloud server performance by using
memory caching. This is the process of storing frequently-requested
objects in-memory for faster retrieval later. There are two types of
memory caching available:

*A PHP opcode Cache (OPcache):* An opcode cache stores compiled PHP
scripts so they don’t need to be re-compiled every time they are called.
These compiled PHP scripts are stored in-memory, on the server on which
they’re compiled.

*A Data Cache:* A data cache stores copies of _data_, _templates_, and
other types of _information-based files_. Depending on the cache
implementation, it can be either _local_, or specific, to one server, or
_distributed_ across multiple servers. This cache type is ideal when you
have a scale-out installation.

== Supported Caching Backends

The caching backends supported by ownCloud are:

* xref:apcu[APCu]: This is a local cache for systems running PHP 5.6
and up. APCu 4.0.6 and up is required. Alternatively you can use
the Zend OPCache. However, *it is not a data cache*, only an opcode
cache.
* xref:redis[Redis]: This is a distributed cache for multi-server
ownCloud installations. Version 2.2.6 or higher of the PHP Redis
extension is required.
* xref:memcached[Memcached]: This is a distributed cache for
multi-server ownCloud installations.

[NOTE]
====
You may use _both_ a local and a distributed cache.
The recommended ownCloud caches are APCu and Redis.
If you do not install and enable a local memory cache you will see a warning on your ownCloud admin page.
If you enable only a distributed cache in your `config.php` (`memcache.distributed`) and not a local cache (`memcache.local`) you will still see the cache warning.
====

=== Cache Directory Location

The cache directory defaults to `data/$user/cache` where `$user` is the
current user. You may use the `'cache_path'` directive in `config.php`
(See config_sample_php_parameters) to select a different location.

== Quick Configuration Example

Install APCu and Redis:

[source,console]
----
apt install php-apcu php-redis redis-server
----

Enable them by adding this to your config.php:

[source,php]
----
'memcache.local' => '\OC\Memcache\APCu',
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => [
    'host' => 'localhost',
    'port' => 6379,
],
----

Restart your web server and you are ready to go.


== Cache Types

=== APCu

PHP 5.6 and up include the Zend OPcache in core, and on most Linux
distributions it is enabled by default. However, it _does not_ bundle a
data cache. Given that, we recommend that you use APCu instead. APCu is
a data cache _and_ is available in most Linux distributions.

==== Installing APCu

[source,console]
----
# On Ubuntu/Debian/Mint systems
apt install php-apcu

----

With that done, assuming that you don’t encounter any errors, restart
Apache and the extension is ready to use.

=== Redis

http://redis.io/[Redis] is an excellent modern memory cache to use for both distributed caching
and as a local cache for xref:configuration/files/files_locking_transactional.adoc[transactional file locking], 
because it guarantees that cached objects are available for as long as they are needed.

The Redis PHP module must be at least version 2.2.6 or higher.
If you are running a Linux distribution that does not package the supported versions of this module — or does not package Redis at all — see xref:installing-redis-on-other-distributions[Installing Redis on other distributions].

==== Installing Redis

If you have Ubuntu 16.04 or higher:

[source,console]
----
apt install redis-server php-redis
----

The installer will automatically launch Redis and configure it to launch at startup.

After that, assuming that you don’t encounter any errors, restart Apache
and the extension is ready to use.

==== Additional notes for Redis vs. APCu on Memory Caching

APCu is faster at local caching than Redis. If you have enough memory,
use APCu for memory caching and Redis for file locking. If you are low
on memory, use Redis for both.


==== Clearing the Redis Cache

The Redis cache can be flushed from the command-line using
https://redis.io/topics/rediscli[the redis-cli tool], as in the following example:

----
sudo redis-cli
SELECT <dbIndex>
FLUSHDB
----

`<dbIndex>` is the number of Redis database where the cache is stored.
It is zero by default at ownCloud. To check what yours is currently set
to, check the `dbindex` value in `config/config.php`. Here’s an example
of what to look for:

[source,php,subs="attributes+"]
----
'redis' => [
    'host' => 'localhost',  // Can also be a unix domain socket => '/tmp/redis.sock'
    'port' => {std-port-redis},
    'timeout' => 0,
    'password' => '',       // Optional, if not defined no password will be used.
    'dbindex' => 0          // Optional, if undefined SELECT will not run and will
                            // use Redis Server's default DB Index.
],
----

.Further Reading
****
* https://redis.io/commands/select
* https://redis.io/commands/flushdb
****

=== Memcached

Memcached is a reliable old-timer for shared caching on distributed
servers. It performs well with ownCloud with one exception: it is not
suitable to use with xref:configuration/files/files_locking_transactional.adoc[Transactional File Locking].
This is because it does not store locks, and data can disappear from the
cache at any time. Given that, Redis is the best memory cache to use.

NOTE: Be sure to install the *memcached* PHP module, and not _memcache_, as in the following examples.
ownCloud supports only the *memcached* PHP module.

==== Installing Memcached

===== On Ubuntu/Debian//Mint

On Ubuntu/Debian/Mint run the following command:

[source,console]
----
apt-get install memcached php5-memcached
----

NOTE: The installer will automatically start `memcached` and configure it to launch at startup.

==== Configuration File Paths

[cols=",",options="header",]
|===
| PHP Version | Filename
| 5.6 | `/etc/opt/rh/rh-php56/php.d/25-memcached.ini`
| 7.0 | `/etc/opt/rh/rh-php70/php.d/25-memcached.ini`
|===

After that, assuming that you don’t encounter any errors:

1.  Restart your Web server
2.  Add the appropriate entries to `config.php` (which you can find an
example of below)
3.  Refresh your ownCloud admin page

==== Clearing the Memcached Cache

The Memcached cache can be flushed from the command-line using a range
of common Linux/UNIX tools, including `netcat` and `telnet`.
The following example uses telnet to login, run 
https://github.com/memcached/memcached/wiki/Commands#flushall[the flush_all command], and logout:

[source,console,subs="attributes+"]
----
telnet localhost {std-port-memcache}
flush_all
quit
----

For more information see:

* https://github.com/memcached/memcached/wiki/Commands#flushall

== Configuring Memory Caching

Memory caches must be explicitly configured in ownCloud by:

1.  Installing and enabling your desired cache (whether that be the PHP
extension and/or the caching server).
2.  Adding the appropriate entry to ownCloud’s `config.php`.

See config_sample_php_parameters for an overview of all possible config parameters.
After installing and enabling your chosen memory cache, verify that it is active by viewing xref:configuration/general_topics/general_troubleshooting.adoc#php-version-and-information[the PHP configuration details].

=== APCu Configuration

To use APCu, add this line to `config.php`:

[source,php]
----
'memcache.local' => '\OC\Memcache\APCu',
----

With that done, refresh your ownCloud admin page, and the cache warning
should disappear.

=== Redis Configuration

This example `config.php` configuration uses Redis for the local server
cache:

[source,php,subs="attributes+"]
----
'memcache.local' => '\OC\Memcache\Redis',
'redis' => [
    'host' => 'localhost',
    'port' => {std-port-redis},
],
----

For best performance add the following

[source,php]
----
'memcache.locking' => '\OC\Memcache\Redis',
----

If you want to connect to Redis configured to listen on an Unix socket,
which is recommended if Redis is running on the same system as ownCloud,
use this example configuration:

[source,php]
----
'memcache.local' => '\OC\Memcache\Redis',
'redis' => [
     'host' => '/var/run/redis/redis.sock',
     'port' => 0,
],
----

Redis is very configurable; consult http://redis.io/documentation[the Redis documentation] to learn more.

=== Memcached Configuration
Redis is very configurable;
This example uses APCu for the local cache, Memcached as the distributed
memory cache, and lists all the servers in the shared cache pool with
their port numbers:

[source,php,subs="attributes+"]
----
'memcache.local' => '\OC\Memcache\APCu',
'memcache.distributed' => '\OC\Memcache\Memcached',
'memcached_servers' => [
     ['localhost', {std-port-memcache}],
     ['server1.example.com', {std-port-memcache}],
     ['server2.example.com', {std-port-memcache}],
 ],
----

=== Configuration Recommendations Based on Type of Deployment

==== Small/Private Home Server

[source,php]
----
// Only use APCu
'memcache.local' => '\OC\Memcache\APCu',
----

==== Small Organization, Single-server Setup

Use APCu for local caching, Redis for file locking

[source,php,subs="attributes+"]
----
'memcache.local' => '\OC\Memcache\APCu',
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => [
    'host' => 'localhost',
    'port' => {std-port-redis},
],
----

==== Large Organization, Clustered Setup

Use Redis for everything except a local memory cache. Use the server’s
IP address or hostname so that it is accessible to other hosts:

[source,php,subs="attributes+"]
----
'memcache.distributed' => '\OC\Memcache\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'memcache.local' => '\OC\Memcache\APCu',
'redis' => [
    'host' => 'server1',      // hostname example
    'host' => '12.34.56.78',  // IP address example
    'port' => {std-port-redis},
],
----

=== Configuring Transactional File Locking

xref:configuration/files/files_locking_transactional.adoc[Transactional File Locking] prevents simultaneous file saving.
It is enabled by default and uses the database to store the locking data. This places a significant load on your database. It is recommended to use a cache backend instead. You have to configure it in `config.php` as in the following example, which uses Redis as the cache backend:

[source,php,subs="attributes+"]
----
'filelocking.enabled' => true,
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => [
     'host' => 'localhost',
     'port' => {std-port-redis},
     'timeout' => 0.0,
     'password' => '', // Optional, if not defined no password will be used.
 ],
----

CAUTION: For enhanced security it is recommended to configure Redis to require a password. 
See http://redis.io/topics/security for more information.

== Caching Exceptions

If ownCloud is configured to use either Memcached or Redis as a memory
cache, please be aware that you may encounter issues with functionality.
When these occur, it is usually a result of PHP being incorrectly
configured, or the relevant PHP extension not being available.

In the table below, you can see all of the known reasons for reduced or
broken functionality related to caching.

[width="100%",cols="41%,59%",options="header",]
|===
| Setup/Configuration                              | Result
| If file locking is enabled, but the locking cache class is missing,
then an exception will appear in the web UI        | The application will not be usable
| If file locking is enabled and the locking cache is configured, but the
PHP module missing.                                | There will be a white page/exception in web UI. It
will be a full page issue, and the application will not be usable
| All enabled, but the Redis server is not running | The application will
be usable. But any file operation will return a "500 Redis went away" exception
| If Memcache is configured for `local` and `distributed`, but the
class is missing                                   | There will be a white page and an exception written to
the logs, This is because autoloading needs the missing class. So there is no way to show a page
|===

