= Using the occ Command
:toc: macro
:toclevels: 2
:page-aliases: configuration/server/occ_app_command.adoc,go/admin-cli-upgrade.adoc,configuration/files/external_storage_configuration.adoc
:php-datetime-url: https://php.net/manual/datetime.formats.php
:hsm-overview-url: https://www.cryptomathic.com/news-events/blog/understanding-hardware-security-modules-hsms
:owncloud-support-url: https://owncloud.com/licenses/owncloud-support-maintenance/

ownCloud's `occ` command (ownCloud console) is ownCloud's command-line interface. 
You can perform many common server operations with `occ`, such as installing and upgrading ownCloud, managing users and groups, encryption, passwords, LDAP setting, and more.

toc::[]

== Running occ

=== As Your HTTP User

On a regular ownCloud installation, `occ` is in the `owncloud/` directory; for example `/var/www/owncloud` on Ubuntu Linux. `occ` is a PHP script.

*You must run it as your HTTP user* to ensure that the correct permissions are maintained on your ownCloud files and directories. The HTTP user is different on the various Linux distributions. 

* The HTTP user and group in Debian/Ubuntu is `www-data`.
* The HTTP user and group in Fedora/CentOS is `apache`.
* The HTTP user and group in Arch Linux is `http`.
* The HTTP user in openSUSE is `wwwrun`, and the HTTP group is `www`.

TIP: See xref:installation/manual_installation.adoc#set-strong-directory-permissions[Setting Strong Permissions] to learn how to find your HTTP user.

If your HTTP server is configured to use a different PHP version than the default (/usr/bin/php), `occ` should be run with the same version.
For example, in CentOS 6.5 with SCL-PHP54 installed, the command looks like this:

----
sudo -u apache /opt/rh/php54/root/usr/bin/php /var/www/html/owncloud/occ
----

=== With a Docker Container

If your ownCloud instance is set up in a docker container, you need a user in the group `docker` to perform `occ` commands. An example command looks like this:

[source,console]
----
docker exec --user www-data <owncloud-container-name> php occ <your-command>
----

For more information on docker, refer to section xref:installation/docker/index.adoc[Installing with Docker].

=== With the ownCloud Appliance

The ownCloud Appliance offers two possibilities to perform `occ` commands:

. Log in to the ownCloud instance as root user with the command `univention-app shell owncloud`. Then use `occ` commands without a preceeding `sudo -u www-data php`.

. Alternatively, you can use `occ` on the host system with the command `univention-app shell owncloud occ` followed by the desired options, commands and arguments.

If you want to find out more about the Appliance, click xref:appliance/index.adoc[here].

=== Example Commands

Running `occ` with no options lists all commands and options, like this example on Ubuntu:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix}
ownCloud version 10.0.8

Usage:
 command [options] [arguments]

==== Options
 -h, --help            Display this help message
 -q, --quiet           Do not output any message
 -V, --version         Display this application version
     --ansi            Force ANSI output
     --no-ansi         Disable ANSI output
 -n, --no-interaction  Do not ask any interactive question
     --no-warnings     Skip global warnings, show command output only
 -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output,
                       2 for more verbose output and 3 for debug

Available commands:
 check                 Check dependencies of the server environment
 help                  Displays help for a command
 list                  Lists commands
 status                Show some status information
 upgrade               Run upgrade routines after installation of
                       a new release. The release has to be installed before
----

This is the same as `{occ-command-example-prefix} list`. 
Run it with the `-h` option for syntax help:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} -h
----

Display your ownCloud version:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} -V
  ownCloud version 10.0.8
----

Query your ownCloud server status:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} status
  - installed: true
  - version: 10.0.8.5
  - versionstring: 10.0.8
  - edition: Community
----

`occ` has _options_, _commands_, and _arguments_. 
Commands are required.
Options are optional. 
Arguments can be required _or_ optional. 
The, generic, syntax is:

----
occ [options] command [arguments]
----

Get detailed information on individual commands with the `help` command, like this example for the `maintenance:mode` command.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} help maintenance:mode
Usage:
 maintenance:mode [options]

Options
     --on              Enable maintenance mode
     --off             Disable maintenance mode
     --output[=OUTPUT] Output format (plain, json or json_pretty, default is plain) [default: "plain"]
 -h, --help            Display this help message
 -q, --quiet           Do not output any message
 -V, --version         Display this application version
     --ansi            Force ANSI output
     --no-ansi         Disable ANSI output
 -n, --no-interaction  Do not ask any interactive question
     --no-warnings     Skip global warnings, show command output only
 -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output,
                       2 for more verbose output and 3 for debug
----

The `status` command from above has an option to define the output format. 
The default is plain text, but it can also be `json`

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} status --output=json
{"installed":true,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}
----

or `json_pretty`

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} status --output=json_pretty
{
   "installed": true,
   "version": "10.0.8.5",
   "versionstring": "10.0.8",
   "edition": "Community"
}
----

This output option is available on all list and list-like commands, which include `status`, `check`, `app:list`, `config:list`, `encryption:status` and `encryption:list-modules`.

== Core Commands

This command reference covers the ownCloud core commands.

include::./occ_commands/core_commands/app_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/background_jobs_selector.adoc[leveloffset=+2]

include::./occ_commands/core_commands/config_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/config_reports_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/command_line_installation_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/command_line_upgrade_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/dav_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/database_conversion_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/encryption_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/federation_sync_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/file_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/files_external_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/full_text_search_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/group_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/integrity_check_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/localisation_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/logging_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/managing_background_jobs.adoc[leveloffset=+2]

include::./occ_commands/core_commands/maintenance_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/migration_steps_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/mimetype_update_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/notifications_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/incoming_shares_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/security_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/sharing_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/trashbin_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/user_commands.adoc[leveloffset=+2]

include::./occ_commands/core_commands/versions_commands.adoc[leveloffset=+2]

== Apps Commands

This command reference covers the ownCloud maintained apps commands.

include::./occ_commands/app_commands/activity_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/antivirus_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/admin_audit_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/brute_force_protection_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/calendar_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/contacts_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/data_explorer_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/files_lifecycle.adoc[leveloffset=+2]

include::./occ_commands/app_commands/ldap_integration_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/market_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/metrics_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/password_policy_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/ransomware_protection_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/richdocuments.adoc[leveloffset=+2]

include::./occ_commands/app_commands/s3objectstore_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/saml_sso_shibboleth_integration_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/2fa_commands.adoc[leveloffset=+2]

include::./occ_commands/app_commands/wnd_commands.adoc[leveloffset=+2]
