= Network File System (NFS) Deployment Recommendations
:keywords: nfs, network file system, nfsv4, mtu, async, noasync
:description: This guide covers the official ownCloud NFS (Network File System) deployment recommendations.
:autofs-url: https://help.ubuntu.com/community/Autofs
:lockd-url: https://docs.oracle.com/cd/E19455-01/806-0916/rfsrefer-9/index.html
:mount-man-page-url: http://man7.org/linux/man-pages/man8/mount.8.html
:netplan-docs-url: https://netplan.io/reference
:networkmanager-url: https://help.ubuntu.com/community/NetworkManager
:networkworld-mtu-size-issues-url: https://www.networkworld.com/article/2224654/mtu-size-issues.html
:nfs-man-page-url: https://linux.die.net/man/5/nfs
:nfs-read-write-delegations-url: https://tools.ietf.org/html/rfc7530#section-1.4.6
:nfs-strong-security-architecture-url: https://tools.ietf.org/html/rfc7530#section-3 
:nmcli-url: https://manpages.ubuntu.com/manpages/disco/man1/nmcli.1.html
:nmtui-url: https://manpages.ubuntu.com/manpages/disco/man1/nmtui.1.html
:rpc-statd-url: https://linux.die.net/man/8/rpc.statd

ownCloud recommends using NFS for any scenario other than local storage. 
It has solid performance and is very stable.
This document contains ownCloud's official deployment recommendations.

There can be different scenarios where ownCloud's storage is located on an NFS mount (primary/secondary). Also in some scenarios multiple application servers can use the same NFS mount.

== Use NFSv4

We recommend using NFSv4 over previous versions for a number of key reasons.
These are:

* *Improved Security:* It {nfs-strong-security-architecture-url}[mandates a strong security architecture]. It does not require {rpc-statd-url}[rpc.statd] or {lockd-url}[lockd]. As a result, it only uses port 2049.
* *Improved Reliability:* Uses TCP by default instead of UDP.
* *Improved Performance:* It uses Multi-Component Messages, which reduce network traffic. It is capable of using a 32KB page size, compared to the default, 1024 bytes.
* Use of {nfs-read-write-delegations-url}[Read/Write Delegations].

== Tune the Mount Parameters

=== _netdev

Use this option to ensure that the network is enabled, before NFS attempts to mount these filesystem.
This setting is essential when MySQL's data files are located on the NFS storage.
MySQL could error if the mount is not ready before attempting to access its data files.

TIP: You can also use {autofs-url}[autofs] to ensure that mounts are always available before attempting to access them.

=== soft

We recommend this option to better handle storage failures.
If `hard` is used, turning off the ownCloud server is likely to be problematic, and you need a boot and shutdown sequence in the servers.

=== retrans

Use this option to set the number of minor timeouts and retransmissions before major timeouts happen.
Major timeouts either abort file operations or display the "server not responding" message.
We recommend that you set it to ?.

=== timeo

Use this option, set in tenths of a second, to set the time before an initial retransmission after a timeout.

According to {nfs-man-page-url}[the NFS man page], better overall performance may be achieved by increasing the timeout when mounting on a busy network, to a slow server, or through several routers or gateways. 
We recommend that you set it to ?.

=== noasync

In clustered environments, we recommend setting the `noasync` option, to avoid filesystem I/O being handled asynchronously. 
This has become the default on most distributions, but we recommend checking what this is set to in your ownCloud installations.

=== noac

The `noac` option should be used with caution. 
Quoting the NFS man page:

[quote, nfs man page]
Using the noac option provides greater cache coherence among NFS clients accessing the same files, *but it extracts a significant performance penalty*. As such, judicious use of file locking is encouraged instead.

== Tune the Read and Write Block Sizes

The allowed block sizes are the packet chunk sizes that NFS uses when reading and writing data.
The smaller the size, the greater the number of packets need to be sent to send or receive a file.
Conversely, the larger the size, the fewer the number of packets need to be sent to send or receive a file.

You can find this information by working with the output of the `mount` command, as in the example below.

[source,console]
----
#root@server:~# mount | grep /mnt/owncloud | egrep -o rsize=[0-9]*
rsize=65536

#root@server:~# mount | grep /mnt/owncloud | egrep -o wsize=[0-9]*
wsize=65536
----

Once you've determined the best sizes, set them permanently by passing the (`rsize` and `wsize`) options when mounting the share or in the share's mount configuration.

.Specifying the read and write block sizes when calling mount
[source, console]
----
mount 192.168.0.104:/data  /mnt -o rsize=65536,wsize=65536
----

=== Tune the MTU (Maximum Transmission Unit) Size

The MTU size dictates the maximum amount of data that can be transferred in one Ethernet frame.
If the MTU size is too small, then regardless of the read and write block sizes, the data must still be fragmented across multiple frames.
You can find the current MTU size for each interface using _netstat_, _ifconfig_, _ip_, and _cat_, as in the following examples:

.Retrieve interface MTU size with netstat
[source,console]
----
netstat -i

Kernel Interface table
Iface      MTU    RX-OK RX-ERR RX-DRP RX-OVR    TX-OK TX-ERR TX-DRP TX-OVR Flg
lo       65536   363183      0      0 0        363183      0      0      0 LRU
wlan0     1500  3138292      0      0 0       2049155      0      0      0 BMR
----

.Retrieve interface MTU size with ifconfig
[source,console]
----
ifconfig| grep -i MTU

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
----

.Retrieve interface MTU size with ip
[source,console]
----
ip addr | grep mtu

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
----

.Retrieve interface MTU size with cat
[source,console]
----
cat /sys/class/net/<interface>/mtu
----

To change the MTU size, under Ubuntu:

* If {networkmanager-url}[NetworkManager] is managing all devices on the system, then you can use {nmtui-url}[nmtui] or {nmcli-url}[nmcli] to configure the MTU setting.
* If NetworkManager is not managing all devices on the system, you can set the MTU to 1280 with Netplan, as in the following example.
+
[source,yaml]
----
network:
  version: 2
  ethernets:
    eth1:
      mtu: 1280
----
+
Refer to {netplan-docs-url}[the Netplan documentation] for further information.

TIP: NetworkWorld has {networkworld-mtu-size-issues-url}[an excellent overview of MTU size issues]. 
