= Apps Config.php Parameters

This document describes parameters for apps maintained by ownCloud that are not part of the core system.
All keys are only valid if the corresponding app is installed and enabled. 
You must copy the keys needed to the active `config.php` file.

[[multiple-configuration-files]]
== Multiple configuration files

ownCloud supports loading configuration parameters from multiple files.
You can add arbitrary files ending with .config.php in the config/ directory.

=== Example:

You could place your email server configuration in `email.config.php`.
This allows you to easily create and manage custom configurations, or to divide a large complex configuration file into a set of smaller files.
These custom files are not overwritten by ownCloud, and the values in these files take precedence over `config.php`.

ownCloud may write configurations into `config.php`. 
These configurations may conflict with identical keys already set in additional config files. Be careful when using this capability!

// header end do not delete or edit this line

== App: Activity

Possible values: `activity_expire_days` days

=== Retention for activities of the activity app

==== Code Sample

[source,php]
....
'activity_expire_days' => 365,
....

== App: LDAP

Possible values: `ldapIgnoreNamingRules` 'doSet' or false

Possible values: `user_ldap.enable_medial_search` true or false

=== Configuring the LDAP app

==== Code Sample

[source,php]
....
'ldapIgnoreNamingRules' => false,
'user_ldap.enable_medial_search' => false,
....

== App: Market

Possible values: `appstoreurl` URL

=== Configuring the download URL for apps

==== Code Sample

[source,php]
....
'appstoreurl' => 'https://marketplace.owncloud.com',
....

== App: Firstrunwizard

Possible values: `customclient_desktop` URL

Possible values: `customclient_android` URL

Possible values: `customclient_ios` URL

=== Configuring the download links for ownCloud clients,
as seen in the first-run wizard and on Personal pages

==== Code Sample

[source,php]
....
'customclient_desktop' =>
	'https://owncloud.org/install/#install-clients',
'customclient_android' =>
	'https://play.google.com/store/apps/details?id=com.owncloud.android',
'customclient_ios' =>
	'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8',
....

== App: Richdocuments

Possible values: `collabora_group` string

=== Configuring the group name for users allowed to use collabora

==== Code Sample

[source,php]
....
'collabora_group' => '',
....

