= Outdated jQuery Warnings

Some users are afraid because their security scans, which scanning for version numbers of library, tell them that jQuery is outdated and this is a security risk.

In some cases the issues were patched or mitigated in other ways.  
While ownCloud is using an older version number we are closely following any security related issues around the library and are making sure that the version we ship inside ownCloud and to all of our customers is fully secure.

Particularly we have identified two issues:  

•	https://github.com/owncloud/core/pull/37596[CVE-2020-11022 / patched in 10.5.0]  

•	https://github.com/owncloud/core/commit/63a14b4eb62a09966ae0166f1b2f48a22c061cf2[CVE-2015-9251 / patched in 10.0.9RC3]  

We continue to monitor and will always keep our customers and users secure! At this time an upgrade would mean lots of retesting and other challenges as newer versions of jQuery also introduce incompatibilities.  
We operate a security bounty program at https://hackerone.com/owncloud[hackerone.com/owncloud] which is very active and effective and of course, welcome to receive pointers and questions from our customers.
