= Two-Factor Authentication

The following commands only enable or disable the two-factor authentication for a particular user. See the xref:two-factor-totp[Two-Factor TOTP] section for managing the two-factor app provided by ownCloud.

If a two-factor provider app is enabled, it is enabled for all users by default but a user has to opt-in, though the provider can decide whether or not the user has to pass the challenge. In case a user is losing access to the second factor like a lost or defect phone with two-factor SMS/app verification, the user would now be locked out. To give the user access to his account, an admin can temporarily disable the two-factor check for that user via the occ command. After the issue has been fixed, the admin can reenable two-factor authentication for that user.

The following commands are available for the two-factor authentication:

[source,console]
----
 twofactorauth
  twofactorauth:disable  Disable two-factor authentication for a user.
  twofactorauth:enable   Enable two-factor authentication for a user.
----

== Disable

Disable two-factor authentication for a user:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} twofactorauth:disable [options] [--] <uid>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `uid`
| The user (user id) to be disabled for two-factor authentication.
|===

== Enable

Enable two-factor authentication for a user:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} twofactorauth:enable [options] [--] <uid>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `uid`
| The user (user id) to be (re)enabled for twofactor authentication.
|===
