= DAV Commands

A set of commands to create and sync address books and calendars:

[source,console]
----
dav
 dav:cleanup-chunks            Cleanup outdated chunks
 dav:create-addressbook        Create a dav address book
 dav:create-calendar           Create a dav calendar
 dav:sync-birthday-calendar    Synchronizes the birthday calendar
 dav:sync-system-addressbook   Synchronizes users to the system address book
----

NOTE: These commands are not available in xref:maintenance-commands[single-user (maintenance) mode].

== Cleanup Chunks

`dav:cleanup-chunks` cleans up outdated chunks (uploaded files) more than a certain number of days old. By default, the command cleans up chunks more than 2 days old. However, by supplying the number of days to the command, the range can be increased.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:cleanup-chunks [options] [--] [<minimum-age-in-days>]
----

=== Arguments

[width="100%",cols="25%,70%",]
|====
| `minimum-age-in-days`
| Minimum age of uploads to cleanup (in days - minimum 2 days - maximum 100) [default: 2]
|====

=== Options

[width="100%",cols="25%,70%",]
|====
| `-l` +
`--local`
| Only delete chunks that exist on the local filesystem. This applies to setups with multiple servers connected to the same database and chunk folder is not shared among them.
|====

=== Example

In the example below, chunks older than 10 days will be removed.
 
[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:cleanup-chunks 10

# example output
Cleaning chunks older than 10 days(2017-11-08T13:13:45+00:00)
Cleaning chunks for admin
   0 [>---------------------------]
----

== Create Addressbook

Create a dav address book.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:create-addressbook <user> <name>
----

=== Arguments

[width="100%",cols="25%,70%",]
|====
| `user`
| User for whom the address book will be created

| `name`
| Name of the addressbook
|====
 
=== Example

This example creates the address book `mollybook` for the user molly:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:create-addressbook molly mollybook
----

Molly will immediately see her address book.

== Create Calendar

Create a dav calendar.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:create-calendar <user> <name>
----

=== Arguments

[width="100%",cols="25%,70%",]
|====
| `user`
| User for whom the calendar will be created

| `name`
| Name of the calendar
|====
 
=== Example

This example creates a new calendar `mollycal` for user molly:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:create-calendar molly mollycal
----

Molly will immediately see her calendar.

// NOTE: dav:migrate-addressbooks has been removed with: https://github.com/owncloud/core/pull/23976


== Sync Birthday Calendar

Synchronizes the birthday calendar. It adds all birthdays to your calendar from address books shared with you.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:sync-birthday-calendar [<user>]
----

=== Arguments

[width="100%",cols="25%,70%",]
|====
| `user`
| User for whom the birthday calendar will be synchronized
|====
 
=== Example

This example syncs to your calendar from user `bernie`:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:sync-birthday-calendar bernie
----

== Sync System Addressbook

Synchronizes all users to the system addressbook.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} dav:sync-system-addressbook
----
