= Poll Incoming Federated Shares For Updates

This command must be used if received federated shares are being referenced by desktop clients but not regularly accessed via the webUI.
This is because, for performance reasons, federated shares do not update automatically.
Instead, federated share directories are only updated when users browse them using the xref:user_manual:files/webgui/overview.adoc[webUI].

ownCloud and system administrators can use the `incoming-shares:poll` command to poll federated shares for updates.

NOTE: The command polls all received federated shares, so does not require a path.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} incoming-shares:poll
----

[IMPORTANT] 
====
When using federation, it is recommended to execute `occ incoming-shares:poll` regularly xref:configuration/server/background_jobs_configuration.adoc#cron-jobs[using Cron jobs]. 
The time interval between executions is a trade-off between the availability of changes in federated shares and resource consumption; which naturally depends a lot on the number of federated shares and the frequency of changes within those shares. 

Executing the command once every 12 hours _should_ be safe enough for most instances. 
However, the interval can be reduced to once every 2 hours, for instances with a small number of federated shares.

Depending on the desired resource consumption, this value should be lowered or increased based on individual expectations. 
To find a value that fits a specific setup, it is recommended to execute the command once, measure the execution time and set the interval, so that the background job can finish before the next execution is triggered.
====
