= Sharing
:page-noindex: yes

This is an occ command to cleanup orphaned remote storages. 
To explain why this is necessary, a little background is required. 
While shares are able to be deleted as a normal matter of course, remote storages with `shared::` are not included in this process.

This might not, normally, be a problem. 
However, if a user has re-shared a remote share which has been deleted it will. 
This is because when the original share is deleted, the remote re-share reference is not.
Internally, the `fileid` will remain in the file cache and storage for that file will not be deleted.

As a result, any user(s) who the share was re-shared with will now get an error when trying to access that file or folder. 
That's why the command is available.
So, to cleanup all orphaned remote storages, run it as follows:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} sharing:cleanup-remote-storages
----

You can also set it up to run as xref:background-jobs-selector[a background job].

NOTE: These commands are not available in xref:maintenance-commands[single-user (maintenance) mode].

include::{partialsdir}configuration/server/occ_command/system_command.adoc[leveloffset=+1]
