= Search Files
// Page attributes
:page-partial:
// Attributes for the core details include
:request_path: remote.php/dav/files/<user> 
:method: REPORT
:content_type: text/xml

The `search-files` report search through the available files in an ownCloud user's filesystem, based on a rudimentary filename pattern match.

By default, the report uses ownCloud's default search provider to power the search functionality. 
However, other search providers, such as https://github.com/owncloud/search_elastic[search_elastic] and https://github.com/owncloudarchive/search_lucene[search_lucene] greatly enrich the ability to search, such as being able to search through file content, as well as by a file's name.
When installed, they replace ownCloud's default search provider and the search API will automatically use them.

TIP: When using the default search provider, if you use the search string "_ownCloud_", files whose filename has "ownCloud" in it will be matched. 
However, if installed https://github.com/owncloud/search_elastic[the search_elastic app], the report also retrieves files that have "_ownCloud_" in the file's contents.

include::{partialsdir}/webdav_api/core_request_details.adoc[leveloffset=+1]

== The Request

An authenticated https://tools.ietf.org/html/rfc3253#section-3.6[REPORT request] needs to be made to search for all files stored in a user's ownCloud filesystem

=== Example Request

[source,console]
----
curl --silent \
  -X REPORT \
  --data "@supported.xml" \
  -u admin:admin \
  'http://localhost/remote.php/dav/files/admin' | xmllint --format -
----

The request must include a request body that includes the search pattern, and can also include a list of properties to return.

=== Example Request Bodies

Below, are several examples of XML response bodies.

==== Filtering By Filename Pattern

In the `search` element, specify the search pattern to filter the list of files to return.

[source,xml]
----
include::{examplesdir}core/webdav_api/search/request/search_files/minimal_request_body.xml[indent=0]
----

==== Limiting The Number Of Results Returned

To limit the number of results returned, use the `limit` element of the `search` element, as in the following example.
It will limit the maximum number of results returned to five.

[source,xml]
----
include::{examplesdir}core/webdav_api/search/request/search_files/limit_number_of_results.xml[indent=0]
----

==== Reducing The File Properties Returned

However, if a specific list of properties is required for each file, then a `prop` element needs to be included in the response body, such as in the example below.

include::{partialsdir}/webdav_api/search/file_properties.adoc[]

[source,xml]
----
include::{examplesdir}core/webdav_api/search/request/search_files/search_body_with_properties.xml[indent=0]
----

NOTE: The example uses http://xmlsoft.org/xmllint.html[xmllint] to make the response more readable.
Xmllint is available in the http://www.xmlsoft.org/[libxml2 package].

== The Response

=== Success

Successful requests return two things:

. An XML payload.
. A status of `HTTP/1.1 207 Multi-Status`.

You can see an example of the XML payload below.
The XML payload contains a `response` element for each file.
And each `response` element contains three items:

. A link to the file (`href`).
. The requested properties, along with their respective values (`propstat`).
. The file's status (`status`).

.Search Response
[source,xml]
----
include::{examplesdir}core/webdav_api/search/response/search_files/success/search_response.xml[indent=0]
----

=== Failure

==== If The Payload File Cannot Be Read Or Is Invalid XML

If the payload file cannot be read or is invalid XML, then the following XML response is sent, along with an `HTTP/1.1 500 Internal Server Error` status code.

[source,xml]
----
include::{examplesdir}core/webdav_api/search/response/common/failure/incorrect_payload_or_parse_failure.xml[indent=0]
----

==== If a Non-Existent Property Is Requested 

If a non-existent property is requested, then an additional `propstat` element is returned, as in the example below, which contains a list of the properties which were not available.

[source,xml]
----
include::{examplesdir}core/webdav_api/search/response/common/failure/request_non_existent_property.xml[indent=0,lines=19..25]
----

