= Troubleshooting
:toc: right

== General Troubleshooting

This section contains a list of error messages that ownCloud displays
when things go wrong. For each message, you can find the most likely
cause, a resolution, and one or more translations.

== Problem loading page, reloading in 5 seconds

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Problem beim Laden der Seite, Seite wird in 5 Sekunden nochmals geladen`
|===

== Already existing files

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Bereits existierende Dateien`
|===

== Which files do you want to keep?

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Welche Dateien möchten Sie behalten?`
|===

== Error while sharing

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Fehler beim Teilen`
|===

== Error while unsharing

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Fehler beim Aufheben der Freigabe`
|===

== Error while sending notification

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Fehler beim Senden der Benachrichtigung`
|===

== Resharing is not allowed

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Das Weiterverteilen ist nicht erlaubt`
|===

== Error removing share

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Fehler beim Entfernen der Freigabe`
|===

== Internal Server Error

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Interner Serverfehler`
|===

== This ownCloud instance is currently in single user mode.

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Diese ownClound-Instanz befindet sich derzeit im Einzelbenutzermodus.`
|===

== This %s instance is currently in maintenance mode, which may take a while.

[cols="15%,70%",]
|===
| Cause       |
| Resolution  |
| Translation | `Diese %s-Instanz befindet sich gerade im Wartungsmodus, was eine Weile dauern kann.`
|===

== File Troubleshooting

Listed here are the most common errors you may encounter while
attempting to upload files, along with what they mean, and possible
workarounds.

== Error while copying file to target location (copied bytes: xxx, expected filesize: yyy)

This error is most likely due to an issue with the target storage
location. During file uploads the file data is read from PHP input and
copied into a part file on the target storage.

If the target storage is not local (eg: FTP) and that storage is slow, not available, or broken
it is likely that the operation will fail either at the beginning, or in
the middle of the copy. Other reasons for this message can be that, when
writing to external storage, the connection took too long to respond or
the network connection was flaky.

== Sharing sidebar does not show `Shared with you by …` for remote shares

In some scenarios, when users share folders and files with each other
they cannot be scanned. There are a variety of reasons why this happens,
which can include firewalls and broken servers.

In these situations, when the initial scan did not complete successfully, the mount point
cannot appear in the ownCloud web UI. This is because ownCloud was not
able to generate a matching file cache entry, nor retrieve any metadata
about whether it’s a folder or file (mime type), etc.

== PIM Troubleshooting

BlackBerry OS up to 10.2.2102 does not accept a URL with protocol
`https://` in front of the server address. It will always tell you that
it cannot login on your server. So instead of writing:

----
https://example.com/remote.php/dav/principals/users/USERNAME/
----

in the server address field, you have to write:

----
example.com/remote.php/dav/principals/users/USERNAME/
----
