= Two-Factor TOTP

Marketplace URL: {oc-marketplace-url}/apps/twofactor_totp[2-Factor Authentication]

The following commands manage the _2-Factor Authentication App_. TOTP stands for _time-based one-time password_. There is also a core component independent of the _2-Factor Authentication App_ with which a particular user can be enabled or disabled for the two-factor authentication. For details see section xref:two-factor-authentication[Two-Factor Authentication].

The following commands are available for the 2-Factor Authentication app:

[source,console]
----
 twofactor_totp
  twofactor_totp:delete-redundant-secret         Delete the redundant secret of non-existing users
  twofactor_totp:set-secret-verification-status  Set secret verification status of specified users or all users
----

== Delete Redundant Secrets

Delete the redundant secrets of non-existing users:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} twofactor_totp:delete-redundant-secret
----

== Set Secret Verification Status

Set secret verification status of specified users or all users:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix}  twofactor_totp:set-secret-verification-status [options] [--] <set-verified>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `set-verified`
| Secret verification status to set. (true or false)
|===

=== Options

[width="100%",cols="20%,70%",]
|===
| `--all`
| Will affect all users that use TOTP

| `-u, --uid=UID`
| The user's uid is used. +
This option can be used as --uid="Alice" --uid="Bob" (multiple values allowed)
|===
