= LDAP Integration

Marketplace URL: {oc-marketplace-url}/apps/user_ldap[LDAP Integration]

[source,console]
----
ldap
 ldap:check-user               Checks whether a user exists on LDAP
 ldap:create-empty-config      Creates an empty LDAP configuration
 ldap:delete-config            Deletes an existing LDAP configuration
 ldap:invalidate-cache         Invalidates the LDAP cache
 ldap:search                   Executes a user or group search
 ldap:set-config               Modifies an LDAP configuration
 ldap:show-config              Shows the LDAP configuration
 ldap:test-config              Tests an LDAP configuration
----

== Search for a User

Search for an LDAP user, using this syntax:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:search [options] [--] <search>
----
=== Arguments

[width="100%",cols="20%,70%",]
|===
| `search`
| The search string (can be empty)
|===

=== Options

[width="100%",cols="20%,70%",]
|===
| `--group`
| Searches groups instead of users

| `--offset=OFFSET`
| The offset of the result set. Needs to be a multiple of limit. [default: 0]

| `--limit=LIMIT`
| Limit the results. 0 means no limit. [default: 15]
|===

Note that the search string can be empty to list all users, or groups when the `--group` option is set. In this case, the search string must be declared with `''`. It is by default a prefix search. Start the string with `*` to change to infix (substring) search.

=== Search Configuration and Rules 

Search attributes are configurable in the LDAP wizard (menu:Settings[Admin > User Authentication > LDAP]) or via an occ command `ldap:set-config` as described below:

.General rule
. If User/Group _Search Attributes_ are *NOT* defined (empty), the entry defined in the User/Group _Display Name Field_ is used as the search attribute, for details see below.
. Important when having multiple search attributes, results are unique as long hits correspond to a unique user or group entry.

.Rules for users
. If *User Search Attributes* are defined (not empty) in:
+
menu:Settings[Admin > User Authentication > LDAP > Advanced > User Search Attributes]
+
`ldapAttributesForUserSearch`

.. Example
+
If your search attributes would be `givenName` and `sn` you can find users by first name + last name very quickly. You will find "Terri Hanson" by searching for `te ha`. Trailing whitespace is ignored.
. Else use the *User Display Name Field* which usually defaults to the default displayname attribute "displayname"
+
menu:Settings[Admin > User Authentication > LDAP > Advanced > User Display Name Field]
+
`ldapUserDisplayName`


.Rules for groups
. If *Group Search Attributes* are defined (not empty) in:
+
menu:Settings[Admin > User Authentication > LDAP > Advanced > Group Search Attributes]
+
`ldapAttributesForGroupSearch`
. Else use the *Group Display Name Field* which usually defaults to the default displayname attribute "cn"
+
menu:Settings[Admin > User Authentication > LDAP > Advanced > Group Display Name Field]
+
`ldapGroupDisplayName`

.Offset and Limit
The best way understanding `offset` and `limit` is the following table when using `occ ldap:search '' [options]`
[caption=]
[width="50%",cols="20%,30%",options="header"]
|===
| Options
| Result Set

| `--offset 0` +
`--limit 5`
| "A", "B", "C", "D" and "E"

| `--offset 5` +
`--limit 5`
| "F", "G", "H", "I" and "J"

| `--offset 1` +
`--limit 3`
| "B", "C" and "D"
|===



=== Examples

Searches match at the beginning of the attribute value only. This example searches for `givenNames` that start with 'rob':

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:search "rob"
----

This will find "robbie", "roberta", and "robin".
Broaden the search to find, for example, `jeroboam` with the asterisk wildcard:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:search "*rob"
----

The following examples use `offset` and `limit` options:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:search "re"
Rebecca OShea (Rebecca.OShea)
Rebecca Vintin (Rebecca.Vintin)
Rebekka Da-Cahuna (Rebekka.Da-Cahuna)
Rekha Cox (Rekha.Cox)
Rekha Craft (Rekha.Craft)
----

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:search "re" --offset 0 --limit 3
Rebecca OShea (Rebecca.OShea)
Rebecca Vintin (Rebecca.Vintin)
Rebekka Da-Cahuna (Rebekka.Da-Cahuna)
----

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:search "re" --offset 3 --limit 3
Rekha Cox (Rekha.Cox)
Rekha Craft (Rekha.Craft)
----

== Check if an LDAP User Exists

This only works if the ownCloud server is connected to an LDAP server.

[source,console,subs="attributes+"]
----
ldap:check-user [options] [--] <ocName>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `ocName`
| The user name as used in ownCloud (see e.g. the user's Federated Cloud ID).
|===

=== Options

[width="100%",cols="20%,70%",]
|===
| `--force`
| Ignores disabled LDAP configuration
|===

Example:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:check-user robert
----

`ldap:check-user` will not run a check when it finds a disabled LDAP connection. This prevents users that exist on disabled LDAP connections from being marked as deleted. If you know for sure that the user you are searching for is not in one of the disabled connections and exists on an active connection, use the `--force` option to force a check of all active LDAP connections.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:check-user --force robert
----

== Create an Empty LDAP Configuration

Create an empty LDAP configuration.

[source,console,subs="attributes+"]
----
ldap:create-empty-config [<configID>]
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `configID`
| Create a configuration with the specified id
|===

Configurations that you create without assigning a <configID> are automatically assigned IDs.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:create-empty-config
   Created new configuration with configID 's01'
----

== List and View Your Configurations

You can list and view your configurations:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:show-config [options] [--] [<configID>]
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `configID`
| Will show the configuration of the specified id
|===

=== Options

[width="100%",cols="20%,70%",]
|===
| `--show-password`
| Show LDAP bind password

| `--output[=OUTPUT]`
| The output format to use (plain, json or json_pretty). [default: "plain"]
|===

==== Examples

If you omit the `configID`, all configuration ID's with their settings are listed:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:show-config
----

View the configuration for a single `configID`:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:show-config s01
----

== Delete an Existing LDAP Configuration

Deletes an existing LDAP configuration.

[source,console,subs="attributes+"]
----
 ldap:delete-config <configID>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `configID`
|  The configuration ID
|===

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:delete  s01
Deleted configuration with configID 's01'
----

== Invalidate LDAP Cache

This command invalidates the LDAP cache for all users:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:invalidate-cache
----

== Manipulate LDAP Configurations

This command manipulates LDAP configurations.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:set-config <configID> <configKey> <configValue>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `configID`
|  The configuration ID

| `configKey`
|  The configuration key

| `configValue`
|  The new configuration value
|===

If a `configKey` allows multiple entries like the key `ldapAttributesForUserSearch`, use semicolons without a whitespace to separate them.

This example sets search attributes:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:set-config s01 ldapAttributesForUserSearch "cn;givenname;sn;displayname;mail"
----

Available keys, along with default values for configValue, are listed in the table below.

[width="70%",cols=",",options="header",]
|===
| Configuration                 | Setting
| hasMemberOfFilterSupport      |
| hasPagedResultSupport         |
| homeFolderNamingRule          |
| lastJpegPhotoLookup           | 0
| ldapAgentName                 | cn=admin,dc=owncloudqa,dc=com
| ldapAgentPassword             | _*_
| ldapAttributesForGroupSearch  |
| ldapAttributesForUserSearch   |
| ldapBackupHost                |
| ldapBackupPort                |
| ldapBase                      | dc=owncloudqa,dc=com
| ldapBaseGroups                | dc=owncloudqa,dc=com
| ldapBaseUsers                 | dc=owncloudqa,dc=com
| ldapCacheTTL                  | 600
| ldapConfigurationActive       | 1
| ldapDynamicGroupMemberURL     |
| ldapEmailAttribute            |
| ldapExperiencedAdmin          | 0
| ldapExpertUUIDGroupAttr       |
| ldapExpertUUIDUserAttr        |
| ldapExpertUsernameAttr        |
| ldapGroupDisplayName          | cn
| ldapGroupFilter               |
| ldapGroupFilterMode           | 0
| ldapGroupFilterObjectclass    |
| ldapGroupMemberAssocAttr      | uniqueMember
| ldapHost                      | ldap://host
| ldapIgnoreNamingRules         |
| ldapLoginFilter               | (&((objectclass=inetOrgPerson))(uid=%uid))
| ldapLoginFilterAttributes     |
| ldapLoginFilterEmail          | 0
| ldapLoginFilterMode           | 0
| ldapLoginFilterUsername       | 1
| ldapNestedGroups              | 0
| ldapOverrideMainServer        |
| ldapPagingSize                | 500
| ldapPort                      | 389
| ldapQuotaAttribute            |
| ldapQuotaDefault              |
| ldapTLS                       | 0
| ldapUserDisplayName           | displayName
| ldapUserDisplayName2          |
| ldapUserFilter                | ((objectclass=inetOrgPerson))
| ldapUserFilterGroups          |
| ldapUserFilterMode            | 0
| ldapUserFilterObjectclass     | inetOrgPerson
| ldapUuidGroupAttribute        | auto
| ldapUuidUserAttribute         | auto
| turnOffCertCheck              | 0
| useMemberOfToDetectMembership | 1
|===

== Test Your Configuration

Tests whether your configuration is correct and can bind to the server.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:test-config <configID>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `configID`
|  The configuration ID
|===

Example:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ldap:test-config s01
The configuration is valid and the connection could be established!
----

== Set and Unset LDAP App Configurations

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set user_ldap updateAttributesInterval --value=7200
----

In the example above, the interval is being set to 7200 seconds.
Assuming the above example was used, the command would output the following:

[source,console]
----
Config value updateAttributesInterval for app user_ldap set to 7200
----

If you want to reset (or unset) the setting, then you can use the following command:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:delete user_ldap updateAttributesInterval
----

*Reuse Existing LDAP Accounts if Available*

If you want to allow new LDAP logins to attempt to reuse existing `oc_accounts` entries that match the resolved username attribute, and have backend set to `User_Proxy`, then set the `reuse_accounts` config setting to `yes`.

Below is an example of how to do so.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set user_ldap reuse_accounts --value="yes"
----

This functionality is valuable for several reasons; these are:

* It handles the situation of when admins mistakenly delete one or more user mappings, and subsequent logins then create new accounts.
* It allows auto-provisioned users with Shibboleth to be moved over to an LDAP server, but be able to continue using ownCloud.

[IMPORTANT]
====
This functionality will not work in the following situations:

. No user or group account exists with the supplied username.
. A user or group account exists, but it uses a different backend.
====
