= OAuth2

Marketplace URL: {oc-marketplace-url}/apps/oauth2[OAuth2]

Use these commands to configure OAuth2 clients via the OAuth2 app:

[source,console]
----
oauth2
  oauth2:add-client     Adds an OAuth2 client
  oauth2:list-clients   Lists OAuth2 clients
  oauth2:remove-client  Removes an OAuth2 client
  oauth2:modify-client  Modify OAuth2 client details
----

== Add a Client

=== Usage

[source,console]
----
oauth2:add-client <name> <client-id> <client-secret> <redirect-url> [<allow-sub-domains> [<trusted> [<force-trust>]]]
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `name`
| Name of the client - will be displayed in the authorization page to the user

| `client-id`
| Identifier of the client - used by the client during the implicit and authorization code flow

| `client-secret`
|  Secret of the client - used by the client during the authorization code flow

| `redirect-url`
| Redirect URL - used in the OAuth flows to post back tokens and authorization codes to the client

| `allow-sub-domains`
|  Defines if the redirect url is allowed to use sub-domains. Enter true or false [default: "false"]

| `trusted`
| Defines if the client is trusted. Enter true or false [default: "false"]

| `force-trust`
| Trust the client even if the redirect-url is localhost. [default: "false"]
|===

== List Clients

=== Usage

[source,console]
----
oauth2:list-clients [options]
----

=== Options

[width="100%",cols="20%,70%",]
|===
| `--output[=OUTPUT]`
|  The output format to use (plain, json or json_pretty). [default: "plain"]
|===

.Example Output
[source,text]
----
  - Desktop Client:
    - name: Desktop Client
    - redirect-url: http://localhost:*
    - client-id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
    - client-secret: UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh
    - allow-sub-domains: false
    - trusted: false
  - Android:
    - name: Android
    - redirect-url: oc://android.owncloud.com
    - client-id: e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD
    - client-secret: dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD
    - allow-sub-domains: false
    - trusted: false
  - iOS:
    - name: iOS
    - redirect-url: oc://ios.owncloud.com
    - client-id: mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1
    - client-secret: KFeFWWEZO9TkisIQzR3fo7hfiMXlOpaqP8CFuTbSHzV1TUuGECglPxpiVKJfOXIx
    - allow-sub-domains: false
    - trusted: false
----

== Modify Client Details

=== Usage

[source,console]
----
oauth2:modify-client <name> <key> <value>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `name`
| Name of client

| `key`
| Key to be changed. Valid keys are: +
`name`, `client-id`, `client-secret`, `redirect-url`, `allow-sub-domains`, `trusted`

| `value`
| The new value of the key.
|===

== Remove a Client

=== Usage

[source,console]
----
oauth2:remove-client <client-id>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `client-id`
| Identifier of the client - used by the client during the implicit and authorization code flow
|===
