= Collabora Online / Secure View

Marketplace URL: {oc-marketplace-url}/apps/richdocuments[Collabora Online]

Collabora Online allows you to work with all kinds of collabora office documents inside ownCloud for improved productivity. For details, see the
xref:enterprise/collaboration/collabora_secure_view.adoc[Collabora Online / Secure View] documentation.

`config:app` commands to configure the Collabora Online app.

[source,console]
----
 config:app:get|set
 richdocuments wopi_url            WOPI Server URL
 richdocuments secure_view_option  Enable Secure View
 richdocuments watermark_text      Watermark pattern displayed in the document
 richdocuments open_in_new_tab     Open documents in a new tab
 richdocuments secure_view_can_print_default    Define if documents can be printed or exported
 richdocuments secure_view_open_action_default  Enforce displaying the watermark by default
----

== App Configuration

All app configurations are set and queried with the `config:app` command set. The examples below set a value. To query a value use `config:app:get` and the corresponding key without any options or attributes. Note that values have to be set in single quotes.

== Define the WOPI Server URL

WOPI Server URL

This command sets the WOPI Server to `[IP/URL]:port` +
`[IP/URL]:port` can be any IP/URL plus the port on which the WOPI server can be accessed like:

- `a.b.c.d`
- `http://a.b.c.d:8098`
- `https://rd.yourdomain.com`
- ...

Adding the port is only necessary when not using standard ports.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set richdocuments wopi_url --value='[IP/URL]:port'
----

== Enable Secure View

Enable Secure View (possible values: true/false, default: false).

The following example command enables secure view globally on the system:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set richdocuments secure_view_option --value='true'
----

== Define the Watermark Pattern Displayed

A watermark pattern is displayed in the document when it is viewed. It can be an arbitrary string. The keyword \{viewer-email} will be replaced with the current user's email address in the document watermark. If an email address is not set, then the user's display name will be used.

The following example command sets the watermark pattern displayed in the document:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set richdocuments watermark_text --value='Restricted to \{viewer-email}'
----

== Open Documents in a New Tab

By default, documents will open in a new tab if not otherwise defined. You can change this behaviour with a command (possible values: true/false, default: false).

The following example command makes documents open in the same tab:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set richdocuments open_in_new_tab --value='false'
----

== Define the Print and Exporting Option

Enable documents in secure view mode to be printed and exported (possible values: true/false, default: false).

The following example command enables the option to globally print and export documents although secure view is enabled:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set secure_view_can_print_default --value='true'
----

== Enforce Displaying the Watermark

Open documents in secure view with watermark by default (possible values: true/false, default: false).

The following example command enables the option to globally enforce displaying the watermark when documents are viewed:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set richdocuments secure_view_open_action_default --value='true'
----

== Delete a Key or Change a Key

You can delete a key with the following example command:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:delete richdocuments secure_view_open_action_default
----

You can change a key with the following example command:

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set richdocuments secure_view_option --value='false'
----
