= Brute Force Protection
:page-noindex: yes

Marketplace URL: {oc-marketplace-url}/apps/brute_force_protection[Brute-Force Protection]

Use these commands to configure the Brute Force Protection app.
Parametrisation must be done with the `occ config` command set.
The combination of `uid` and `IP address` is used to trigger the ban.

== List the Current Settings

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:list brute_force_protection
----

== Set the Setting

To set a new value, use the command below and replace `<Key>` and value `<Value>` accordingly.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set brute_force_protection <Key> --value=<Value> --update-only
----

=== Fail Tolerance [attempts]

Number of wrong attempts to trigger the ban.

[width="80%",cols="30%,70%",]
|===
| Key     | `brute_force_protection_fail_tolerance`
| Default | 3
|===

=== Time Treshold [seconds]

Time in which the number of wrong attempts must occur to trigger the ban.

[width="80%",cols="30%,70%",]
|===
| Key     | `brute_force_protection_time_threshold`
| Default | 60
|===

=== Ban Period [seconds]

Time how long the ban will be active if triggered.

[width="80%",cols="30%,70%",]
|===
| Key     | `brute_force_protection_ban_period`
| Default | 300
|===
