= Ransomware Protection (Enterprise Edition only)
:page-noindex: yes

Marketplace URL: {oc-marketplace-url}/apps/ransomware_protection[Ransomware Protection]

Use these commands to help users recover from a Ransomware attack.
You can find more information about the application in xref:enterprise/security/ransomware-protection/index.adoc[the Ransomware Protection documentation].

== Command Description

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ransomguard:scan <timestamp> <user>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `<timestamp>` +
`<user>`          | Report all changes in a user's account, starting from timestamp.
|===

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ransomguard:restore <timestamp> <user>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `<timestamp>` +
`<user>`          | Revert all operations in a user account after a point in time.
|===

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ransomguard:lock <user>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `<user>` | Set a user account as read-only for ownCloud and other WebDAV clients when
malicious activity is suspected.
|===

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} ransomguard:unlock <user>
----

=== Arguments

[width="100%",cols="20%,70%",]
|===
| `<user>` | Unlock a user account after ransomware issues have been resolved.
|===
