= OCS Share API
:toc: right
:page-aliases: core/ocs-share-api.adoc
:endpoint-uri: /ocs/v1.php/apps/files_sharing/api/v1/shares/pending

== Introduction

The OCS Share API allows you to access the sharing API from outside over pre-defined OCS calls.
The base URL for all calls to the share API is: `{endpoint-uri}`.

== Local Shares

=== Get All Shares

Get all shares shared with a user.

[cols="20%,80%"]
|===
|*Endpoint* |`{endpoint-uri}`
|*Method* |GET
|===

==== Request Attributes

[cols="20%,15%,65%",options="header",]
|===
|Attribute
|Type
|Description

|`format`
|string
|sets the output format of the response.
Default value is `xml`.
Available options are `xml` and `json`.

|`path`
|string
|limit the shares to those in a specific path.

|`reshares`
|boolean
|returns not only the shares shared with the current user but all shares.

|`shared_with_me`
|string
|limits the returned shares to only those shared with the authenticating user.

|`state`
|string
a|limits the returned shares to only those with the specified state.
Available options are `accepted`, `all`, `declined`, `pending`, and `rejected`.

NOTE: This attribute is only valid when `shared_with_me` is set.

NOTE: `declined` and `rejected` are interchangeable.

|`subfiles`
|boolean
|returns all shares within a folder, given that path defines a folder.
This option requires the path option to be specified.
|===

==== Status Codes

[cols="20%,80%",options="header",]
|===
| Code | Description
| 100 | Successful.
| 400 | Not a directory (if the `subfile' argument was used).
| 404 | Couldn't fetch shares or file doesn't exist.
| 997 | Unauthorised.
|===

==== Example Request Response Payloads

If the user that you're connecting with is not authorized, then you will see output similar to the following:

[source,xml]
----
include::{examplesdir}core/scripts/responses/not-authorised-response.xml[]
----

If the user that you're connecting with _is_ authorized, then you will see output similar to the following:

[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/get-all-shares-success-no-shares.xml[]
----

[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/list-share-details-failure.xml[]
----

.Files shared with the current user in XML format.
[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/list-share-details-success.xml[]
----

.Files shared with the current user in JSON format.
[source,json]
----
include::{examplesdir}core/scripts/responses/shares/list-share-details-success.json[]
----

==== Code Example

ifeval::["{format}" == "html"]
[tabs]
====
Curl::
+
--
[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/list-share-details.sh[]
----
--
PHP::
+
--
[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/list-share-details.php[]
----
--
Ruby::
+
--
[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/list-share-details.rb[]
----
--
Go::
+
--
[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/list-share-details.go[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
===== Curl

[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/list-share-details.sh[]
----

===== PHP

[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/list-share-details.php[]
----

===== Ruby

[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/list-share-details.rb[]
----

===== Go

[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/list-share-details.go[]
----
endif::[]

=== Get Information About A Known Share

[cols="20%,80%"]
|===
|Endpoint |`{endpoint-uri}/<share_id>`
|Method |GET
|===

==== Supported Attributes

[cols=",,",options="header",]
|===
| Attribute | Type | Description
| share_id | int | The share's unique id
|===

==== Response Status Codes

[cols="20%,80%",options="header",]
|===
| Code | Description
| 100 | Successful
| 404 | Share doesn't exist
|===

==== Code Example

ifeval::["{format}" == "html"]
[tabs]
====
Curl::
+
--
[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/get-share-info.sh[]
----
--
PHP::
+
--
[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/get-share-info.php[]
----
--
Ruby::
+
--
[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/get-share-info.rb[]
----
--
Go::
+
--
[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/get-share-info.go[]
----
--
Kotlin::
+
--
[source,kotlin,subs="attributes+"]
----
include::{examplesdir}core/scripts/kotlin/get-share-info.kt[]
----
--
Java::
+
--
[source,java,subs="attributes+"]
----
include::{examplesdir}core/scripts/java/get-share-info.java[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
===== Curl

[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/get-share-info.sh[]
----

===== PHP

[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/get-share-info.php[]
----

===== Ruby

[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/get-share-info.rb[]
----

===== Go

[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/get-share-info.go[]
----

===== Kotlin

[source,kotlin,subs="attributes+"]
----
include::{examplesdir}core/scripts/kotlin/get-share-info.kt[]
----

===== Java

[source,java,subs="attributes+"]
----
include::{examplesdir}core/scripts/java/get-share-info.java[]
----
endif::[]

NOTE: The Java and Kotlin examples use https://github.com/square/okhttp[the square/okhttp library].

==== Example Response Payloads

ifeval::["{format}" == "html"]
[tabs]
====
Success::
+
--
[source,console]
----
include::{examplesdir}core/scripts/responses/shares/get-share-info-success.xml[]
----
--
Failure::
+
--
[source,console]
----
include::{examplesdir}core/scripts/responses/shares/get-share-info-failure.xml[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
===== Success

[source,console]
----
include::{examplesdir}core/scripts/responses/shares/get-share-info-success.xml[]
----

===== Failure

--
[source,console]
----
include::{examplesdir}core/scripts/responses/shares/get-share-info-failure.xml[]
----
endif::[]

==== Response Attributes

For details about the elements in the XML response payload please refer to the Response Attributes section of xref:response-attributes-1[the Create a New Share section] below.

=== Accept a Pending Share

[cols="20%,80%"]
|===
|Endpoint |`{endpoint-uri}/<share_id>`
|Method |POST
|===

==== Request Attributes

[cols="20%,15%,65%",options="header",]
|===
|Attribute
|Type
|Description

|share id
|integer
|the id of the pending share to accept.
Pending share ids are available in xref:get-all-shares[the get all shares response].
|===

==== Status Codes

[cols="20%,80%",options="header",]
|===
|Code
|Description

|200
a|
* Pending share successfully accepted.
* Share doesn't exist.
|===

==== Example Request Response Payloads

ifeval::["{format}" == "html"]
[tabs]
====
Success::
+
--
.Pending share was successfully accepted
[source,console]
----
include::{examplesdir}core/scripts/responses/shares/accept-pending-share-success.xml[]
----
--
Failure::
+
--
.The share id does not exist.
[source,console]
----
include::{examplesdir}core/scripts/responses/shares/accept-pending-share-failure.xml[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
===== Success

.Pending share was successfully accepted
[source,console]
----
include::{examplesdir}core/scripts/responses/shares/accept-pending-share-success.xml[]
----

===== Failure

.The share id does not exist.
[source,console]
----
include::{examplesdir}core/scripts/responses/shares/accept-pending-share-failure.xml[]
----
endif::[]

==== Code Example

ifeval::["{format}" == "html"]
[tabs]
====
Curl::
+
--
[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/accept-pending-share.sh[]
----
--
PHP::
+
--
[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/accept-pending-share.php[]
----
--
Ruby::
+
--
[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/accept-pending-share.rb[]
----
--
Go::
+
--
[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/accept-pending-share.go[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
===== Curl

[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/accept-pending-share.sh[]
----

===== PHP

[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/accept-pending-share.php[]
----

===== Ruby

[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/accept-pending-share.rb[]
----

===== Go

[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/accept-pending-share.go[]
----
endif::[]

=== Decline a Pending Share

[cols="20%,80%"]
|===
|Endpoint |`{endpoint-uri}/<share_id>`
|Method |DELETE
|===

==== Request Attributes

[cols="20%,15%,65%",options="header",]
|===
|Attribute
|Type
|Description

|share id
|integer
|the id of the pending share to decline.
Pending share ids are available in xref:get-all-shares[the get all shares response].
|===

==== Status Codes

[cols=",",options="header",]
|===
|Code
|Description

|200
a|
* Pending share successfully declined (one or more times).
* Share doesn't exist.
|===

==== Example Request Response Payloads

.A pending share is successfully declined.
[source,xml]
----
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
----

.The share id does not exist or the pending share has already been declined.
[source,xml]
----
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Wrong share ID, share doesn't exist</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
----

==== Code Example

ifeval::["{format}" == "html"]
[tabs]
====
Curl::
+
--
[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/decline-pending-share.sh[]
----
--
PHP::
+
--
[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/decline-pending-share.php[]
----
--
Ruby::
+
--
[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/decline-pending-share.rb[]
----
--
Go::
+
--
[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/decline-pending-share.go[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
===== Curl

[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/decline-pending-share.sh[]
----
--
===== PHP

[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/decline-pending-share.php[]
----

===== Ruby

[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/decline-pending-share.rb[]
----

===== Go

[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/decline-pending-share.go[]
----
endif::[]

=== Create A New Share

Share an existing file or folder with a user, a group, or as a public link.

[cols="20%,80%"]
|===
|Endpoint |`{endpoint-uri}`
|Method |POST
|===

==== Function Arguments

[width="100%",cols="27%,11%,62%",options="header",]
|===
| Argument | Type | Description
| name | string | A (human-readable) name for the share, which can be up to
64 characters in length.

| path | string | The path to the file or folder which should be shared.

| shareType | int a|
The type of the share. This can be one of:

* 0 = user
* 1 = group
* 3 = public link
* 6 = federated cloud share

| shareWith | string | The user or group id with which the file should be shared.

| publicUpload | boolean | Whether to allow public upload to a public link shared folder.

| password | string | The password to protect the public link share with.

| permissions | int
a|
The permissions to set on the share.

* 1 = read (default for public link shares);
* 2 = update;
* 4 = create;
* 8 = delete;
* 15 = read/write;
* 16 = share;
* 31 = All permissions.

| expireDate | string | An expire date for the user, group or public link share. This
argument expects a date string in the following format `'YYYY-MM-DD'`.

| attributes
| array
| Contain a set of one or more permissions to set for a share.
The list of available permissions can be obtained from a request to xref:core/apis/roles-api.adoc[the Roles API].
|===

[NOTE]
====
Things to remember about public link shares

* Files will only ever have the *read* permission set
* Folders will have *read*, *update*, *create*, and *delete* set
* Public link shares *cannot* be shared with users and groups
* Public link shares are not available if public link sharing is disabled by the administrator

*Mandatory Fields*

`shareType`, `path` and `shareWith` are mandatory if `shareType` is set to 0 or 1
====

==== Returns

XML containing the share ID (int) of the newly created share

==== Status Codes

[cols="20%,80%",options="header",]
|===
| Code | Description
| 100 | Successful
| 400 | Unknown share type
| 403 | Public upload was disabled by the admin
| 404 | File or folder couldn't be shared
|===

==== Code Example

ifeval::["{format}" == "html"]
[tabs]
====
Curl::
+
--
[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/create-share.sh[]
----
--
PHP::
+
--
[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/create-share.php[]
----
--
Ruby::
+
--
[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/create-share.rb[]
----
--
Go::
+
--
[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/create-share.go[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
===== Curl

[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/create-share.sh[]
----

===== PHP

[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/create-share.php[]
----

===== Ruby

[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/create-share.rb[]
----

===== Go

[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/create-share.go[]
----
endif::[]

==== Example Request Response Payloads

Failure

[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/create-share-failure.xml[]
----

Success

[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/create-share-success.xml[]
----

==== Response Attributes

[width="100%",cols="27%,11%,62%",options="header",]
|===
| Argument | Type | Description
| id | int | The share's unique id.

| share_type | int a|
The share's type. This can be one of:

* 0 = user
* 1 = group
* 3 = public link
* 6 = federated cloud share

| uid_owner | string | The username of the owner of the share.

| displayname_owner | string | The display name of the owner of the share.

| permissions | octal a |
The permission attribute set on the file. Options are:

* 1 = Read
* 2 = Update
* 4 = Create
* 8 = Delete
* 16 = Share
* 31 = All permissions

The default is 31, and for public link shares is 1.

| stime | int | The UNIX timestamp when the share was created.

| parent | int | The UNIX timestamp when the share was created.

| expiration | string | The UNIX timestamp when the share expires.

| token | string | The public link to the item being shared.

| uid_file_owner | string | The unique id of the user that owns the file or
folder being shared.

| displayname_file_owner | string | The display name of the user that owns
the file or folder being shared.

| path | string | The path to the shared file or folder.

| item_type | string | The type of the object being shared. This can be one
of file or folder.

| mimetype | string | The https://tools.ietf.org/html/rfc2045[RFC-compliant mimetype] of the file.

| storage_id | string |

| storage | int |

| item_source | int | The unique node id of the item being shared.

| file_source | int | The unique node id of the item being shared. For
legacy reasons item_source and file_source attributes have the same value.

| file_parent | int | The unique node id of the parent node of the item being shared.

| file_target | int | The name of the shared file.

| share_with | string | The uid of the receiver of the file. This is either
a GID (group id) if it is being shared with a group or a UID (user id)
if the share is shared with a user.

| share_with_displayname | string | The display name of the receiver of the file.

| url | string |

| mail_send | int | Whether the recipient was notified, by mail, about the
share being shared with them.

| name | string | A (human-readable) name for the share, which can be up to
64 characters in length
|===

=== Delete A Share

Remove the given share.

[cols="20%,80%"]
|===
|Endpoint |`{endpoint-uri}/<share_id>`
|Method |DELETE
|===

[cols=",,",options="header",]
|===
| Attribute | Type | Description
| share_id | int | The share's unique id
|===

==== Status Codes

[cols="20%,80%",options="header",]
|===
| Code | Description
| 100 | Successful
| 404 | Share couldn't be deleted
|===

==== Code Example

ifeval::["{format}" == "html"]
[tabs]
====
Curl::
+
--
[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/delete-share.sh[]
----
--
PHP::
+
--
[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/delete-share.php[]
----
--
Ruby::
+
--
[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/delete-share.rb[]
----
--
Go::
+
--
[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/delete-share.go[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
Curl
+
--
[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/delete-share.sh[]
----
--
PHP::
+
--
[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/delete-share.php[]
----
--
Ruby::
+
--
[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/delete-share.rb[]
----
--
Go::
+
--
[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/delete-share.go[]
----
endif::[]

==== Example Request Response Payloads

Failure

[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/delete-share-success.xml[]
----

Success

[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/delete-share-failure.xml[]
----

=== Update Share

Update a given share.
Only one value can be updated per request.

[cols=",,"]
|===
|Endpoint |`{endpoint-uri}/<share_id>`
|Method |PUT
|===

==== Request Arguments

[cols=",,",options="header",]
|===
| Argument | Type | Description
| name | string | A (human-readable) name for the share, which can
| | | be up to 64 characters in length
| share_id | int | The share's unique id
| permissions | int | Update permissions
| | | (see xref:create-a-new-share[the create share section] above)
| password | string | Updated password for a public link share
| publicUpload | boolean | Enable (true) / disable (false)
| | | public upload for public link shares.
| expireDate | string | Set an expire date for the user, group or public link share.
| | | This argument expects a well-formatted date string,
| | | such as: `YYYY-MM-DD'
|===

NOTE: Only one of the update parameters can be specified at once.

==== Status Codes

[cols=",",options="header",]
|===
| Code | Description
| 100 | Successful
| 400 | Wrong or no update parameter given
| 403 | Public upload disabled by the admin
| 404 | Couldn't update share
|===

==== Code Example

ifeval::["{format}" == "html"]
[tabs]
====
Curl::
+
--
[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/update-share.sh[]
----
--
PHP::
+
--
[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/update-share.php[]
----
--
Ruby::
+
--
[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/update-share.rb[]
----
--
Go::
+
--
[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/update-share.go[]
----
--
====
endif::[]

ifeval::["{format}" == "pdf"]
===== Curl

[source,console,subs="attributes+"]
----
include::{examplesdir}core/scripts/curl/update-share.sh[]
----

===== PHP

[source,php,subs="attributes+"]
----
include::{examplesdir}core/scripts/php/update-share.php[]
----

===== Ruby

[source,ruby,subs="attributes+"]
----
include::{examplesdir}core/scripts/ruby/update-share.rb[]
----

===== Go

[source,go,subs="attributes+"]
----
include::{examplesdir}core/scripts/go/update-share.go[]
----
endif::[]

==== Example Request Response Payloads

Failure

[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/update-share-failure.xml[]
----

Success

[source,xml]
----
include::{examplesdir}core/scripts/responses/shares/update-share-success.xml[]
----

== Federated Cloud Shares

Both the sending and the receiving instance need to have federated cloud sharing enabled and configured.
See xref:admin_manual:configuration/files/federated_cloud_sharing_configuration.adoc[Configuring Federated Cloud Sharing].

=== Create A New Federated Cloud Share

Creating a federated cloud share can be done via the local share
endpoint, using (int) 6 as a shareType and the
https://owncloud.org/federation/[Federated Cloud ID] of the share
recipient as shareWith. See xref:create-a-new-share[Create a new Share] for more information.

=== List Accepted Federated Cloud Shares

Get all federated cloud shares the user has accepted.

* Syntax: /remote_shares
* Method: GET

==== Returns

XML with all accepted federated cloud shares

==== Status Codes

[cols=",",options="header",]
|===
| Code | Description
| 100 | Successful
|===

=== Get Information About A Known Federated Cloud Share

Get information about a given received federated cloud share that was sent from a remote instance.

* Syntax: /remote_shares/<share_id>
* Method: GET

[cols=",,",options="header",]
|===
| Attribute | Type | Description
| share_id | int | The share id as listed in the id field
| | | in the `remote_shares` list
|===

==== Returns

XML with the share information

==== Status Codes

[cols=",",options="header",]
|===
| Code | Description
| 100 | Successful
| 404 | Share doesn't exist
|===

=== Delete An Accepted Federated Cloud Share

Locally delete a received federated cloud share that was sent from a remote instance.

* Syntax: /remote_shares/<share_id>
* Method: DELETE

[cols=",,",options="header",]
|===
| Attribute | Type | Description
| share_id | int | The share id as listed in the id field
| | | in the `remote_shares` list
|===

==== Status Codes

[cols=",",options="header",]
|===
| Code | Description
| 100 | Successful
| 404 | Share doesn't exist
|===

=== List Pending Federated Cloud Shares

Get all pending federated cloud shares the user has received.

* Syntax: /remote_shares/pending
* Method: GET

==== Returns

XML with all pending federated cloud shares

==== Status Codes

[cols=",",options="header",]
|===
| Code | Description
| 100 | Successful
| 404 | Share doesn't exist
|===

=== Accept a Pending Federated Cloud Share

Locally accept a received federated cloud share that was sent from a remote instance.

* Syntax: /remote_shares/pending/*<share_id>*
* Method: POST

[cols=",,",options="header",]
|===
| Attribute | Type | Description
| share_id | int | The share id as listed in the id field
| | | in the `remote_shares/pending` list
|===

==== Status Codes

[cols=",",options="header",]
|===
| Code | Description
| 100 | Successful
| 404 | Share doesn't exist
|===

=== Decline a Pending Federated Cloud Share

Locally decline a received federated cloud share that was sent from a remote instance.

* Syntax: /remote_shares/pending/<share_id>
* Method: DELETE

[cols=",,",options="header",]
|===
| Attribute | Type | Description
| share_id | int | The share id as listed in the id field
| | | in the `remote_shares/pending` list
|===

==== Status Codes

[cols=",",options="header",]
|===
| Code | Description
| 100 | Successful
| 404 | Share doesn't exist
|===
