= OCS Recipient API
:toc: right
:page-aliases: core/ocs-recipient-api.adoc

== Introduction

The OCS Recipient API is a new OCS endpoint that is used by the share
dialog autocomplete process, when you pick a user or group to share to.

The base URL for all calls to the share API is:
_<owncloud_base_url>/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json_

The result is divided into a blog with `exact` and non exact matches. All results that match
the string provided by the `search` parameter exactly will be listed in the `exact` block. All other
results will be listed outside of it.

== Get Shares Recipients

Get all share recipients for the provided search term.

* Syntax: /sharees
* Method: GET

=== Query Attributes

[cols=",,,,",options="header",]
|=======================================================================
| Attribute | Type | Description | Required | Default
| format | string | The response format. Can be either `xml` or `json` |
| `xml`

| search | string | The search string | |

| itemType | string | The type which is shared. | Yes |

| | | Can be either `file` or `folder` | |

| shareType | integer | Any one of: | |

| | | - 0 (user) | |

| | | - 1 (group) | |

| | | - 6 (remote) | |

| page | integer | The page number in the results to be returned | | 1

| perPage | integer | The number of items per page | Yes | 200
|=======================================================================

=== Status Codes

[cols=",",options="header",]
|============================================
| Code | Description
| 100 | Successful
| 400 | Failure due to invalid query parameters
|============================================

=== Example Request Response Payloads
If the users admin, user1, user2 and the groups group1 and group2 were registerd on a server.

[source,json]
----
include::{examplesdir}core/scripts/responses/recipients/response-success.json[]
----

The same request with xml body.

[source,xml]
----
include::{examplesdir}core/scripts/responses/recipients/response-success.xml[]
----


