Below are the steps done for testing:

    encrypt the fs with user-keys encryption and create 2 users admin and user1
    Login as user1 and logout.
    Login as admin and create a file publink.txt. Add some contents to the file.
    Create public link share of publink.txt.
    Execute the steps to decrypt the fs ( captured the log from terminal) :

➜  owncloud3 git:(master) ✗ ./occ maintenance:singleuser --on; ./occ encryption:decrypt-all; ./occ encryption:disable; ./occ app:disable encryption;
Cannot load Xdebug - it was already loaded
Single user mode enabled
Cannot load Xdebug - it was already loaded
Disable server side encryption... done.


You are about to start to decrypt all files stored in your ownCloud.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Do you really want to continue? (y/n) y
prepare encryption modules...
 done.


 starting to decrypt files...
 [->--------------------------]
Prepare "Default encryption module"

You can only decrypt the users files if you know
the users password or if he activated the recovery key.

Do you want to use the user: admin login password to decrypt all files? (y/n) y
 decrypt files for user admin (1 of 2): /admin/files/welcome.txt
 [--->------------------------]
Prepare "Default encryption module"

You can only decrypt the users files if you know
the users password or if he activated the recovery key.

Do you want to use the user: user1 login password to decrypt all files? (y/n) y
 decrypt files for user user1 (2 of 2): /user1/files/welcome.txt
 [---->-----------------------]

 starting to decrypt files... finished
 [============================]


all files could be decrypted successfully!
Cannot load Xdebug - it was already loaded
Encryption is already disabled
Cannot load Xdebug - it was already loaded
encryption disabled
➜  owncloud3 git:(master) ✗

Now modify the db and remove files_encryption folder as shown below ( I use sqlite ):

➜  owncloud3 git:(master) ✗ sqlite3 data/owncloud.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from oc_appconfig where appid='encryption';
encryption|recoveryKeyId|recoveryKey_9cbde1a3
encryption|publicShareKeyId|pubShare_9cbde1a3
encryption|masterKeyId|master_9cbde1a3
encryption|installed_version|1.3.1
encryption|types|filesystem
encryption|enabled|no
encryption|userSpecificKey|1
sqlite> delete from oc_appconfig where appid='encryption';
sqlite> select * from oc_appconfig where appid='encryption';
sqlite>
➜  owncloud3 git:(master) ✗ find . -name files_encryption
./data/files_encryption
./data/user1/files_encryption
./data/admin/files_encryption
➜  owncloud3 git:(master) ✗ rm -fr ./data/files_encryption ./data/user1/files_encryption ./data/admin/files_encryption
➜  owncloud3 git:(master)

After decrypting, try to encrypt the fs again with masterkey:

➜  owncloud3 git:(master) ✗ ./occ app:enable encryption; ./occ encryption:enable; ./occ encryption:select-encryption-type masterkey -y; ./occ encryption:encrypt-all; ./occ maintenance:singleuser --off
Cannot load Xdebug - it was already loaded
encryption enabled
Cannot load Xdebug - it was already loaded
Encryption enabled

Default module: OC_DEFAULT_MODULE
Cannot load Xdebug - it was already loaded
Master key successfully enabled.
Cannot load Xdebug - it was already loaded


You are about to encrypt all files stored in your ownCloud installation.
Depending on the number of available files, and their size, this may take quite some time.
Please ensure that no user accesses their files during this time!
Note: The encryption module you use determines which files get encrypted.

Do you really want to continue? (y/n) y


Encrypt all files with the Default encryption module
====================================================


Use master key to encrypt all files.


Start to encrypt users files
----------------------------



 all files encrypted
 [============================]

Cannot load Xdebug - it was already loaded
Single user mode disabled
➜  owncloBelow are the steps done for testing:

    encrypt the fs with user-keys encryption and create 2 users admin and user1
    Login as user1 and logout.
    Login as admin and create a file publink.txt. Add some contents to the file.
    Create public link share of publink.txt.
    Execute the steps to decrypt the fs ( captured the log from terminal) :

➜  owncloud3 git:(master) ✗ ./occ maintenance:singleuser --on; ./occ encryption:decrypt-all; ./occ encryption:disable; ./occ app:disable encryption;
Cannot load Xdebug - it was already loaded
Single user mode enabled
Cannot load Xdebug - it was already loaded
Disable server side encryption... done.


You are about to start to decrypt all files stored in your ownCloud.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Do you really want to continue? (y/n) y
prepare encryption modules...
 done.


 starting to decrypt files...
 [->--------------------------]
Prepare "Default encryption module"

You can only decrypt the users files if you know
the users password or if he activated the recovery key.

Do you want to use the user: admin login password to decrypt all files? (y/n) y
 decrypt files for user admin (1 of 2): /admin/files/welcome.txt
 [--->------------------------]
Prepare "Default encryption module"

You can only decrypt the users files if you know
the users password or if he activated the recovery key.

Do you want to use the user: user1 login password to decrypt all files? (y/n) y
 decrypt files for user user1 (2 of 2): /user1/files/welcome.txt
 [---->-----------------------]

 starting to decrypt files... finished
 [============================]


all files could be decrypted successfully!
Cannot load Xdebug - it was already loaded
Encryption is already disabled
Cannot load Xdebug - it was already loaded
encryption disabled
➜  owncloud3 git:(master) ✗

Now modify the db and remove files_encryption folder as shown below ( I use sqlite ):

➜  owncloud3 git:(master) ✗ sqlite3 data/owncloud.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from oc_appconfig where appid='encryption';
encryption|recoveryKeyId|recoveryKey_9cbde1a3
encryption|publicShareKeyId|pubShare_9cbde1a3
encryption|masterKeyId|master_9cbde1a3
encryption|installed_version|1.3.1
encryption|types|filesystem
encryption|enabled|no
encryption|userSpecificKey|1
sqlite> delete from oc_appconfig where appid='encryption';
sqlite> select * from oc_appconfig where appid='encryption';
sqlite>
➜  owncloud3 git:(master) ✗ find . -name files_encryption
./data/files_encryption
./data/user1/files_encryption
./data/admin/files_encryption
➜  owncloud3 git:(master) ✗ rm -fr ./data/files_encryption ./data/user1/files_encryption ./data/admin/files_encryption
➜  owncloud3 git:(master)

After decrypting, try to encrypt the fs again with masterkey:

➜  owncloud3 git:(master) ✗ ./occ app:enable encryption; ./occ encryption:enable; ./occ encryption:select-encryption-type masterkey -y; ./occ encryption:encrypt-all; ./occ maintenance:singleuser --off
Cannot load Xdebug - it was already loaded
encryption enabled
Cannot load Xdebug - it was already loaded
Encryption enabled

Default module: OC_DEFAULT_MODULE
Cannot load Xdebug - it was already loaded
Master key successfully enabled.
Cannot load Xdebug - it was already loaded


You are about to encrypt all files stored in your ownCloud installation.
Depending on the number of available files, and their size, this may take quite some time.
Please ensure that no user accesses their files during this time!
Note: The encryption module you use determines which files get encrypted.

Do you really want to continue? (y/n) y


Encrypt all files with the Default encryption module
====================================================


Use master key to encrypt all files.


Start to encrypt users files
----------------------------



 all files encrypted
 [============================]

Cannot load Xdebug - it was already loaded
Single user mode disabled
➜  owncloud3 git:(master) ✗

After this, try to reload the web page and

    The files should be accessible
    The public link share should be visible as share.

To verify in the db:

➜  owncloud3 git:(master) ✗ sqlite3 data/owncloud.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from oc_appconfig where appid='encryption';
encryption|recoveryKeyId|recoveryKey_73facda6
encryption|publicShareKeyId|pubShare_73facda6
encryption|masterKeyId|master_73facda6
encryption|installed_version|1.3.1
encryption|types|filesystem
encryption|enabled|yes
encryption|useMasterKey|1
sqlite>
➜  owncloud3 git:(master) ✗

Also cat the file publink.txt it should be encrypted again.
ud3 git:(master) ✗

After this, try to reload the web page and

    The files should be accessible
    The public link share should be visible as share.

To verify in the db:

➜  owncloud3 git:(master) ✗ sqlite3 data/owncloud.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from oc_appconfig where appid='encryption';
encryption|recoveryKeyId|recoveryKey_73facda6
encryption|publicShareKeyId|pubShare_73facda6
encryption|masterKeyId|master_73facda6
encryption|installed_version|1.3.1
encryption|types|filesystem
encryption|enabled|yes
encryption|useMasterKey|1
sqlite>
➜  owncloud3 git:(master) ✗

Also cat the file publink.txt it should be encrypted again.
