= Migrating from user encryption to master encryption

Thommie Rother admin@netzwissen.de
(based on work by sharidas), v1.2, 8.11.2018

NOTE: ToDo: test with MariaDB/MySQL instead of sqlite

== Why should I move away from user encryption

NOTE: User-key encryption is planned to be removed from Owncloud in the near future. For new installations, server-wide encryption with master key is the recommended setup.

With user encryption, all files stored in the Owncloud data repository are encrypted with a key based on the users login password. Files are decrypted in the web interface or during file transfer with the owncloud client. In the web interface and during transport, the protection is delivered from the https protocol.

With master key, a general encryption key is used for the data of all users on the same Owncloud server. Thus the users have to trust the administrators and operators of the Owncloud server. From the user perspective, the user encryption is a bit "more save" than a server-wide encryption, as there is no other person who can gain access to their files. But this also has some major disadvantages:

* if a login password is lost, files can not be recovered directly from the owncloud server
* encrypted files can not be shared with other users based on group permissions (share with group). Instead, you have to create a share for each indiviudal user

IMPORTANT: A Server-wide decryption of all user files is only possible if all users have set the option of "recovery key" during the initial configuration of their account. Otherwise the only way is to save the (decrypted) files on a local machine and upload them again to another Owncloud instance with server-wide encryption.

== Prepare the Test-System

Prerequisites:

. Owncloud 10.x with user-key encryption and active recovery key
. create 2 users admin and user1
. Login as user1 and logout.
. Login as admin and create a file publink.txt. Add some contents to the file.
. Create public link share of publink.txt.
. Execute the steps to decrypt the fs

=== Decryption (with file recovery key)

Switch to admin single mode

 ./occ maintenance:singleuser --on

Start the decryption

 ./occ encryption:decrypt-all

 Disable encryption
  ./occ encryption:disable

  ./occ app:disable encryption;

=== Encrypt again (server-wide key)

IMPORTANT: It will depend on the encryption module and your setup if this is possible. Depending on the number and size of your files this can take some time. Please make sure that no user access his files during this process!

 Do you want to use the user: admin login password to decrypt all files? (y/n) y
 decrypt files for user admin (1 of 2):
 /admin/files/welcome.txt

Now modify the db and remove files_encryption folder as shown below ( I use sqlite ):

 sqlite> select * from oc_appconfig where appid='encryption';
 encryption|recoveryKeyId|recoveryKey_9cbde1a3
 encryption|publicShareKeyId|pubShare_9cbde1a3
 encryption|masterKeyId|master_9cbde1a3
 encryption|installed_version|1.3.1
 encryption|types|filesystem
 encryption|enabled|no
 encryption|userSpecificKey|1
 sqlite> delete from oc_appconfig where appid='encryption';
 sqlite> select * from oc_appconfig where appid='encryption';
 sqlite>

 find . -name files_encryption
 ./data/files_encryption
 ./data/user1/files_encryption
 ./data/admin/files_encryption

 rm -fr ./data/files_encryption ./data/user1/files_encryption ./data/admin/files_encryption

After decrypting, try to encrypt the fs again with masterkey:

 ./occ app:enable encryption;
 ./occ encryption:enable;
 ./occ encryption:select-encryption-type masterkey -y
 ./occ encryption:encrypt-all;
 ./occ maintenance:singleuser --off

You are about to encrypt all files stored in your ownCloud installation. Depending on the number of available files, and their size, this may take quite some time. Please ensure that no user accesses their files during this time! The encryption module you use determines which files get encrypted. After this, try to reload the web page and

- The files should be accessible
- The public link share should be visible as share.

To verify in the db:

 sqlite3 data/owncloud.db
 sqlite> select * from oc_appconfig where appid='encryption';
 encryption|recoveryKeyId|recoveryKey_73facda6
 encryption|publicShareKeyId|pubShare_73facda6
 encryption|masterKeyId|master_73facda6
 encryption|installed_version|1.3.1
 encryption|types|filesystem
 encryption|enabled|yes
 encryption|useMasterKey|1
 sqlite>

Also cat the file publink.txt it should be encrypted again.
