= Installation
:page-aliases: go/admin-install.adoc

You can install ownCloud in multiple ways, here are our trusted guides:

== xref:installation/manual_installation/index.adoc[Manual Installation]

This is a thorough guide to installing ownCloud, containing all the information needed for the prerequisites, the dependencies, the actual installation and the configuration afterwards.

== xref:installation/docker/index.adoc[Installing With Docker]

This guide will show you how to install ownCloud with Docker Compose using our YAML file.

== xref:installation/quick_guides/index.adoc[Example Installation on Ubuntu]

This is an example installation on an Ubuntu Server. This guide takes you from a clean Ubuntu server to a finished ownCloud installation in the minimal steps required. All commands are written down and are easy to copy and paste in to your terminal.

== xref:installation/linux_packetmanager_install.adoc[Linux Package Manager]

This guide shows you how to install ownCloud with the Ubuntu Package Manager.
