= Server Preparation for Ubuntu 18.04
:keywords: ubuntu, ubuntu 18.04, apache2, php-fpm, php, libsodium, mcrypt
:description: If your Ubuntu 18.04 server is a bare-minimum installation, follow this preparation guide to get it ready to manually install ownCloud.
:toc: right
:toclevels: 1
:auth-unix-socket-url: https://mariadb.com/kb/en/library/authentication-plugin-unix-socket/
:disabling-thp-url: https://stackoverflow.com/questions/48743100/why-thp-transparent-huge-pages-are-not-recommended-for-databases-like-oracle-a
:discover-samba-hosts-url: https://ubuntuforums.org/showthread.php?t=2384959
:install-mariadb-latest-url: https://downloads.mariadb.org/mariadb/repositories/#
:mcrypt-link-url: https://websiteforstudents.com/install-php-7-2-mcrypt-module-on-ubuntu-18-04-lts/
:mcrypt-pecl-url: https://pecl.php.net/package/mcrypt
:overriding-vendor-settings-url: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
:transport-huge-pages-url: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/performance_tuning_guide/s-memory-transhuge
:iscsi_initiator-url: https://help.ubuntu.com/lts/serverguide/iscsi-initiator.html
:ondrej-php-url: https://launchpad.net/~ondrej/+archive/ubuntu/php

== Introduction

The target audience for this document is more sophisticated admins with additional needs and setup scenarios.
Ubuntu 18.04, by design, only provides PHP 7.2.
Because PHP 7.2 security support ends in November 2020, you may want to to consider using PHP 7.3.
If you want to install the PHP 7.3 package and other required PHP extensions for PHP 7.3 for Ubuntu 18.04,
you need to use the well known, custom, PPA {ondrej-php-url}[ondrej/php].
Independent of the PHP version used, all other items, such as installing extensions or comments, and notes,
remain the same.

== Apache Web Server and PHP

The following command installs the Apache web server and PHP.

[source,console]
----
sudo apt install php libapache2-mod-php apache2
----

== Common Prerequisites

[source,console]
----
# Applications suggested for the use with ownCloud
sudo apt install smbclient
sudo apt install redis-server

# Applications needed for the use with ownCloud
sudo apt install unzip
sudo apt install openssl

# PHP extensions needed to use ownCloud
sudo apt install php-mysql php-mbstring php-gettext php-intl php-redis \
     php-imagick php-igbinary php-gmp php-bcmath php-curl php-gd php-zip \
     php-imap php-ldap php-bz2 php-phpseclib
----

== Useful Commands For Managing PHP Extensions 

=== List Enabled PHP Extensions
 
If you want to retrieve a list of enabled PHP extensions run following command:

[source,console]
----
ls `php -i | grep "^extension_dir" | sed -e 's/.*=> //'`
----

=== Enabling and Disabling PHP Extensions

To enable or disable a PHP extension, use the commands `phpenmod` or `phpdismod`.

Example:
[source,console]
----
sudo phpenmod php-ldap
# or
sudo phpdismod php-ldap
----

== Exif Library

This library _should_ already be part of PHP 7.2.
However, you can check if it is by running the following command.

[source,console]
----
grep -q -P 'EXIF Support => enabled' <(php -i) && echo "Exif is installed and enabled"
----

== Notes for PHP Library phpseclib

phpseclib's BigInteger uses the php-gmp (GNU Multiple Precision Arithmetic Library), php-bcmath and OpenSSL extensions,
if they're available, for speed, but doesn't require them to maintain maximum compatibility. 
The GMP library uses an internal resource type, while the BCMath library uses strings as datatype.
The most salient difference is, that GMP works on [arbitrary precision] integer values, whereas BCMath
allows [arbitrary precision] decimal / float-like values.

== Cryptography Library

The sodium and OpenSSL PHP libraries are cryptographic libraries which are part of the PHP core from PHP 7.2 onwards.
Consequently, there is no need to install additional cryptographic libraries, such as php-libsodium or mcrypt.

[NOTE]
====
mcrypt was deprecated in PHP 7.2.
If you need it, it is still available via PECL.

mcrypt is only used if it's available.
If mcrypt is not available, either a pure-PHP implementation or OpenSSL is used instead.

The prioritization is as follows: OpenSSL > mcrypt > pure-PHP. 
mcrypt and OpenSSL load faster than the pure-PHP implementation. 
mcrypt offers a 45x speedup over pure-PHP.
OpenSSL offers a greater than 6.5x speedup over mcrypt.
====

=== Mcrypt PHP Library

Here are the steps for installing mcrypt, when it is explicitly required.

NOTE: Some of the steps were borrowed from the website for student’s
{mcrypt-link-url}[guide to installing the PHP 7.2-Mcrypt module].

First, determine the mcrypt version you want to use in {mcrypt-pecl-url}[PECL's mcrypt documentation].
Then, run the following commands to install it.

[source,console]
----
sudo apt install php-dev libmcrypt-dev php-pear
sudo pecl channel-update pecl.php.net
sudo pecl install mcrypt-<desired mcrypt version>
----

When the commands complete, you then have to:

* Create `/etc/php/7.2/mods-available/mcrypt.ini` with the following content: `extension=mcrypt.so`.
* Enable the module by running `phpenmod mcrypt`.
* Restart your web server, by running the following commands:
+
  sudo service apache2 restart

=== php-libsodium

NOTE: From PHP 7.2 onwards, libsodium is part of PHP, so installing this extension is no longer necessary.

If you see the message "_PHP Fatal error: sodium_init() in Unknown on line 0_" when invoking the command
`php -v` or when running PHP programs, php-libsodium may have been installed unnecessarily.
This error does not do any harm, but it can be annoying and it fills up your logs.
To prevent this, you can uninstall php-libsodium. 
This can be done by invoking the following command:

[source,console]
----
sudo apt remove php-libsodium
----

You can check success by invoking the command `php -v`, which should no longer return the error message.
You can also check the existence of sodium with following command:

[source,console]
----
grep -P "sodium support => enabled" <( php -i )
----

== libsmbclient-php Library

libsmbclient-php is a PHP extension that uses Samba's libsmbclient library to provide Samba-related functions
to PHP programs. You only need to install it if you have installed smbclient as described above. 
To install it, run the following commands.

[source,console]
----
sudo apt install php-dev libsmbclient-dev php-pear
sudo pecl channel-update pecl.php.net
sudo pecl install smbclient
----

When the commands complete, you then have to:

- Create `/etc/php/7.2/mods-available/smbclient.ini` with following content `extension=smbclient.so`.
- Enable the module by running `phpenmod smbclient`.
- Restart PHP and your web server by running the following command:
+
  sudo service apache2 restart

[IMPORTANT]
====
Due to a change in the minimum protocol version used in the Samba client in Ubuntu 18.04, you may not get a
valid connection in ownCloud. This error is identified by a red box at the mount definition or being unable to
list directory content. In this case, you have to add the following to `/etc/samba/smb.cnf`, below the
`workgroup =` statement:

`client max protocol = NT1`

For more information see: {discover-samba-hosts-url}[Bionic Beaver can not discover Samba hosts]
====

== MariaDB Database

For how to install the latest stable release of MariaDB, please refer to
{install-mariadb-latest-url}[the MariaDB installation documentation].

[NOTE]
====
For MariaDB server releases lower than 10.4.3, you will be prompted during the installation to create a root
password. Be sure to remember your password, as you will need it during the ownCloud database setup.
====

[NOTE]
====
If you have an existing installation of MariaDB and upgrade to a higher version, do not forget to run the following
command, to handle the new setup for admin users — especially when upgrading to MariaDB 10.4.3 upwards:

[source,console]
----
sudo mysql_upgrade 
----
====

[NOTE]
====
From MariaDB 10.4.3 onwards, the authentication method has changed to UNIX sockets. 
For details, please refer to: {auth-unix-socket-url}[MariaDB: Authentication Plugin - Unix Socket].
The unix_socket authentication plugin allows the user to use operating system credentials when
connecting to MariaDB via a local UNIX socket. Follow the procedure below to create an admin user
for non-socket login, giving ownCloud access to create it's database respectively for phpMyAdmin. 
_This is not the ownCloud user!_
_Don't forget to change the username and password according to your needs_.

[source,console]
----
sudo mysql
MariaDB [(none)]>
 CREATE USER IF NOT EXISTS 'newuser'@'localhost' IDENTIFIED BY 'changeme';
 GRANT ALL PRIVILEGES ON *.* TO 'newuser'@'localhost' WITH GRANT OPTION;
 FLUSH PRIVILEGES;
 SHOW GRANTS FOR 'newuser'@'localhost';
----
====

NOTE: Follow this procedure, if you want to disable <<Disable Transparent Huge Pages (THP),Transparent Huge Pages>>

If you want to install phpMyAdmin as a graphical interface for administering the database, run the following command:

[source,console]
----
sudo apt install phpmyadmin
----

== Useful Tips

=== Start a Service After a Resource is Mounted

If you have network resources, such as NFS or iSCSI based mounts and you want to make
sure that thedatabase or web server only starts _after_ the resource is mounted.
Consider the following example setup when configuring your system.

The example below is based on an NFS mount which you want to be available _before_ the service with <name.service> starts.
The same procedure can be used for iSCSI. 
For details setting up an iSCSI mount see the {iscsi_initiator-url}[Ubuntu 18.04 iSCSI Initiator] guide.
 
The name in <name.service> could be any valid service, including `apache2`, `mysql` or `mariadb`.

* Add `_netdev` to the list of NFS mount point options in `/etc/fstab`.
+
--
This option ensures that the mount happens _after_ the network is up:

[source,console]
----
resource:foreign_path local_path nfs (<your options>),_netdev
----
--

* Make sure that all mounts in `/etc/fstab` are mounted by running:
+
--
[source,console]
----
sudo mount -a
----
--

* Run the following command to list mounts which must be up first:
+
--
[source,console]
----
systemctl list-units | grep -nP "\.mount"
----

You should see lines printed to the console.
Look for the mount you want to be up in the command's output. 

[source,console]
----
<folder.mount>
  loaded active mounted <local_path>
----
where `<folder.mount>` and `<local_path>` are examples!
--

* Edit the service you want to change:
+
--
[source,console]
----
sudo systemctl edit <name>.service
----

Add the following directive in the editor opened using your chosen `folder.mount` from above:

[source,console]
----
[Unit]
After=folder.mount
----

You can add more than one dependency if needed by separating them with spaces.
This procedure keeps `<name>.service` in its original state but makes it possible to override the
current setup with new parameters. It automatically creates a directory in `/etc/systemd/system`,
named `<name>.service.d`, and a file in that directory called `override.conf`.
In the example above, the parameter is added to the existing list of parameters of the `After` directive.

For more details please read section {overriding-vendor-settings-url}[Example 2. Overriding vendor settings]

Please keep the following points in mind, regarding if `<name>.service` is linked or not:

** If the file is linked from `/lib/systemd/system`, it is for packaged unit files.
They are overwritten when Systemd (or whatever package provides them) is upgraded.

** If the file originates in `/etc/systemd/system`, it is for your own and customised unit files.
Unit files you place in here override the package-provided file and will not be replaced on upgrade.

It is recommended to keep things simple and future proof by creating an override file via `systemctl edit`.
--

* Run the following command to apply your changes:
+
--
[source,console]
----
sudo systemctl daemon-reload
----
--

* Check if `<name>.service` has been properly added:
+
--
[source,console]
----
sudo systemctl show <name>.service | grep "After="
----
`folder.mount` should be part of the parameter list.
--

* Restart your service by invoking:
+
--
[source,console]
----
sudo system <name> restart
----
--

=== Disable Transparent Huge Pages (THP)

{transport-huge-pages-url}[Transparent Huge Pages] should be disabled when using databases.
This is applicable when using Redis, as well as MariaDB.
For more information read: {disabling-thp-url}[Why THP (Transparent Huge Pages) are not recommended for Databases].

To disable Transparent Huge Pages, follow these steps:

* Create in `/etc/systemd/system` a file like `disable-thp.service` add the following content:
+
--
[source,console]
----
[Unit]
Description=Disable Transparent Huge Pages
DefaultDependencies=no
After=sysinit.target local-fs.target
Before=basic.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c '/bin/echo never > /sys/kernel/mm/transparent_hugepage/enabled'
ExecStart=/bin/sh -c '/bin/echo never > /sys/kernel/mm/transparent_hugepage/defrag'

[Install]
WantedBy=basic.target
----
--

* Run following command to apply and activate your changes and start it automatically at boot time:
+
--
[source,console]
----
sudo systemctl daemon-reload
sudo systemctl enable disable-thp
sudo service disable-thp start
----
--
