= System Requirements
:toc: right
:toclevels: 1
:ppa-guide-url: https://itsfoss.com/ppa-guide/
:desktop-system-requirements-url: https://doc.owncloud.com/desktop/installing.html#system-requirements
:ios-system-requirements-url: https://doc.owncloud.com/ios-app/ios_faq.html
:android-system-requirements-url: https://doc.owncloud.com/android/faq.html

== Officially Recommended Environment

For _best performance_, _stability_, _support_ and _full functionality_, we officially recommend and support:

[cols="1,2a",options="header"]
|===
|Platform
|Options

|Operating System
|Ubuntu 20.04 LTS

|Database
|MariaDB 10.5 ^1^

|Web server
|Apache 2.4 with xref:installation/manual_installation/manual_installation.adoc#configure-the-web-server[`prefork and mod_php`]

|PHP Runtime
|{recommended-php-version}
|===

(1) MariaDB 10.6 is *only supported* with ownCloud release 10.9 and upwards. See the xref:installation/manual_installation/manual_installation.adoc#install-a-database[Install a Database] guide and the _Database Upgrade_ guide available in the 10.9 documentation.

== Officially Supported Environments

For _best performance_, _stability_, _support_, and _full functionality_ we officially support:

=== Server

[cols="1,2a",options="header"]
|===
|Platform
|Options

|Operating System (64bit)
|
* Debian 10
* Fedora 32 and 33
* Red Hat Enterprise Linux/Centos 7.5 and 8
* SUSE Linux Enterprise Server 12 with SP4/5 and 15
* Ubuntu 18.04 and 20.04
* openSUSE Leap 15.2

|Database
|
* MySQL 8+ or MariaDB 10.2, 10.3, 10.4 or 10.5 ^1^ (*Recommended*)
* Oracle 11 and 12
* PostgreSQL 9 and 10
* SQLite (*Not for production*)

|Web server
|* Apache 2.4 with xref:installation/manual_installation/manual_installation.adoc#configure-the-web-server[`prefork` and `mod_php`]

|PHP Runtime
|* {supported-php-versions}
|===

(1) MariaDB 10.6 is *only supported* with ownCloud release 10.9 and upwards. See the xref:installation/manual_installation/manual_installation.adoc#install-a-database[Install a Database] guide and xref:maintenance/upgrading/database_upgrade.adoc[Database Upgrade] guide.

[NOTE]
====
For Linux distributions, we support, if technically feasible, the latest two versions per platform and the previous LTS Version.
====

=== Hypervisors

* Hyper-V
* VMware ESX
* Xen
* KVM

=== Web Browser

* Edge (current version on Windows 10)
* IE11 or newer (except Compatibility Mode)
* Firefox 60 ESR+
* Chrome 66+
* Safari 10+

=== Desktop Sync Client

We always recommend to use the newest sync client with the latest server release.

You can find {desktop-system-requirements-url}[detailed system requirements] in the documentation for the Desktop Synchronization Client.

=== Mobile Apps

We always recommend to use the newest mobile apps with the latest server release.

You can find detailed system requirements in the documentation for the mobile apps.

* {ios-system-requirements-url}[iOS system requirements]
* {android-system-requirements-url}[Android system requirements]

[TIP]
====
You can find out more in the https://owncloud.com/changelog[changelog].
====

== Database Requirements

The following database settings are currently required if you’re running ownCloud together with a MySQL or MariaDB database:

* Disabled or `BINLOG_FORMAT = MIXED` or `BINLOG_FORMAT = ROW` configured Binary Logging (See: xref:configuration/database/linux_database_configuration.adoc#mysql-mariadb[MySQL / MariaDB with Binary Logging Enabled])
* InnoDB storage engine (The MyISAM storage engine is *not supported*, see:
xref:configuration/database/linux_database_configuration.adoc#mysql-mariadb[MySQL / MariaDB storage engine])
* `READ COMMITTED` transaction isolation level (See:
xref:configuration/database/linux_database_configuration.adoc#set-read-committed-as-the-transaction-isolation-level[MySQL / MariaDB `READ COMMITTED` transaction isolation level])

== Memory Requirements

Memory requirements for running an ownCloud server are greatly variable, depending on the numbers of users and files, and volume of server activity. ownCloud officially requires a minimum of 128MB RAM.
But, we recommend a minimum of 512MB.
