= Manual installation of ownCloud on Ubuntu 18.04

:toc: right

TIP: Copy/Paste these commands into you terminal/shell

== Preparation
First we have to prepare our server for ownCloud.

=== Prerequisites
Freshly installed https://www.ubuntu.com/download/server[Ubuntu 18.04] Server with SSH.

==== Update OS

....
apt update && apt upgrade -y
....

==== Create helper script

....
FILE="/usr/local/bin/occ"
/bin/cat <<EOM >$FILE
#! /bin/bash
cd /var/www/owncloud
sudo -u www-data /usr/bin/php /var/www/owncloud/occ "\$@"
EOM

chmod +x /usr/local/bin/occ

....

== Installation

=== Install the required packages

....
apt install -y \
apache2 \
mariadb-server \
libapache2-mod-php7.2 \
openssl \
php-imagick php7.2-common php7.2-curl \
php7.2-gd php7.2-imap php7.2-intl \
php7.2-json php7.2-mbstring php7.2-mysql \
php-ssh2 php7.2-xml php7.2-zip \
php-apcu php-redis redis-server \
wget
....

=== Install the recommended packages

....
apt install -y \
ssh bzip2 rsync curl jq \
sudo inetutils-ping \
smbclient php-smbclient coreutils php7.2-ldap
....
WARNING: The current Ubuntu 18.04 includes smbclient 4.7.6 which has the known limitation to use only SMB V1 protocol.

=== Configure the web Server

==== Change the document root
....
sed -i  "s#html#owncloud#" /etc/apache2/sites-available/000-default.conf

service apache2 restart
....

==== Create ownCloud.conf

....
FILE="/etc/apache2/sites-available/owncloud.conf"
/bin/cat <<EOM >$FILE
Alias /owncloud "/var/www/owncloud/"

<Directory /var/www/owncloud/>
  Options +FollowSymlinks
  AllowOverride All

 <IfModule mod_dav.c>
  Dav off
 </IfModule>

 SetEnv HOME /var/www/owncloud
 SetEnv HTTP_HOME /var/www/owncloud

</Directory>
EOM
....

....
ln -s /etc/apache2/sites-available/owncloud.conf \
/etc/apache2/sites-enabled/owncloud.conf

service apache2 restart
....

==== Configure the Database

....
mysql -u root -e "CREATE DATABASE IF NOT EXISTS owncloud; \
GRANT ALL PRIVILEGES ON owncloud.* TO owncloud@localhost IDENTIFIED BY 'password'";
....

==== Install recommended Web Server Modules

....
echo "Enabling a2mod Modules"
a2enmod rewrite
a2enmod headers
a2enmod env
a2enmod dir
a2enmod mime
a2enmod setenvif
service apache2 restart
....

==== Download ownCloud

....
cd /var/www
wget https://download.owncloud.org/community/owncloud-10.2.0.tar.bz2
tar xjf owncloud-10.2.0.tar.bz2
chown -R www-data. /var/www/owncloud
....

==== Install ownCloud

....
occ maintenance:install \
    --database "mysql" --database-name "owncloud" \
    --database-user "owncloud" --database-pass "password" \
    --admin-user "admin" --admin-pass "admin"
....

==== Configure Trusted Domains

....
myip=$(hostname -I|cut -f1 -d ' ')
occ config:system:set trusted_domains 1 --value="$myip"
....

==== Set up a Cron Job

....
echo "*/15  *  *  *  * /usr/bin/php -f /var/www/owncloud/cron.php" > /var/spool/cron/crontabs/www-data
chown www-data.crontab  /var/spool/cron/crontabs/www-data
chmod 0600  /var/spool/cron/crontabs/www-data
....

NOTE: If you haven a LDAP/Active Directory Server connected to ownCloud you need to add this additional cronjob to sync your LDAP users locally.

....
echo "*  */6  *  *  * /usr/bin/php -f /var/www/owncloud/cron.php" > /var/spool/cron/crontabs/www-data
chown www-data.crontab  /var/spool/cron/crontabs/www-data
chmod 0600  /var/spool/cron/crontabs/www-data
....

==== Configure Caching and File Locking

Add this to your config.php

....
'memcache.local' => '\OC\Memcache\APCu',
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => array(
      'host' => 'localhost',
      'port' => 6379,
       ),
....

==== Configure Log Rotation

Execute this command to set up log rotation.

....
FILE="/etc/logrotate.d/owncloud"
/bin/cat <<EOM >$FILE
/var/www/owncloud_data/owncloud.log {
size 10M
rotate 12
copytruncate
missingok
compress
compresscmd  /bin/gzip
EOM
....

==== Adjust the Permissions

....
FILE="/usr/local/bin/ocpermissions"
/bin/cat <<EOM >$FILE
#!/bin/bash 
ocpath='/var/www/owncloud' 
datadir='/var/owncloud/data' 
htuser='www-data' 
htgroup='www-data' 
rootuser='root' 
printf "Creating possible missing Directories\n" 
mkdir -p \$ocpath/assets 
mkdir -p \$ocpath/updater 
mkdir -p \$datadir 
printf "chmod Files and Directories\n" 
find \${ocpath}/ -type f -print0 | xargs -0 chmod 0640 
find \${ocpath}/ -type d -print0 | xargs -0 chmod 0750 
printf "chown Directories\n" 
chown -R \${rootuser}:\${htgroup} \${ocpath}/ 
chown -R \${htuser}:\${htgroup} \${ocpath}/apps/ 
chown -R \${htuser}:\${htgroup} \${ocpath}/assets/ 
chown -R \${htuser}:\${htgroup} \${ocpath}/config/ 
chown -R \${htuser}:\${htgroup} \${datadir} 
chown -R \${htuser}:\${htgroup} \${ocpath}/updater/ 
chmod +x \${ocpath}/occ
printf "chmod/chown .htaccess\n"
if [ -f \${ocpath}/.htaccess ] 
then  
chmod 0644 \${ocpath}/.htaccess  
chown \${rootuser}:\${htgroup} \${ocpath}/.htaccess 
fi 
if [ -f \${datadir}/.htaccess ] 
then  
chmod 0644 \${datadir}/.htaccess  
chown \${rootuser}:\${htgroup} \${datadir}/.htaccess
fi 
EOM

chmod +x /usr/local/bin/ocpermissions

ocpermissions
....
