= Install ownCloud on Ubuntu 18.04
:toc: right
:logrotate-url: https://linux.die.net/man/8/logrotate
:webserver-user: www-data
:webserver-group: www-data
:install-directory: /var/www/owncloud
:ubuntu-version: 18.04

This is a, reasonably, concise guide to installing ownCloud on a fresh installation of Ubuntu {ubuntu-version}.

== Prerequisites

* A fresh install of https://www.ubuntu.com/download/server[Ubuntu {ubuntu-version}] with SSH enabled.
* This guide assumes that you are connected as the root user.

== Ultra Short Guide

If you are short on time and just need the essential instructions for installing ownCloud on Ubuntu {ubuntu-version}, then run the commands below.
However, if you want an annotated guide, then please refer to the remainder of this guide.

[source,console,subs="attributes+"]
----
# Add ownCloud’s repository to the list of available Apt repositories
curl https://download.owncloud.org/download/repositories/production/Ubuntu_{ubuntu-version}/Release.key \
  | apt-key add -
echo 'deb http://download.owncloud.org/download/repositories/production/Ubuntu_{ubuntu-version}/ /' \
  > /etc/apt/sources.list.d/owncloud-files.list

# Install the required packages
apt update
apt install -y libapache2-mod-php owncloud-files php-bz2 php-curl \
  php-gd php-imagick php-intl php-mbstring php-mysql php-sqlite3 \
  php-xml php-zip

# Configure Apache for ownCloud
cp /usr/share/doc/owncloud-files/owncloud-config-apache.conf.default /etc/apache2/conf-available/owncloud-config-apache.conf
a2enconf owncloud-config-apache
a2enmod php7.2

# Restart Apache
systemctl reload apache2

# View the new site in Firefox
firefox http://localhost/owncloud
----

== Preparation

First, ensure that all of the installed packages are entirely up to date, and that PHP is available in the APT repository.
To do so, follow the instructions below:

[source,console,subs="attributes+"]
----
apt update && \
  apt upgrade -y
----

=== Create the occ Helper Script

Create a helper script to simplify running xref:configuration/server/occ_command.adoc[occ commands].

[source,console,subs="attributes+"]
----
FILE="/usr/local/bin/occ"
/bin/cat <<EOM >$FILE
#! /bin/bash

cd {install-directory}
sudo -u {webserver-user} /usr/bin/php {install-directory}/occ "\$@"
EOM
----

Make helper script executable:

[source,console,subs="attributes+"]
----
chmod +x /usr/local/bin/occ
----

=== Install the Required Packages

[source,console,subs="attributes+"]
----
apt install -y \
  apache2 \
  libapache2-mod-php \
  mariadb-server \
  openssl \
  php-imagick php-common php-curl \
  php-gd php-imap php-intl \
  php-json php-mbstring php-mysql \
  php-ssh2 php-xml php-zip \
  php-apcu php-redis redis-server \
  wget
----

=== Install the Recommended Packages

[source,console,subs="attributes+"]
----
apt install -y \
  ssh bzip2 rsync curl jq \
  inetutils-ping smbclient\
  php-smbclient coreutils php-ldap
----

WARNING: Ubuntu {ubuntu-version} includes smbclient 4.7.6, which has a known limitation of only using version 1 of the SMB protocol.

== Installation

=== Configure Apache

==== Change the Document Root

[source,console,subs="attributes+"]
----
sed -i "s#html#owncloud#" /etc/apache2/sites-available/000-default.conf

service apache2 restart
----

==== Create a Virtual Host Configuration

[source,console,subs="attributes+"]
----
include::{examplesdir}installation/ubuntu/{ubuntu-version}/create-vhost-config.sh[]
----

==== Enable the Virtual Host Configuration

[source,console,subs="attributes+"]
----
a2ensite owncloud.conf
service apache2 reload
----

=== Configure the Database

[source,console,subs="attributes+"]
----
mysql -u root -e "CREATE DATABASE IF NOT EXISTS owncloud; \
GRANT ALL PRIVILEGES ON owncloud.* \
  TO owncloud@localhost \
  IDENTIFIED BY 'password'";
----

==== Enable the Recommended Apache Modules

[source,console,subs="attributes+"]
----
echo "Enabling Apache Modules"

a2enmod dir env headers mime rewrite setenvif
service apache2 reload
----

=== Setup ownCloud

==== Download ownCloud

[source,console,subs="attributes+"]
----
cd /var/www/
wget https://download.owncloud.org/community/owncloud-10.2.1.tar.bz2 && \
tar -xjf owncloud-10.2.1.tar.bz2 && \
chown -R www-data. owncloud
----

==== Install ownCloud

[source,console,subs="attributes+"]
----
occ maintenance:install \
    --database "mysql" \
    --database-name "owncloud" \
    --database-user "owncloud" \
    --database-pass "password" \
    --admin-user "admin" \
    --admin-pass "admin"
----

==== Configure ownCloud's Trusted Domains

[source,console,subs="attributes+"]
----
myip=$(hostname -I|cut -f1 -d ' ')
occ config:system:set trusted_domains 1 --value="$myip"
----

==== Set Up a Cron Job

[source,console,subs="attributes+"]
----
echo "*/15  *  *  *  * /usr/bin/php /path/to/your/owncloud/occ system:cron" \
  > /var/spool/cron/crontabs/{webserver-user}
chown {webserver-user}.crontab /var/spool/cron/crontabs/{webserver-user}
chmod 0600 /var/spool/cron/crontabs/{webserver-user}
----

[NOTE]
====
If you need to sync your users from an LDAP or Active Directory Server, add this additional xref:configuration/server/background_jobs_configuration.adoc[Cron job].

[source,console,subs="attributes+"]
----
echo "*/15  *  *  *  * /usr/bin/php /path/to/your/owncloud/occ system:cron" > /var/spool/cron/crontabs/www-data
chown www-data.crontab  /var/spool/cron/crontabs/www-data
chmod 0600  /var/spool/cron/crontabs/www-data
----
====

==== Configure Caching and File Locking

Execute these commands:

[source,php]
----
occ config:system:set \
   memcache.local \
   --value '\OC\Memcache\APCu'

occ config:system:set \
   memcache.locking \
   --value '\OC\Memcache\Redis'

occ config:system:set \
   redis \
   --value '{"host": "127.0.0.1", "port": "6379"}' \
   --type json
----

=== Configure Log Rotation

Execute this command to set up {logrotate-url}[log rotation].

[source,console,subs="attributes+"]
----
include::{examplesdir}installation/ubuntu/{ubuntu-version}/configure-log-rotation.sh[]
----

==== Finalise the Installation 

[source,console]
----
include::{examplesdir}installation/ubuntu/{ubuntu-version}/finalise-install.sh[]
----

**ownCloud is now installed. 
You can confirm that it is ready to use by pointing your web browser to your ownCloud installation.**
