= Guests App

Share with external users conveniently just by entering an email address in the sharing dialog. 
Recipients receive an email containing an activation link. 
They can log in using their email address as user name and the password they chose during activation. 
Guests may even use the ownCloud desktop clients and mobile apps to connect to ownCloud and work on shared contents.

Guest users do not have storage space and can only work in contents that are shared with them.
Have a look at our informational YouTube video below, for an introduction to the Guests app.

video::L42PBHgqKVI[youtube,width=640,height=360]

== Installation

Go to Market and install the Guests app if not already installed with your bundle.
The Guests app requires the email server to be configured in your ownCloud because you need to be able to invite your guests by mail.

== Configuration

Check your Guests app's configuration in the sharing section of the admin settings. 
There you can change the Guest's **group name** and add or exclude apps to the app **whitelist** of the Guests app. 
Guests can not access apps that are not in that list.

== Troubleshooting

If for some reason you don't see some buttons, please try a different browser to exclude the script/adblocking add-on as a cause.
If you as a guest user can not open a PDF document for example in your ownCloud, but you can download it - please check the White List of your Guests app in the sharing section of the admin settings. 
You have to specify that the guest users can access the required app.
