= How To Install and Configure an LDAP Proxy-Cache Server
:toc: right
:experimental:
:list-of-ldap-url: https://en.wikipedia.org/wiki/List_of_LDAP_software
:open-ldap-url: https://en.wikipedia.org/wiki/OpenLDAP

[[background]]
== Background

To reduce network traffic overhead and avoid problems either logging in
or performing user searches while sharing, it’s an excellent idea to
implement an LDAP proxy cache.

An LDAP proxy cache server, similar to other kinds of caching servers,
is a special type of LDAP replica. It can cache a range of LDAP records,
often resulting in improved LDAP server performance.

Specifically, the records which need to be cached, for improved ownCloud
performance, are:

* Users that are allowed to log in
* Groups (limited to the allowed users)
* Search fields (e.g., `sAMAccountName`, `CN`, `SN`, `givenName`, and `displayName`)

[[how-to-setup-the-server]]
== How To Setup the Server

There’s not that much to it, just the following five steps:

1.  xref:install-openldap[Install OpenLDAP]
2.  xref:configure-the-server[Configure the Server]
3.  xref:enable-the-configuration-file[Enable the Configuration File]
4.  xref:open-the-log[Check the Log]
5.  xref:perform-a-test-search[Perform a Test Search]
6.  xref:configure-owncloud-ldap-app[Configure ownCloud LDAP App]

[[install-openldap]]
=== Install OpenLDAP

There are a number of {list-of-ldap-url}[LDAP server implementations] available,
the one used in this guide is {open-ldap-url}[OpenLDAP].

NOTE: While OpenLDAP does work on any operating system, for the purposes of this guide,
we’ll be using a Debian-based Linux distribution.

First update your system, to ensure that you are using the latest packages.:

[source,console]
----
sudo apt-get update && apt-get upgrade -y
----

Next, install OpenLDAP and its associated packages.:

[source,console]
----
sudo apt-get install slapd ldap-utils -y
----

[[configure-the-server]]
=== Configure the Server

With OpenLDAP installed and running, you now need to configure the
server. One way of doing so, is to create a configuration file. So,
create `/etc/ldap/slapd.conf` with your text editor of choice, and add
the following configuration to it.

[source,conf]
----
include::example$configuration/ldap/single.slapd.conf[]
----

NOTE: This configuration only caches queries from a single Active Directory server. To cache queries from multiple Active Directory servers, a configuration is available below.

After you’ve done that, save the file, test that there are no errors in
the configuration by running:

[source,console]
----
sudo slaptest -f /etc/ldap/slapd.conf
----

NOTE: If you see warnings in the console output, they are not crucial.

[[enable-the-configuration-file]]
=== Enable the Configuration File

Next, we need to tell OpenLDAP to use our configuration. +
To do so, open `/etc/default/slapd` and add the following line to it:

....
SLAPD_CONF=/etc/ldap/slapd.conf
....

With that done, restart OpenLDAP by running the following command:

[source,console]
----
sudo service slapd restart
----

[[open-the-log]]
=== Open the Log

Open another terminal and see the systemlog with the following command.:

[source,console]
----
tail -f /var/log/syslog | grep QUERY
----

If there is no such file, you need to install rsyslog with.

[source,console]
----
sudo apt install rsyslog
----

[[perform-a-test-search]]
=== Perform a Test Search

Now that the server’s installed, configured, and running, we next need
to perform a search. This will check that records are being correctly
cached. To do so, update the command below with values from your Active
Directory server configuration, and then run it.:

[source]
----
sudo ldapsearch -h localhost -x -LLL \
	-D "cn=admin,cn=users,dc=example,dc=com" \
 	-b "cn=users,dc=example,dc=com" \
	-w "Password" "(cn=Administrator)" name
----

or

[source]
----
sudo ldapsearch -H ldaps://localhost:636 -x -LLL \
	-D "cn=admin,cn=users,dc=example,dc=com" \
	-b "cn=users,dc=example,dc=com" \
	-W "(cn=Administrator)" name
----

.Description of Options
[width="100%",cols="20%,80%",options="header",]
|===
| Option
| Description

| -h
| Host address (Example: `localhost` or `192.168.1.1`)

| -H
| Host address (Example: `ldap://` or `ldaps://` hostname or ip and port `:389` or `:636`)

| -x
| Simple authentication

| -b
| Search Base, (Example: `cn=Users,dc=example,dc=com`)

| -D
| User with permissions (Example: `cn=Admin,dc=example,dc=com`)

| -LLL
| Show only results, no extra information

| -w
| Password ("Password")

| -W
| Password, will ask for password and hide your input

| `(cn=Administrator)`
| Filter the search

| name
| Show only this attributes
|===

If you see results including: `"Query cachable"` and `"Query answered (x) times"`, then the setup works.

[[configure-owncloud-ldap-app]]
=== Configure ownCloud LDAP App

Login as ownCloud admin in your ownCloud server.

* Click on the dropdown menu in the top-right corner menu:Settings[].
** Click on the dropdown menu in the left side menu:Administrator[Apps].
** Click on btn:[Show Disabled Apps] and enable the `LDAP Integration` App.
* Click on the menu in the left side menu:Administrator[User Authentication].
** Select `LDAP` if not already selected.

* Select menu:Server[] tab
** First enter the server address, either IP or DN.
** You can click on the button to detect your servers port or enter it manually.
** Enter the `DN` of the user you want to log in with
** Enter the password in the next line
** Click on btn:[Detect Base DN] or enter it manually
** Click on btn:[Test Base DN]

* If you fulfill all the requirements you should get a green light and `Configuration OK` message.

* Select menu:User[] tab
** Select the objectclass for the users, for example `user`.
** Verify your settings +
You will see the number of users being found

* Select menu:Attributes[] tab
** A configuration appears by default +
Adjust it to your users configuration
** If required, adjust the login parameters additional login attributes
** You can check users with any of the allowed login options +
You can adjust them or leave them the way they are

* Select menu:Groups[] tab
** Select all the objectclasses for your groups, for example `group` +
Verify your settings

* Select menu:Advanced[] tab
** Configuration Active shoud be selected.
** Adjust the Cache TTL (time to live) value as required
** ownCloud usualy autoselects the best settings for each AD configuration
** Check if the Group-Member association is `Member (AD)` +
That’s important for the users being shown in their respective groups
** Select `Nested groups`, if you have them

* Select menu:Expert[] tab
** Click btn:[Internal Username Attribute] +
Here we need to set `CN` for the users being shown with their unique
name. If you leave that field empty, each user will get a unique uid as
a string of numbers and letters
** Clear the Username and Groupname Mapping and test your configuration by
clicking on the buttons below

* Navigate to our ownCloud `User` administration page and check if all your users are listed
properly, and shown in the right groups.

* Go to the homepage of your ownCloud server and try to share something
with one of your users

If everything is set up correctly, you now have an LDAP proxy server to
your active directory that will reduce the network traffic by caching the
searches your perform.

[[cache-multiple-active-directory-servers]]
== Cache Multiple Active Directory Servers

If you have more than one that you want to cache, in
`/etc/ldap/slapd.conf` add the following configuration instead,
adjusting as necessary. The ownCloud LDAP app settings are the same as
in section 6.

[source,conf]
----
include::example$configuration/ldap/Multi-AD.slapd.conf[]
----
