= Providing log files and configurations

When you report a problem to ownCloud Support or our Forum (central) you will be asked to provide certain log files or configs
for our engineers or other users to better understand your issue, your specific configuration and the cause of the problem.
Here are instructions how to collect those files.

'''

== Config Report
You can use the webUI or the command line to generate a config report.
Please note that you have to have the configreport app enabled. You can enable this app with:
`occ market:install configreport`  or  `occ:app enable configreport`

=== web UI
Navigate to: admin > settings > general > "Generate Config report" > "Download ownCloud config report" 

=== Command Line
`occ  configreport:generate > config_report.txt`

'''

== ownCloud Server Log File
You can use the webUI to download your ownCloud Server log file

=== web UI
Navigate to admin > settings > general > Log > "Download logfile"

'''

== LDAP Config

LDAP config is important to check for errors in the configuration of your LDAP to ownCloud connection. Execute this command:

`occ ldap:show-config > ldap_config.txt`
