= Microsoft Office Online / WOPI Integration
:toc: right
:msoffice-online-server-url: https://www.microsoft.com/en-us/microsoft-365/blog/2016/05/04/office-online-server-now-available/
:office365-url: https://products.office.com/en-us/business/office 
:wopi-protocol-url: https://wopi.readthedocs.io/en/latest/
:office-online-server-url: https://docs.microsoft.com/de-de/officeonlineserver/deploy-office-online-server
:wopi-timeout-documentation-url: https://wopi.readthedocs.io/projects/wopirest/en/latest/concepts.html#term-lock

== About

The WOPI (Web Application Open Platform Interface) app, which is bundled with ownCloud Enterprise Edition, is the connector between ownCloud server and {msoffice-online-server-url}[Microsoft Office Online Server].

It allows Microsoft Office Online users to collaboratively work with Office documents in ownCloud in the browser, by connecting ownCloud with your Microsoft Office Online Server via {wopi-protocol-url}[the WOPI protocol]. 
To use it, you need to have a running Microsoft Office Online Server in your data center.

[NOTE]
====
Please bear in mind:

* WOPI is only available for ownCloud enterprise. It _is not available_ in the community version.
* Out-of-the box only the on-premise version of Microsoft Office Online Server is supported.
* This app requires ownCloud Version 10.1 and php 7.1.
====

TIP: If you want to integrate the {office365-url}[Office 365 (cloud)] version of Microsoft Office Online, you need to {oc-contact-url}[get in touch with us].

== Preparing the Environment
You need an {office-online-server-url}[Office Online Server] installed.

All involved servers (OfficeOnline Server and the ownCloud server) need to be accessible by HTTPS with valid certificates.

== Configuring the WOPI App in ownCloud

To configure the WOPI app in your ownCloud installation, add the following configuration to `config/config.php`, and adjust it based on the details of your setup:

[source,php]
----
'wopi.token.key' => 'replace-with-your-own-random-string',
'wopi.office-online.server' => 'https://your.office.online.server.tld',
----

== Restrict Usage to Users in a Specific Group

Microsoft Office Online access can be restricted to users in a specific group, by use of the `wopi_group` configuration key (in `config/config.php`), as in the following example.

[source,php]
----
'wopi_group' => 'admin'
----

In the example above, only users in the `admin` group would be able to access Microsoft Office Online.

NOTE: If the key is not defined, then all users have access to WOPI.

== Locking the Document

If you open a document with Microsoft Office Online in ownCloud, it makes use of the WebDAV file locking functionality, available in ownCloud server. 
The idea is to lock the file so other users, who have access, can't make changes to the document while you're editing it. 

In other words: the feature ensures that you are the "master editor", your changes will always be the "master state". 
Other users can make changes, e.g., with the desktop client, but those will create conflict files for them, which can be resolved afterward.
When you close the document, Microsoft Office Online also has a feature to unlock the file again, so others can edit it after you are finished editing it.

You can always click on the lock icon next to your file name and unlock it manually using the button in the sidebar.

=== Lock Timeout

If a user is editing a file and loses their internet connection the lock will timeout, freeing the lock, after 30 minutes. 
Please refer to {wopi-timeout-documentation-url}[the WOPI documentation] for further information.
