= OpenID Connect (OIDC)
:toc: right
:toclevels: 2
:page-aliases: configuration/user/oidc/index.adoc
:openid-connect-url: https://openid.net/connect/
:schemeful-samesite-url: https://web.dev/schemeful-samesite/
:ms-azure-ad-url: https://azure.microsoft.com/en-us/services/active-directory/
:ms-adfs-url: https://docs.microsoft.com/en-us/windows-server/identity/active-directory-federation-services
:ping-identity-url: https://developer.pingidentity.com/en/cloud-software/pingfederate.html
:cidaas-url: https://www.cidaas.com/
:keycloak-url: https://www.keycloak.org/
:kopano-konnect-github-url: https://github.com/Kopano-dev/konnect

== Introduction

{openid-connect-url}[OpenID Connect] is an open standard for single sign-on, identity and access management. With ownCloud it can be used for user authentication and client authorization against an external identity provider(IdP).

**Benefits of using ownCloud with OpenID Connect**

- Increased security by shifting user authentication to an external identity provider.
- Seamless integration into single sign-on (SSO) environments as well as with third party products.
- Centralized client management within the identity provider.
- Enterprise-grade security through the use of authentication security features (e.g., multi-factor authentication) and policies (e.g., automatic token expiration on certain conditions) provided by identity providers.

NOTE: ownCloud only supports one configured identity provider which is then valid for all requests.

Click on the
link:{attachmentsdir}/configuration/user/oidc/OAuth-code-flow-sequence-diagram.png[OAuth code flow sequence diagram]
link to get more details on the flow sequence.

== Supported Identity Providers

ownCloud Server can work with identity providers (IdP) that support OpenID Connect. There are many identity providers available and the OpenID Connect implementations vary a lot in terms of supported features as well as configuration needs. 

The currently supported products are

- {ms-azure-ad-url}[Microsoft Azure AD]
- {ms-adfs-url}[Microsoft ADFS]
- {ping-identity-url}[PingIdentity PingFederate]
- {cidaas-url}[cidaas]
- {keycloak-url}[Keycloak]
- {kopano-konnect-github-url}[Kopano Konnect]

Please get in touch with ownCloud Consulting if you need help with a specific identity provider product.

== Prerequisites

Setting up ownCloud Server to work with OpenID Connect requires a couple of components to work together:

- An external identity provider configured to work with the ownCloud components
- A distributed memcache setup - such as Redis or Memcached - is required to operate this app. Follow the xref:configuration/server/caching_configuration.adoc[caching documentation] on how to set it up.
- The {oc-marketplace-url}/apps/openidconnect[OpenID Connect App] installed on ownCloud Server
- Configuration settings in `config.php` on ownCloud Server
+
* `'http.cookie.samesite' \=> 'None',`
+
See xref:configuration/server/config_sample_php_parameters.adoc#define-how-to-relax-same-site-cookie-settings[config.sample.php] and {schemeful-samesite-url}[Schemeful Same-Site] for examples and details.
+
* Settings for the OpenID Connect App
+
See xref:configuration/server/config_apps_sample_php_parameters.adoc#app-openid-connect-oidc[config.apps.sample.php] for examples and details or see section xref:save-settings-in-the-database[Save Settings in the Database] below when running clustered setups.
- Service discovery for the xref:owncloud-desktop-and-mobile-clients[ownCloud Clients]

=== Save Settings in the Database

If you run a clustered setup, the following method configuring the OpenID Connect app is preferred, because it is stateless. The app checks for settings in the database first. If none are found, it falls back to the settings stored in `config.php`. The settings are stored as a JSON formatted string with the following keys and values: 

[width="50%",cols="40%,50%",options="header"]
|===
| Key
| Value

| appid
| 'openidconnect'

| configkey
| 'openid-connect'

| configvalue
| _JSON-String_
|===

If a malformed JSON string is found, an error is logged. The _key->value_ pairs are the same as when storing them to the `config.php` file. This task has to be done by invoking an occ command, see the following example. Use the occ commands `config:app:get` to view the current setting or `config:app:delete` to delete it. See the xref:configuration/server/occ_command.adoc#config-commands[Config Command Set] for more details.

[source,console,subs="attributes+"]
----
{occ-command-example-prefix} config:app:set \
    openidconnect \
    openid-connect \
    --value='{"provider-url":"https:\/\/idp.example.net","client-id":"fc9b5c78-ec73-47bf-befc-59d4fe780f6f","client-secret":"e3e5b04a-3c3c-4f4d-b16c-2a6e9fdd3cd1","loginButtonName":"Login via OpenId Connect"}'
----

NOTE: Only set either the database or the config.php keys but not both for the OpenID Connect app.

== Set Up Service Discovery

. Webserver Service Discovery Information
+
In order to allow the ownCloud Clients (Desktop/Android/iOS) to make use of OpenID Connect, the webserver serving ownCloud Server needs to _provide service discovery information_ under the following static path:
+
[source,url]
----
https://cloud.example.com/.well-known/openid-configuration
----

. App Service Discovery Information
+
When enabled, the OpenID Connect App provides the service discovery information on the endpoint:
+
[source,url]
----
https://cloud.example.com/index.php/apps/openidconnect/config
----

. Webserver Rewrite Rule
+
To make the endpoint available under the static service discovery path, it is recommended to put a `RewriteRule` in place using `.htaccess` (the Apache modules `proxy` and `proxy_http` have to be enabled):
+
[source,apache]
----
RewriteRule ^\.well-known/openid-configuration /index.php/apps/openidconnect/config [P]
----
+
TIP: Depending on the respective infrastructure setup there can be other ways to solve this. In any case, please make sure _not to use redirect rules_ as this will violate the OpenID Connect specification.
+
IMPORTANT: If you use the `.htaccess` file in the ownCloud web root, you have to manually add that rewrite rule again after any ownCloud upgrade.

. Once service discovery is available as described above, the ownCloud clients will attempt to connect via OpenID Connect.

== General Example Setup

All IdPs have their own setup, but often share common ways of configuring things. Although not identical, the xref:example-setup-using-kopano-konnect[Kopano Konnect] example may be a good starting point for the specific configuration of your setup. As Microsoft with Azure is different, it has its own example section.

== Example Setup Using Kopano Konnect

Follow this link to see 
xref:configuration/user/oidc/kopano-setup.adoc[Example Setup Using Kopano Konnect].

== Example Setup Using Microsoft Azure

Follow this link to see 
xref:configuration/user/oidc/ms-azure-setup.adoc[Example Setup Using Microsoft Azure].

== ownCloud Desktop and Mobile Clients

ownCloud desktop and mobile clients detect whether OIDC is available (service discovery) and use this login method when a new account is created.

NOTE: The desktop and mobile apps (clients) have a default client ID and secret hard-coded, which are used for ownCloud's oauth2 app. When using Kopano as IdP, it does not pre-define a client ID and secret. You can use the default ones of the client to configure Kopano properly. With some IdPs like MS-Azure, these and other required parameters come from the IdP and must be coded into the client. Note that each IdP has different requirements. Get in touch with ownCloud for a branding subscription to customize the clients according to your needs.

=== Client Support for OIDC

[caption=]
.Following owncloud clients support OIDC 
[width="50%",cols="40%,50%",options="header"]
|===
| ownCloud Client  | Release with OIDC support
| Desktop | >= 2.7.0
| Android | >= 2.15
| iOS     | >= 1.2
|===

=== Client IDs, Secrets and Redirect URIs

All IdPs can use ownCloud's default implemented _Client IDs, Secrets and Redirect URIs_ with the exception of Microsoft, which uses a different approach. Here is the data necessary for the configuration.

==== Client ID

[width="100%",cols="15%,85%",options="header"]
|===
| Source
| Key

| Server/Web
| as specified in `config.php`

| Desktop
| `xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69`

| Android
| `e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD`

| iOS
| `mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1`
|===

==== Client Secret

[width="100%",cols="15%,85%",options="header"]
|===
| Source
| Key

| Server/Web
| as specified in `config.php`

| Desktop
| `UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh`

| Android
| `dInFYGV33xKzhbRmpqQltYNdfLdJIfJ9L5ISoKhNoT9qZftpdWSP71VrpGR9pmoD`

| iOS
| `KFeFWWEZO9TkisIQzR3fo7hfiMXlOpaqP8CFuTbSHzV1TUuGECglPxpiVKJfOXIx`
|===

==== Redirect URIs

[width="100%",cols="15%,85%",options="header"]
|===
| Source
| Redirect URI

| Desktop ≤ 2.8
| `\http://localhost`

| Desktop ≥ 2.9
| `\http://127.0.0.1`

| Android
| `oc://android.owncloud.com`

| iOS
| `oc://ios.owncloud.com`
|===

=== Migrate Clients from Basic Authentication to OIDC

If your users are logged in to their desktop and mobile clients via basic authentication (username/password) against ownCloud Server and you are not using OAuth2 to authorize the ownCloud clients, a migration to OIDC can be conducted as follows:

1. Make sure you have a working OIDC configuration based on the above sections.
2. Enable the OpenID Connect App.
3. Enable xref:configuration/server/config_sample_php_parameters.adoc#enforce-token-only-authentication-for-apps-and-clients-connecting-to-owncloud[token-only authentication].

Once the OpenID Connect App is enabled, token-only authentication is enforced and service discovery is properly set up, the ownCloud clients will ask the users to re-authenticate. After a successful re-authentication, the migration is done.

To connect legacy clients, users have to generate xref:user_manual:personal_settings/security.adoc#app-passwords-tokens[special app passwords (tokens)].

=== Migrate Clients from OAuth2 to OIDC

If you use OAuth2 for client authorization, a migration to OIDC can be conducted as follows:

1. Make sure you have a working configuration based on the above sections.
2. Enable the OpenID Connect App (while having the OAuth2 App still enabled).
3. Disable the OAuth2 App.

Once the OAuth2 App is disabled and service discovery is properly set up, the ownCloud Clients will ask the users to re-authenticate. After a successful re-authentication, the migration is done.

== Migrate Web Login (and Client Login) from SAML to OIDC

If you are using SAML/SSO, a migration to OIDC depends on your identity provider and is not straight forward. Please get in touch with ownCloud Consulting to plan the migration.
