= Meta API
:toc: right
// Attributes for the core details include
:request_path: remote.php/dav/meta/<fileid> 
:method: PROPFIND
:content_type: text/xml
:report-request-uri: https://tools.ietf.org/html/rfc3253#section-3.6
:libxml-url: http://www.xmlsoft.org
:http207-url: https://httpstatuses.com/207
:http404-url: https://httpstatuses.com/404

== Introduction

An authenticated `PROPFIND` request to `{request_path}` returns the path to a file/folder for the
logged in user.

TIP: To retrieve a list of available files, use the
xref:webdav_api/search.adoc#limiting-returned-file-properties[Filter Files endpoint],
and ensure that returned properties includes `fileid`. 

include::{partialsdir}webdav_api/core_request_details.adoc[leveloffset=+1]

== Request Parameters

[cols=",,",options="header",]
|===
|Attribute 
|Type 
|Description

|`fileid` 
|integer 
|The file's id.
|===

TIP: The example above uses xmllint, available in {libxml-url}[the libxml2 package] to make
the response easier to read.

== Example Responses

=== Success

If the file of folder is found, then a response similar to the following will be returned with an
{http207-url}[HTTP/1.1 207 Multi-Status] status:

[source,xml]
----
include::{examplesdir}core/webdav_api/meta/response-success.xml[]
----

=== Failure

If the file is not found, then the following response will be returned with an
{http404-url}[HTTP/1.1 404 Not Found] status:

[source,xml]
----
include::{examplesdir}core/webdav_api/meta/response-failure.xml[]
----

== Example Request

[tabs]
====
Curl::
+
--
[source,console,subs="attributes+"]
----
curl -u {oc-examples-username}:{oc-examples-password} \
  -X PROPFIND \
  -H "Depth: 0" \
  -H "Content-Type: text/xml" \
  --data "@meta-files.xml" \
  '{oc-examples-server-url}/remote.php/dav/meta/<fileid>' | xmllint --format -
----
--
====

=== meta-files.xml

[source,xml]
----
include::{examplesdir}core/webdav_api/meta/meta-files-filter.xml[]
----
