= Backporting

[[general]]
== General

We backport important fixes and improvements from the current master
release to get them to our users faster.

[[process]]
== Process

We mostly consider bug fixes for back porting. Occasionally, important
changes to the API can be backported to make it easier for developers to
keep their apps working between major releases. If you think a pull
request (PR) is relevant for the stable release, go through these steps:

1.  Make sure the PR is merged to master
2.  Ask the feature maintainer if the code should be backported and add
the label
https://github.com/owncloud/core/labels/Backport-Request[backport-request]
to the PR
3.  If the maintainer say yes then create a new branch based on the
respective stable branch, cherry-pick the needed commits to that branch
and create a PR on GitHub.
4.  Specify the corresponding milestone for that series to this PR and
reference the original PR in there. This enables the QA team to find the
backported items for testing and having the original PR with detailed
description linked.

NOTE: Before each patch release there is a freeze to be able to test
everything as a whole without pulling in new changes. This freeze is
announced on the https://mailman.owncloud.org/pipermail/devel/[owncloud-devel
mailinglist]. While this freeze is active a backport isn’t allowed and
has to wait for the next patch release.

The QA team will try to reproduce all the issues with the
X.Y.Z-next-maintenance milestone on the relevant release and verify it
is fixed by the patch release (and doesn’t cause new problems). Once the
patch release is out, the post-fix -next-maintenance is removed and a
new -next-maintenance milestone is created for that series.

[[steps]]
== Steps

Because pushing directly to particular ownCloud branches is forbidden
(e.g., `origin/stable-xx`), you need to create your own remote branch,
based off of the branch that you wish to backport to. However, doing so
can involve a number of manual steps. To reduce the effort and time
involved, use the script below instead.

NOTE: The script uses `curl` and the `jq` (lightweight and flexible
command-line JSON processor) package. Please install them before first usage.

NOTE: This script uses the github API. For unauthenticated requests, the rate
limit allows for up to 60 requests per hour. Unauthenticated requests are
associated with the originating IP address, and not the user making requests.
For more information see https://developer.github.com/v3/#rate-limiting

NOTE: In case of conflicts, the script exits. The merge conflicts will need
to be resolved before manually continuing the backport.

[source,console]
----
include::examples/scripts/backport.sh
----

TIP: It is highly recommended to use the merge commit sha when backporting a Pull Request.
The merge commit includes all PR sub commits to be backported. With that, no individual
sub commit backporting is necessary.

The following example assumes that:

- You save the script in a file called `<path>/backport.sh` and mark it executable
- You have checked out the branch containing the merged sha (like `master`)
- Your merge sha = 1234567 and your target branch = stable10

The command to backport this Pull Request would be called as follows:

[source,console]
----
<path>/backport.sh 1234567 stable10
Backporting commit 1234567 to stable10
...
Switched to a new branch ‘stable10-1234567-34654‘
...
Pushing: [stable10] [PR 34654] Each generated birthday or death event gets a new UID
...
----

Please keep in mind that this is an example and you have to adapt the commit hash and the
target branch accordingly.

When the script completes, go to GitHub, where it will suggest that you
make a PR from pushed branch.

IMPORTANT: Change the base branch to be committed against,
from `master` to your target branch (in our example `stable10`) and continue.

In case you have installed the `xdg-utils` package, you can add at the
end of the script above following code which opens the PR to be
finalized in your browser:

[source,console]
----
echo "Creating pull request for branch $targetBranch in $repository"

xdg-open "https://github.com/$repository/pull/new/$targetBranch...$targetCommit"
----

NOTE: This command opens the Pull Request and sets the target branch
(in our example `stable10`) for the backport automatically.

