= Setup Your Development Environment
:toc: right

== Introduction

This page helps with setting up your environment for use with and developing ownCloud.

Feel free to skip already one or more of the following steps, if you have already completed them.
Otherwise, if you’re just getting started, begin by getting the ownCloud source code.

[[install-the-core-software]]
== Install the Core Software

The first thing to do is to ensure that your server has the necessary software for installing and running ownCloud.
While you can go further, you need to install at least
xref:admin_manual:installation/manual_installation.adoc#install-the-required-packages[the required packages].
Then, you will need to install the software required to run the development environment's installation process.

* https://www.gnu.org/software/make/[Make]
* https://nodejs.org[Node.js]
* https://git-scm.com/[git]
* https://www.npmjs.com/[npm]
* https://linux.die.net/man/1/unzip[unzip]
* https://www.gnu.org/software/wget/[wget]

[[install-dependencies-on-ubuntu-16.04]]
=== Install Dependencies on Ubuntu 16.04/18.04

==== Install nodejs, make, unzip, and git

[source,console]
....
cd ~
curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get -y -q update
sudo apt-get -y -q upgrade
sudo apt-get install nodejs build-essential make unzip git
....

==== Install Composer

===== Prepare the Installation

[source,console]
....
cd ~/tmp
sudo apt-get install wget php-cli php-zip
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
HASH="$(wget -q -O - https://composer.github.io/installer.sig)"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
....

If the hashes match, you will see the following output:

....
Installer verified
....

===== Install Composer

To install Composer, run the following command:

[source,console]
....
sudo php composer-setup.php \
    --install-dir=/usr/local/bin \
    --filename=composer
....

Running the command will produce output similar to the following.

....
All settings correct for using Composer
Downloading...

Composer (version 1.7.2) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer
....

===== Verify the Installation

To verify that Composer is properly installed, run `composer`. 
You should see output similar to that below.

[source,console]
....
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.8.4 2019-02-11 10:52:10
....

Composer is fully installed, and ready to be used.

==== Install Yarn


[source,console]
....
# Enable the Yarn repository
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

# Add the Yarn APT repository to your system’s software repository list:
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

# Update the package list and install Yarn:
sudo apt-get update
sudo apt-get install --no-install-recommends yarn
....

===== Verify that Yarn installed successfully:

After you have installed yarn, you can run `yarn --version` to confirm that it’s fully installed. 
If it is, then it will print output similar to the following to the console.

....
yarn version v1.13.0
....

[[install-dependencies-on-opensuse-leap-42.3]]
=== Install Dependencies on openSUSE Leap 42.3

....
# Ensure that Zypper's cache is up to date
sudo zypper --non-interactive --quiet \
   update --auto-agree-with-licenses --best-effort

# Auto-install the required dependencies with a minimum of output
sudo zypper --quiet --non-interactive install \
    wget make nodejs6 nodejs-common unzip git
    npm6 phantomjs php7-curl php7-openssl openssl php7-phar
....

[[setup-the-webserver-and-database]]
== Setup the Webserver and Database

Next, you need to setup your web and database servers, so that they work
properly with ownCloud. The respective guides are available at:

* xref:admin_manual:installation/manual_installation.adoc#configure-apache-web-server[Apache Webserver Configuration]
* xref:admin_manual:configuration/database/linux_database_configuration.adoc[Database Server Configuration]

[[get-the-source]]
== Get The Source

With the web and database servers setup, you next need to get a copy of
ownCloud. There are two ways to do so:

1.  Use a xref:admin_manual:installation/manual_installation.adoc[manual installation]
2.  Use a xref:admin_manual:installation/linux_installation.adoc[Linux Package Manager Installation]
3.  Clone the development version from https://github.com/owncloud[GitHub]:

For the sake of a brief example, assuming you chose to clone from
GitHub, here’s an example of how to do so:

....
# Assuming that /var/www/html is the webserver's document root
git clone https://github.com/owncloud/core.git /var/www/html/core
....

*What is the Web Server’s Root Directory?*

The quickest way to find out is by using the `ls` command, for example:
`ls -lah /var/wwww`. Depending on your Linux distribution, it’s likely
to be one of `/var/www`, `/var/www/html`, or `/srv/http`.

[[set-user-group-and-permissions]]
=== Set User, Group, and Permissions

You now need to make sure that the web server user (and optionally the
web server’s group) have read/write access to the directory where you
installed ownCloud: The following commands assume that `/var/www` is the
web server’s directory and that `www-data` is the web server user and
group. The following commands will do this:

....
# Set the user and group to the webserver user and group
sudo chown -R www-data:www-data /var/www/html/core/

# Set read/write permissions on the directory
sudo chmod o+rw /var/www/html/core/
....

*What is the Web Server’s User and Group?*

There are a few ways to identify the user and group the webserver is
running as. Likely the easiest are `grep` and `ps`. Here’s an example of
using both (which assumes that the distribution is Ubuntu 16.04).

....
# Find the user defined in Apache's configuration files
grep -r 'APACHE_RUN_USER' /etc/apache2/

# Find the user that's running Apache.
ps -aux | grep apache2
....

Depending on your distribution, it will likely be one of `http`, `www-data`, `apache`, or `wwwrun`.


[[install-software-dependencies]]
== Install Software Dependencies

With the ownCloud source
xref:admin_manual:installation/manual_installation.adoc#configure-apache-web-server[available to your webserver],
next install ownCloud’s dependencies by running
https://www.gnu.org/software/make/[Make], from the directory where
ownCloud’s located. Here’s an example of how to do so:

[source,console]
----
# Assuming that the ownCloud source is located in `/var/www/html/core`
cd /var/www/html/core && make
----

By default, running `make` will install the required dependencies for
both PHP and JavaScript. However, there are other options that it
supports, which you can see in the table below, which are useful for a
variety of tasks.

[cols=",",options="header",]
|===
| Target     | Description
| make       | Pulls in both Composer and Bower dependencies
| make clean | Cleans up dependencies. This is useful for starting over or when switching to older branches
| make dist  | Builds a minimal owncloud-core tarball with only core apps in build/dist/core, stripped
of unwanted files
| make docs  | Builds the JavaScript documentation using http://usejsdoc.org[JSDoc]
| make test  | Runs all of the test targets
| make test-external | Runs one of the external storage tests, and is configurable through make variables
| make test-js  | Runs the Javascript unit tests, replacing ./autotest-js.sh
| make test-php | Runs the PHPUnit tests with SQLite as the data source. +
This replaces ./autotest.sh sqlite and is configurable through make variables
|===

[[enable-debug-mode]]
== Enable Debug Mode

Now that ownCloud’s available to your web server and the dependencies
are installed, we strongly encourage you to disable JavaScript and CSS
caching during development. This is so that when changes are made,
they’re immediately visible, not at some later stage when the respective
caches expire. To do so, enable debug mode by setting `debug` to `true`
in config/config.php, as in the example below.

[source,php]
----
<?php

$CONFIG = [
    'debug' => true,
    ... configuration goes here ...
];
----

Do not enable this for production! This can create security problems and
is only meant for debugging and development!

[[setup-owncloud]]
== Setup ownCloud

With all that done, you’re now ready to use either
xref:admin_manual:installation/installation_wizard.adoc[the installation wizard] or
xref:admin_manual:installation/command_line_installation.adoc[command line installer]
to finish setting up ownCloud.
