= Setup Your Development Environment based on docker

Using docker containers makes it such easier to create a execution-environment
for developing. As a developer you nearly don't have to take care about myslq, redis or
apache configuration. Most of the things are done by container orchestration.

The environment is described in a docker-compose.yml file.

To be able to use and develop ownCloud using docker follow these steps.

1. xref:get-the-source[Get the source]
2. xref:prerequisite[Prerequisite]
3.  xref:build-a-docker-container[Build a docker container]
4.  xref:create-the-environment-with-docker-compose[Create the environment with docker-compose]
5.  xref:set-user-group-and-permissions[Install software dependencies]
6.  xref:enable-debug-mode[Enable debug mode]
7.  xref:setup-owncloud[Setup ownCloud]

[[get-the-source]]
== Get the source
Get the owncloud source code from one of the next options:

1. Download a tarball from here https://owncloud.org/download/#owncloud-server-tar-ball
2. Create a clone of the github repo you can find here https://github.com/owncloud/core

Be aware that cloning the git-repo brings a very raw version of owncloud.
It must be enriched with some other apps inside the `owncloud/apps`
folder. It is possible to clone some different apps to that location.
The `user_management` app for example.

For both cases place the code in a folder inside your home directory

[source,console]
....
/home/<your-username>/src/owncloud
....

for example.

[[prerequisite]]
== Prerequisite

Let's assume that you already have installed `docker` and `docker-compose` on your computer.

Make shure that you have created a folder parallel to the owncloud sources.

[source,console]
....
/home/<your-username>/src/oc_dev_docker
....

[[build-a-docker-container]]
=== Build a docker container

Create a file named `dockerfile` with the following content inside that directory.
[source,console]
----
FROM owncloud/base:bionic

RUN apt-get update &&\
    apt-get install -y npm make && \
    npm install -g yarn
----

Now that you have created a `dockerfile` you can build your docker image.
Open a terminal application and execute the following commands:

[source,console]
....
cd /home/<your-username>/src/oc_dev_docker
docker build -t oc_dev:latest .
....

After the command has terminated succesfully check if you can find the new image
with the command

[source,console]
....
docker images
....

[[create-the-environment-with-docker-compose]]
== Create the environmane with `docker-compose`

A good point to start for creating an environment for running an owncloud instance
is the `docker-compose.yml' provided by owncloud. You can find it here:

https://github.com/owncloud-docker/server/blob/master/docker-compose.yml

Generally it is designed to create a very simple production environment. Make
some modifications to it:

First change the container image that is used with the owncloud service. Search for the services section
and replace

[source, yml]
....
services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
....

with
[source,yml]
....
services:
  owncloud:
    image: owncloud/oc_dev:latest
....

the container prepared before.

Also it is necessary to mount the source folder into the container. To do so add a line to the volumes section
inside the owncloud service

[source,yml]
....
services:
  owncloud:
    image: owncloud/oc_dev:latest
    .
    .
    .
    volumes:
      - files:/mnt/data
      - ../owncloud:/var/www/owncloud
....

Start the environment with the command

[source,console]
....
cd /home/<your-username>/src/oc_dev_docker
docker-compose up
....

Before it is possible to access the application it must be build.
To achive this the `make` command inside the container must be executed. To attach to the
container find out its name with
[source,console]
....
docker ps
....
In the responging tabel search for the image name `oc_dev:latest` and take the container name from the last colume
for the next command:

[source,console]
....
docker exec -ti <container_name> /bin/bash
....

Now the prompt changes to something like:
[source,console]
....
root@ebd5bf5a33c0: /var/www/owncloud
....

simply type `make` and wait until everything is ready. Open a browser and try to access
http://localhost.

With the access to the container it is also possible to use the `occ` command.

[[enable-debug-mode]]
== Enable Debug Mode

Now that ownCloud’s available to your web server and the dependencies
are installed, we strongly encourage you to disable JavaScript and CSS
caching during development. This is so that when changes are made,
they’re immediately visible, not at some later stage when the respective
caches expire. To do so, enable debug mode by setting `debug` to `true`
in config/config.php, as in the example below.

[source,php]
----
<?php

$CONFIG = [
    'debug' => true,
    ... configuration goes here ...
];
----

Do not enable this for production! This can create security problems and
is only meant for debugging and development!

[[setup-owncloud]]
== Setup ownCloud

With all that done, you’re now ready to use either
xref:admin_manual:installation/installation_wizard.adoc[the installation wizard] or
xref:admin_manual:installation/command_line_installation.adoc[command line installer]
to finish setting up ownCloud.
