:iscsi_initiator-url: https://ubuntu.com/server/docs/service-iscsi
:overriding-vendor-settings-url: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
:transport-huge-pages-url: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/performance_tuning_guide/s-memory-transhuge

== Start a Service After a Resource is Mounted

If you have network resources, such as NFS or iSCSI based mounts, and you want to make
sure that the database or web server only starts _after_ the resource is mounted,
then consider the following example setup when configuring your system.

The example below is based on an NFS mount which you want to be available _before_ the service
with <name.service> starts. The same procedure can be used for iSCSI. For details setting up an
iSCSI mount see the {iscsi_initiator-url}[Ubuntu iSCSI Initiator] guide.

The name in <name.service> could be any valid service, including `apache2`, `mysql` or `mariadb`.

* Add `_netdev` to the list of NFS mount point options in `/etc/fstab`.
+
--
This option ensures, that the mount happens _after_ the network is up:

[source,console]
----
resource:foreign_path local_path nfs (<your options>),_netdev
----
--

* Make sure that all mounts in `/etc/fstab` are mounted by running:
+
--
[source,console]
----
sudo mount -a
----
--

* Run the following command to list mounts which must be up first:
+
--
[source,console]
----
systemctl list-units | grep -nP "\.mount"
----

You should see lines printed to the console.
Look for the mount you want to be up in the command's output.

[source,console]
----
<folder.mount>
  loaded active mounted <local_path>
----
where `<folder.mount>` and `<local_path>` are examples!
--

* Edit the service you want to change:
+
--
[source,console]
----
sudo systemctl edit <name>.service
----

Add the following directive in the editor opened, using your chosen `folder.mount` from above:

[source,console]
----
[Unit]
After=folder.mount
----

You can add more than one dependency if needed by separating them with spaces. This procedure
keeps `<name>.service` in its original state but makes it possible to override the current
setup with new parameters. This is necessary, because on updates, the original service data will
be overwritten. It automatically creates a directory in `/etc/systemd/system`, named
`<name>.service.d`, and a file in that directory called `override.conf`. In the example
above, the parameter is added to the existing list of parameters of the `After` directive.

For more details please read section {overriding-vendor-settings-url}[Example 2. Overriding vendor settings]

Please keep the following points in mind, regarding if `<name>.service` is linked or not:

** If the file is linked from `/lib/systemd/system`, it is for packaged unit files.
They are overwritten when Systemd (or whatever package provides them) is upgraded.

** If the file originates in `/etc/systemd/system`, it is for your own and customised unit files.
Unit files you place in here override the package-provided file and will not be replaced on upgrade.

It is recommended to keep things simple and future-proof by creating an override file via `systemctl edit`.
--

* Run the following command to apply your changes:
+
--
[source,console]
----
sudo systemctl daemon-reload
----
--

* Check if `<name>.service` has been properly added:
+
--
[source,console]
----
sudo systemctl show <name>.service | grep "After="
----
`folder.mount` should be part of the parameter list.
--

* Restart your service by invoking:
+
--
[source,console]
----
sudo system <name> restart
----
--

== Disable Transparent Huge Pages (THP)

{transport-huge-pages-url}[Transparent Huge Pages] should be disabled when using databases.
This is applicable when using Redis, as well as MariaDB. For more information read:
{disabling-thp-url}[Why THP (Transparent Huge Pages) are not recommended for Databases].

To disable Transparent Huge Pages, follow these steps:

* Create in `/etc/systemd/system` a file like `disable-thp.service` add the following content:
+
--
[source,console]
----
[Unit]
Description=Disable Transparent Huge Pages
DefaultDependencies=no
After=sysinit.target local-fs.target
Before=basic.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c '/bin/echo never > /sys/kernel/mm/transparent_hugepage/enabled'
ExecStart=/bin/sh -c '/bin/echo never > /sys/kernel/mm/transparent_hugepage/defrag'

[Install]
WantedBy=basic.target
----
--

* Run the following command to apply and activate your changes and start it automatically at boot time:
+
--
[source,console]
----
sudo systemctl daemon-reload
sudo systemctl enable disable-thp
sudo service disable-thp start
----
--

