= Install ownCloud on Ubuntu 20.04
:toc: right
:logrotate-url: https://linux.die.net/man/8/logrotate
:webserver-user: www-data
:webserver-group: www-data
:install-directory: /var/www/owncloud
:page-aliases: installation/quick_guides/ubuntu_18_04.adoc

== Introduction

This is a short guide to installing ownCloud on a fresh installation of Ubuntu 20.04.
Run the following commands in your terminal to complete the installation.

NOTE: This guide can not go into details and has its limits by nature. If you experience issues like with dependencies of PHP or other relevant things like the operating system, web server or database, look at the xref:installation/manual_installation/manual_installation.adoc#ubuntu-20-04-lts-server[Detailed Installation Guide]
for more information.

== Prerequisites

* A fresh installation of https://www.ubuntu.com/download/server[Ubuntu 20.04] with SSH enabled.
* This guide assumes that you are working as the root user.
* Your ownCloud directory will be located in `/var/www/owncloud/`

== Preparation

First, ensure that all the installed packages are entirely up to date and that PHP is available in the APT repository.
To do so, follow the instructions below:

----
apt update && \
  apt upgrade -y
----

=== Create the occ Helper Script

Create a helper script to simplify running xref:configuration/server/occ_command.adoc[occ commands].

[source,console,subs="attributes+"]
----
FILE="/usr/local/bin/occ"
/bin/cat <<EOM >$FILE
#! /bin/bash
cd {install-directory}
sudo -E -u {webserver-user} /usr/bin/php {install-directory}/occ "\$@"
EOM
----

Make the helper script executable:

----
chmod +x /usr/local/bin/occ
----

=== Install the Required Packages

----
apt install -y \
  apache2 \
  libapache2-mod-php \
  mariadb-server \
  openssl redis-server wget \
  php-imagick php-common php-curl \
  php-gd php-imap php-intl \
  php-json php-mbstring php-mysql \
  php-ssh2 php-xml php-zip \
  php-apcu php-redis php-ldap 
----

Note : php 7.4 is the default version installable with Ubuntu 20.04

=== Install the Recommended Packages

----
apt install -y \
  ssh bzip2 rsync curl jq \
  inetutils-ping coreutils \
  imagemagick
----

== Installation

=== Configure Apache

==== Change the Document Root

----
sed -i "s#html#owncloud#" /etc/apache2/sites-available/000-default.conf
service apache2 restart
----

==== Create a Virtual Host Configuration

[source,console,subs="attributes+"]
----
include::{examplesdir}installation/ubuntu/18.04/create-vhost-config.sh[]
----

==== Enable the Virtual Host Configuration

----
a2ensite owncloud.conf
service apache2 reload
----

=== Configure the Database

----
mysql -u root -e "CREATE DATABASE IF NOT EXISTS owncloud; \
GRANT ALL PRIVILEGES ON owncloud.* \
  TO owncloud@localhost \
  IDENTIFIED BY 'password'";
----

==== Enable the Recommended Apache Modules

----
echo "Enabling Apache Modules"
a2enmod dir env headers mime rewrite setenvif
service apache2 reload
----

=== Download ownCloud

[source,console,subs="attributes+"]
----
cd /var/www/
wget https://download.owncloud.org/community/{oc-complete-name}.tar.bz2 && \
tar -xjf {oc-complete-name}.tar.bz2 && \
chown -R www-data. owncloud
----

=== Install ownCloud

----
occ maintenance:install \
    --database "mysql" \
    --database-name "owncloud" \
    --database-user "owncloud" \
    --database-pass "password" \
    --admin-user "admin" \
    --admin-pass "admin"
----

=== Configure ownCloud's Trusted Domains

----
myip=$(hostname -I|cut -f1 -d ' ')
occ config:system:set trusted_domains 1 --value="$myip"
----

=== Set Up a Cron Job

Set your background job mode to cron

----
occ background:cron
----

[source,console,subs="attributes+"]
----
echo "*/15  *  *  *  * /var/www/owncloud/occ system:cron" \
  > /var/spool/cron/crontabs/{webserver-user}
chown {webserver-user}.crontab /var/spool/cron/crontabs/{webserver-user}
chmod 0600 /var/spool/cron/crontabs/{webserver-user}
----

[NOTE]
====
If you need to sync your users from an LDAP or Active Directory Server, add this additional xref:configuration/server/background_jobs_configuration.adoc[Cron job]. Every 15 minutes this cron job will sync LDAP users in ownCloud and disable the ones who are not available for ownCloud. Additionally, you get a log file in `/var/log/ldap-sync/user-sync.log` for debugging.
====

[source,subs="attributes+"]
----
echo "*/15 * * * * /var/www/owncloud/occ user:sync 'OCA\User_LDAP\User_Proxy' -m disable -vvv >> /var/log/ldap-sync/user-sync.log 2>&1" >> /var/spool/cron/crontabs/{webserver-user}
chown {webserver-user}.crontab  /var/spool/cron/crontabs/{webserver-user}
chmod 0600  /var/spool/cron/crontabs/{webserver-user}
mkdir -p /var/log/ldap-sync
touch /var/log/ldap-sync/user-sync.log
chown {webserver-user}. /var/log/ldap-sync/user-sync.log
----

=== Configure Caching and File Locking

Execute these commands:

[source,php,subs="attributes+"]
----
occ config:system:set \
   memcache.local \
   --value '\OC\Memcache\APCu'
occ config:system:set \
   memcache.locking \
   --value '\OC\Memcache\Redis'
occ config:system:set \
   redis \
   --value '{"host": "127.0.0.1", "port": "{std-port-redis}"}' \
   --type json
----

=== Configure Log Rotation

Execute this command to set up {logrotate-url}[log rotation].

[source,console,subs="attributes+"]
----
include::{examplesdir}installation/ubuntu/18.04/configure-log-rotation.sh[]
----

==== Finalise the Installation

Make sure the permissions are correct
----
cd /var/www/
chown -R www-data. owncloud
----

**ownCloud is now installed.
You can confirm that it is ready to use by pointing your web browser to your ownCloud installation.**

IMPORTANT: We recommend you check out the section xref:configuration/server/harden_server.adoc[Hardening and Security Guidance] next.
