= Notifications

In this document, you can learn how to send notifications in apps.

== Sending Notifications

To send notifications from your app, requires four steps, these are:

. Fetch the notification manager from the server.
. Use the notification manager to create a notification object.
. Set the notification's information
. Send the notification.

You can see an example of how to perform all of these steps in the example below.
The notification has a number of properties set that help identify the app that should receive it, along with information for the receiving app to use, once the notification has been received.

[source,php]
----
include::{examplesdir}app/advanced/notifications/intro-notification.php[]
----

TIP: Make sure the app set in the notification matches the one you're expecting, because other notifications for other apps might reach your notifier. 
Throw an `InvalidArgumentException` if this isn't the case.

TIP: The notification's subject and message should be set using translated strings.

In case you need to add some actions to the notification (e.g., to accept or reject shares, or other kind of actions): 

. Create the action from the notification
. Fill the action data
. Add the action in the notification

You can see an example of how to perform all of these steps in the example below.

[source,php]
----
include::{examplesdir}app/advanced/notifications/notification-with-object.php[]
----
